// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: materialization.sql

package materializedb

import (
	"context"
	"database/sql"
)

const cancelQueuedChildMaterializationRuns = `-- name: CancelQueuedChildMaterializationRuns :exec
UPDATE refresh_job_runs
SET status = ?1, finished_at = CURRENT_TIMESTAMP, error = ''
WHERE refresh_job_runs.parent_run_id = ?2
  AND refresh_job_runs.status = ?3
  AND refresh_job_runs.job_id IN (SELECT id FROM refresh_jobs WHERE workspace_id = ?4)
`

type CancelQueuedChildMaterializationRunsParams struct {
	CancelledStatus string         `json:"cancelled_status"`
	ParentRunID     sql.NullString `json:"parent_run_id"`
	QueuedStatus    string         `json:"queued_status"`
	WorkspaceID     string         `json:"workspace_id"`
}

func (q *Queries) CancelQueuedChildMaterializationRuns(ctx context.Context, arg CancelQueuedChildMaterializationRunsParams) error {
	_, err := q.db.ExecContext(ctx, cancelQueuedChildMaterializationRuns,
		arg.CancelledStatus,
		arg.ParentRunID,
		arg.QueuedStatus,
		arg.WorkspaceID,
	)
	return err
}

const cancelQueuedChildRefreshJobs = `-- name: CancelQueuedChildRefreshJobs :exec
UPDATE refresh_jobs
SET status = ?1, finished_at = CURRENT_TIMESTAMP,
    lease_owner = '', lease_expires_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE refresh_jobs.workspace_id = ?2
  AND refresh_jobs.status = ?3
  AND refresh_jobs.id IN (SELECT job_id FROM refresh_job_runs WHERE parent_run_id = ?4)
`

type CancelQueuedChildRefreshJobsParams struct {
	CancelledStatus string         `json:"cancelled_status"`
	WorkspaceID     string         `json:"workspace_id"`
	QueuedStatus    string         `json:"queued_status"`
	ParentRunID     sql.NullString `json:"parent_run_id"`
}

func (q *Queries) CancelQueuedChildRefreshJobs(ctx context.Context, arg CancelQueuedChildRefreshJobsParams) error {
	_, err := q.db.ExecContext(ctx, cancelQueuedChildRefreshJobs,
		arg.CancelledStatus,
		arg.WorkspaceID,
		arg.QueuedStatus,
		arg.ParentRunID,
	)
	return err
}

const cancelQueuedMaterializationRun = `-- name: CancelQueuedMaterializationRun :execresult
UPDATE refresh_job_runs
SET status = ?1, finished_at = CURRENT_TIMESTAMP, error = ''
WHERE refresh_job_runs.id = ?2
  AND refresh_job_runs.status = ?3
  AND refresh_job_runs.job_id IN (
    SELECT refresh_jobs.id FROM refresh_jobs WHERE refresh_jobs.workspace_id = ?4
  )
`

type CancelQueuedMaterializationRunParams struct {
	CancelledStatus string `json:"cancelled_status"`
	RunID           string `json:"run_id"`
	QueuedStatus    string `json:"queued_status"`
	WorkspaceID     string `json:"workspace_id"`
}

func (q *Queries) CancelQueuedMaterializationRun(ctx context.Context, arg CancelQueuedMaterializationRunParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, cancelQueuedMaterializationRun,
		arg.CancelledStatus,
		arg.RunID,
		arg.QueuedStatus,
		arg.WorkspaceID,
	)
}

const cancelQueuedRefreshJobForRun = `-- name: CancelQueuedRefreshJobForRun :exec
UPDATE refresh_jobs
SET status = ?1, finished_at = CURRENT_TIMESTAMP,
    lease_owner = '', lease_expires_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE refresh_jobs.id = (SELECT refresh_job_runs.job_id FROM refresh_job_runs WHERE refresh_job_runs.id = ?2)
  AND refresh_jobs.workspace_id = ?3
  AND refresh_jobs.status = ?4
`

type CancelQueuedRefreshJobForRunParams struct {
	CancelledStatus string `json:"cancelled_status"`
	RunID           string `json:"run_id"`
	WorkspaceID     string `json:"workspace_id"`
	QueuedStatus    string `json:"queued_status"`
}

func (q *Queries) CancelQueuedRefreshJobForRun(ctx context.Context, arg CancelQueuedRefreshJobForRunParams) error {
	_, err := q.db.ExecContext(ctx, cancelQueuedRefreshJobForRun,
		arg.CancelledStatus,
		arg.RunID,
		arg.WorkspaceID,
		arg.QueuedStatus,
	)
	return err
}

const claimRefreshJob = `-- name: ClaimRefreshJob :execresult
UPDATE refresh_jobs
SET status = ?1, started_at = COALESCE(started_at, CURRENT_TIMESTAMP), finished_at = NULL,
    lease_owner = ?2, lease_expires_at = datetime('now', CAST(?3 AS TEXT)),
    attempt_count = attempt_count + 1, lease_generation = lease_generation + 1, updated_at = CURRENT_TIMESTAMP
WHERE id = ?4
  AND (
    status = ?5
    OR (status = ?6 AND (lease_expires_at IS NULL OR lease_expires_at <= CURRENT_TIMESTAMP))
  )
`

type ClaimRefreshJobParams struct {
	RunningStatus         string `json:"running_status"`
	LeaseOwner            string `json:"lease_owner"`
	LeaseModifier         string `json:"lease_modifier"`
	ID                    string `json:"id"`
	QueuedStatus          string `json:"queued_status"`
	PreviousRunningStatus string `json:"previous_running_status"`
}

func (q *Queries) ClaimRefreshJob(ctx context.Context, arg ClaimRefreshJobParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, claimRefreshJob,
		arg.RunningStatus,
		arg.LeaseOwner,
		arg.LeaseModifier,
		arg.ID,
		arg.QueuedStatus,
		arg.PreviousRunningStatus,
	)
}

const completeRefreshJobFailed = `-- name: CompleteRefreshJobFailed :exec
UPDATE refresh_jobs
SET status = 'failed', updated_at = CURRENT_TIMESTAMP, finished_at = CURRENT_TIMESTAMP,
    lease_owner = '', lease_expires_at = NULL, last_error = ?1
WHERE refresh_jobs.id = (SELECT job_id FROM refresh_job_runs WHERE refresh_job_runs.id = ?2)
  AND workspace_id = ?3
`

type CompleteRefreshJobFailedParams struct {
	ErrorMessage string `json:"error_message"`
	RunID        string `json:"run_id"`
	WorkspaceID  string `json:"workspace_id"`
}

func (q *Queries) CompleteRefreshJobFailed(ctx context.Context, arg CompleteRefreshJobFailedParams) error {
	_, err := q.db.ExecContext(ctx, completeRefreshJobFailed, arg.ErrorMessage, arg.RunID, arg.WorkspaceID)
	return err
}

const completeRefreshJobSucceeded = `-- name: CompleteRefreshJobSucceeded :exec
UPDATE refresh_jobs
SET status = 'succeeded', updated_at = CURRENT_TIMESTAMP, finished_at = CURRENT_TIMESTAMP,
    lease_owner = '', lease_expires_at = NULL
WHERE refresh_jobs.id = (SELECT job_id FROM refresh_job_runs WHERE refresh_job_runs.id = ?1)
  AND workspace_id = ?2
`

type CompleteRefreshJobSucceededParams struct {
	RunID       string `json:"run_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) CompleteRefreshJobSucceeded(ctx context.Context, arg CompleteRefreshJobSucceededParams) error {
	_, err := q.db.ExecContext(ctx, completeRefreshJobSucceeded, arg.RunID, arg.WorkspaceID)
	return err
}

const createRefreshJob = `-- name: CreateRefreshJob :exec

INSERT INTO refresh_jobs (id, workspace_id, serving_state_id, model_id, kind, payload_json, status, queued_at)
VALUES (?1, ?2, NULLIF(CAST(?3 AS TEXT), ''), ?4, ?5, ?6, ?7, CURRENT_TIMESTAMP)
`

type CreateRefreshJobParams struct {
	ID             string `json:"id"`
	WorkspaceID    string `json:"workspace_id"`
	ServingStateID string `json:"serving_state_id"`
	ModelID        string `json:"model_id"`
	Kind           string `json:"kind"`
	PayloadJson    string `json:"payload_json"`
	Status         string `json:"status"`
}

// Refresh execution, materialization runs, and durable scheduling jobs.
func (q *Queries) CreateRefreshJob(ctx context.Context, arg CreateRefreshJobParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshJob,
		arg.ID,
		arg.WorkspaceID,
		arg.ServingStateID,
		arg.ModelID,
		arg.Kind,
		arg.PayloadJson,
		arg.Status,
	)
	return err
}

const createRefreshJobRun = `-- name: CreateRefreshJobRun :exec
INSERT INTO refresh_job_runs (
  id, job_id, principal_id, environment, target_type, target_id, trigger_type,
  parent_run_id, retry_of, status, target_generation, created_sequence
)
VALUES (
  ?1, ?2, NULLIF(CAST(?3 AS TEXT), ''),
  ?4, ?5, ?6, ?7,
  NULLIF(CAST(?8 AS TEXT), ''), NULLIF(CAST(?9 AS TEXT), ''),
  ?10,
  CASE WHEN CAST(?11 AS INTEGER) > 0 THEN CAST(?11 AS INTEGER)
    ELSE COALESCE((
      SELECT MAX(existing.target_generation) + 1
      FROM refresh_job_runs existing
      JOIN refresh_jobs existing_job ON existing_job.id = existing.job_id
      JOIN refresh_jobs new_job ON new_job.id = ?2
      WHERE existing_job.workspace_id = new_job.workspace_id
        AND existing.environment = ?4
        AND existing.target_type = ?5
        AND existing.target_id = ?6
    ), 1)
  END,
  COALESCE((SELECT MAX(created_sequence) + 1 FROM refresh_job_runs), 1)
)
`

type CreateRefreshJobRunParams struct {
	ID               string `json:"id"`
	JobID            string `json:"job_id"`
	PrincipalID      string `json:"principal_id"`
	Environment      string `json:"environment"`
	TargetType       string `json:"target_type"`
	TargetID         string `json:"target_id"`
	TriggerType      string `json:"trigger_type"`
	ParentRunID      string `json:"parent_run_id"`
	RetryOf          string `json:"retry_of"`
	Status           string `json:"status"`
	TargetGeneration int64  `json:"target_generation"`
}

func (q *Queries) CreateRefreshJobRun(ctx context.Context, arg CreateRefreshJobRunParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshJobRun,
		arg.ID,
		arg.JobID,
		arg.PrincipalID,
		arg.Environment,
		arg.TargetType,
		arg.TargetID,
		arg.TriggerType,
		arg.ParentRunID,
		arg.RetryOf,
		arg.Status,
		arg.TargetGeneration,
	)
	return err
}

const failCancelledRefreshCandidate = `-- name: FailCancelledRefreshCandidate :execresult
UPDATE serving_states
SET status = 'failed', error = 'refresh cancelled'
WHERE id = ?1
  AND source = 'refresh'
  AND status = 'validated'
`

func (q *Queries) FailCancelledRefreshCandidate(ctx context.Context, servingStateID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, failCancelledRefreshCandidate, servingStateID)
}

const failTerminalServingStateJobs = `-- name: FailTerminalServingStateJobs :exec
UPDATE refresh_jobs
SET status = ?1, updated_at = CURRENT_TIMESTAMP
WHERE refresh_jobs.status IN (?2, ?3)
  AND serving_state_id IN (
    SELECT id FROM serving_states
    WHERE environment = ?4
      AND status IN ('failed', 'delete_scheduled', 'deleted')
  )
`

type FailTerminalServingStateJobsParams struct {
	FailedStatus  string `json:"failed_status"`
	QueuedStatus  string `json:"queued_status"`
	RunningStatus string `json:"running_status"`
	Environment   string `json:"environment"`
}

func (q *Queries) FailTerminalServingStateJobs(ctx context.Context, arg FailTerminalServingStateJobsParams) error {
	_, err := q.db.ExecContext(ctx, failTerminalServingStateJobs,
		arg.FailedStatus,
		arg.QueuedStatus,
		arg.RunningStatus,
		arg.Environment,
	)
	return err
}

const failTerminalServingStateRuns = `-- name: FailTerminalServingStateRuns :exec
UPDATE refresh_job_runs
SET status = ?1, finished_at = CURRENT_TIMESTAMP,
    error = CASE WHEN error <> '' THEN error ELSE ?2 END
WHERE refresh_job_runs.status IN (?3, ?4)
  AND job_id IN (
    SELECT j.id FROM refresh_jobs j
    JOIN serving_states d ON d.id = j.serving_state_id
    WHERE d.environment = ?5
      AND d.status IN ('failed', 'delete_scheduled', 'deleted')
  )
`

type FailTerminalServingStateRunsParams struct {
	FailedStatus  string `json:"failed_status"`
	ErrorMessage  string `json:"error_message"`
	QueuedStatus  string `json:"queued_status"`
	RunningStatus string `json:"running_status"`
	Environment   string `json:"environment"`
}

func (q *Queries) FailTerminalServingStateRuns(ctx context.Context, arg FailTerminalServingStateRunsParams) error {
	_, err := q.db.ExecContext(ctx, failTerminalServingStateRuns,
		arg.FailedStatus,
		arg.ErrorMessage,
		arg.QueuedStatus,
		arg.RunningStatus,
		arg.Environment,
	)
	return err
}

const getMaterializationRun = `-- name: GetMaterializationRun :one
SELECT r.id, j.workspace_id, r.environment, j.serving_state_id, j.model_id, r.principal_id,
       COALESCE(NULLIF(p.display_name, ''), NULLIF(p.email, ''), r.principal_id, '') AS principal_display_name,
       r.target_type, r.target_id, r.target_generation, r.trigger_type, r.parent_run_id, r.retry_of, r.status, j.created_at, j.updated_at,
       r.started_at, r.finished_at, r.error
FROM refresh_job_runs r
JOIN refresh_jobs j ON j.id = r.job_id
LEFT JOIN principals p ON p.id = r.principal_id
WHERE r.id = ?1 AND j.workspace_id = ?2
`

type GetMaterializationRunParams struct {
	RunID       string `json:"run_id"`
	WorkspaceID string `json:"workspace_id"`
}

type GetMaterializationRunRow struct {
	ID                   string         `json:"id"`
	WorkspaceID          string         `json:"workspace_id"`
	Environment          string         `json:"environment"`
	ServingStateID       sql.NullString `json:"serving_state_id"`
	ModelID              string         `json:"model_id"`
	PrincipalID          sql.NullString `json:"principal_id"`
	PrincipalDisplayName string         `json:"principal_display_name"`
	TargetType           string         `json:"target_type"`
	TargetID             string         `json:"target_id"`
	TargetGeneration     int64          `json:"target_generation"`
	TriggerType          string         `json:"trigger_type"`
	ParentRunID          sql.NullString `json:"parent_run_id"`
	RetryOf              sql.NullString `json:"retry_of"`
	Status               string         `json:"status"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
	StartedAt            string         `json:"started_at"`
	FinishedAt           sql.NullString `json:"finished_at"`
	Error                string         `json:"error"`
}

func (q *Queries) GetMaterializationRun(ctx context.Context, arg GetMaterializationRunParams) (GetMaterializationRunRow, error) {
	row := q.db.QueryRowContext(ctx, getMaterializationRun, arg.RunID, arg.WorkspaceID)
	var i GetMaterializationRunRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Environment,
		&i.ServingStateID,
		&i.ModelID,
		&i.PrincipalID,
		&i.PrincipalDisplayName,
		&i.TargetType,
		&i.TargetID,
		&i.TargetGeneration,
		&i.TriggerType,
		&i.ParentRunID,
		&i.RetryOf,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
	)
	return i, err
}

const getMaterializationRunCursor = `-- name: GetMaterializationRunCursor :one
SELECT j.created_at, r.created_sequence
FROM refresh_job_runs r
JOIN refresh_jobs j ON j.id = r.job_id
WHERE r.id = ?1
  AND j.workspace_id = ?2
  AND r.environment = ?3
  AND (
    CAST(?4 AS TEXT) = ''
    OR (r.target_type = CAST(?4 AS TEXT) AND r.target_id = ?5)
  )
`

type GetMaterializationRunCursorParams struct {
	RunID       string `json:"run_id"`
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
	TargetType  string `json:"target_type"`
	TargetID    string `json:"target_id"`
}

type GetMaterializationRunCursorRow struct {
	CreatedAt       string `json:"created_at"`
	CreatedSequence int64  `json:"created_sequence"`
}

func (q *Queries) GetMaterializationRunCursor(ctx context.Context, arg GetMaterializationRunCursorParams) (GetMaterializationRunCursorRow, error) {
	row := q.db.QueryRowContext(ctx, getMaterializationRunCursor,
		arg.RunID,
		arg.WorkspaceID,
		arg.Environment,
		arg.TargetType,
		arg.TargetID,
	)
	var i GetMaterializationRunCursorRow
	err := row.Scan(&i.CreatedAt, &i.CreatedSequence)
	return i, err
}

const getRefreshJobQueueStats = `-- name: GetRefreshJobQueueStats :one
SELECT
  CAST(COALESCE(SUM(CASE WHEN j.status = ?1 THEN 1 ELSE 0 END), 0) AS INTEGER) AS queued_jobs,
  CAST(COALESCE(SUM(CASE WHEN j.status = ?2 AND j.lease_expires_at IS NOT NULL AND j.lease_expires_at > CURRENT_TIMESTAMP THEN 1 ELSE 0 END), 0) AS INTEGER) AS running_jobs,
  CAST(COALESCE(SUM(CASE WHEN j.status = ?3 AND (j.lease_expires_at IS NULL OR j.lease_expires_at <= CURRENT_TIMESTAMP) THEN 1 ELSE 0 END), 0) AS INTEGER) AS stale_leased_jobs
FROM refresh_jobs j
JOIN refresh_job_runs r ON r.job_id = j.id
WHERE COALESCE(r.parent_run_id, '') = ''
  AND j.kind = ?4
  AND r.environment = ?5
`

type GetRefreshJobQueueStatsParams struct {
	QueuedStatus        string `json:"queued_status"`
	RunningStatus       string `json:"running_status"`
	StaleRunningStatus  string `json:"stale_running_status"`
	RefreshPipelineKind string `json:"refresh_pipeline_kind"`
	Environment         string `json:"environment"`
}

type GetRefreshJobQueueStatsRow struct {
	QueuedJobs      int64 `json:"queued_jobs"`
	RunningJobs     int64 `json:"running_jobs"`
	StaleLeasedJobs int64 `json:"stale_leased_jobs"`
}

func (q *Queries) GetRefreshJobQueueStats(ctx context.Context, arg GetRefreshJobQueueStatsParams) (GetRefreshJobQueueStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshJobQueueStats,
		arg.QueuedStatus,
		arg.RunningStatus,
		arg.StaleRunningStatus,
		arg.RefreshPipelineKind,
		arg.Environment,
	)
	var i GetRefreshJobQueueStatsRow
	err := row.Scan(&i.QueuedJobs, &i.RunningJobs, &i.StaleLeasedJobs)
	return i, err
}

const latestSuccessfulMaterializationRun = `-- name: LatestSuccessfulMaterializationRun :one
SELECT r.id, j.workspace_id, r.environment, j.serving_state_id, j.model_id, r.principal_id,
       COALESCE(NULLIF(p.display_name, ''), NULLIF(p.email, ''), r.principal_id, '') AS principal_display_name,
       r.target_type, r.target_id, r.target_generation, r.trigger_type, r.parent_run_id, r.retry_of, r.status, j.created_at, j.updated_at,
       r.started_at, r.finished_at, r.error
FROM refresh_job_runs r
JOIN refresh_jobs j ON j.id = r.job_id
LEFT JOIN principals p ON p.id = r.principal_id
WHERE j.workspace_id = ?1 AND r.target_type = ?2
  AND r.environment = ?3
  AND r.target_id = ?4 AND r.status = ?5
ORDER BY j.created_at DESC, r.rowid DESC
LIMIT 1
`

type LatestSuccessfulMaterializationRunParams struct {
	WorkspaceID string `json:"workspace_id"`
	TargetType  string `json:"target_type"`
	Environment string `json:"environment"`
	TargetID    string `json:"target_id"`
	Status      string `json:"status"`
}

type LatestSuccessfulMaterializationRunRow struct {
	ID                   string         `json:"id"`
	WorkspaceID          string         `json:"workspace_id"`
	Environment          string         `json:"environment"`
	ServingStateID       sql.NullString `json:"serving_state_id"`
	ModelID              string         `json:"model_id"`
	PrincipalID          sql.NullString `json:"principal_id"`
	PrincipalDisplayName string         `json:"principal_display_name"`
	TargetType           string         `json:"target_type"`
	TargetID             string         `json:"target_id"`
	TargetGeneration     int64          `json:"target_generation"`
	TriggerType          string         `json:"trigger_type"`
	ParentRunID          sql.NullString `json:"parent_run_id"`
	RetryOf              sql.NullString `json:"retry_of"`
	Status               string         `json:"status"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
	StartedAt            string         `json:"started_at"`
	FinishedAt           sql.NullString `json:"finished_at"`
	Error                string         `json:"error"`
}

func (q *Queries) LatestSuccessfulMaterializationRun(ctx context.Context, arg LatestSuccessfulMaterializationRunParams) (LatestSuccessfulMaterializationRunRow, error) {
	row := q.db.QueryRowContext(ctx, latestSuccessfulMaterializationRun,
		arg.WorkspaceID,
		arg.TargetType,
		arg.Environment,
		arg.TargetID,
		arg.Status,
	)
	var i LatestSuccessfulMaterializationRunRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Environment,
		&i.ServingStateID,
		&i.ModelID,
		&i.PrincipalID,
		&i.PrincipalDisplayName,
		&i.TargetType,
		&i.TargetID,
		&i.TargetGeneration,
		&i.TriggerType,
		&i.ParentRunID,
		&i.RetryOf,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
	)
	return i, err
}

const listChildMaterializationRuns = `-- name: ListChildMaterializationRuns :many
SELECT r.id, j.workspace_id, r.environment, j.serving_state_id, j.model_id, r.principal_id,
       COALESCE(NULLIF(p.display_name, ''), NULLIF(p.email, ''), r.principal_id, '') AS principal_display_name,
       r.target_type, r.target_id, r.target_generation, r.trigger_type, r.parent_run_id, r.retry_of, r.status, j.created_at, j.updated_at,
       r.started_at, r.finished_at, r.error
FROM refresh_job_runs r
JOIN refresh_jobs j ON j.id = r.job_id
LEFT JOIN principals p ON p.id = r.principal_id
WHERE j.workspace_id = ?1 AND r.parent_run_id = ?2
ORDER BY r.rowid ASC
`

type ListChildMaterializationRunsParams struct {
	WorkspaceID string         `json:"workspace_id"`
	ParentRunID sql.NullString `json:"parent_run_id"`
}

type ListChildMaterializationRunsRow struct {
	ID                   string         `json:"id"`
	WorkspaceID          string         `json:"workspace_id"`
	Environment          string         `json:"environment"`
	ServingStateID       sql.NullString `json:"serving_state_id"`
	ModelID              string         `json:"model_id"`
	PrincipalID          sql.NullString `json:"principal_id"`
	PrincipalDisplayName string         `json:"principal_display_name"`
	TargetType           string         `json:"target_type"`
	TargetID             string         `json:"target_id"`
	TargetGeneration     int64          `json:"target_generation"`
	TriggerType          string         `json:"trigger_type"`
	ParentRunID          sql.NullString `json:"parent_run_id"`
	RetryOf              sql.NullString `json:"retry_of"`
	Status               string         `json:"status"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
	StartedAt            string         `json:"started_at"`
	FinishedAt           sql.NullString `json:"finished_at"`
	Error                string         `json:"error"`
}

func (q *Queries) ListChildMaterializationRuns(ctx context.Context, arg ListChildMaterializationRunsParams) ([]ListChildMaterializationRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChildMaterializationRuns, arg.WorkspaceID, arg.ParentRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChildMaterializationRunsRow{}
	for rows.Next() {
		var i ListChildMaterializationRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Environment,
			&i.ServingStateID,
			&i.ModelID,
			&i.PrincipalID,
			&i.PrincipalDisplayName,
			&i.TargetType,
			&i.TargetID,
			&i.TargetGeneration,
			&i.TriggerType,
			&i.ParentRunID,
			&i.RetryOf,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutableRefreshJobHeads = `-- name: ListExecutableRefreshJobHeads :many
WITH eligible AS (
  SELECT j.id, j.workspace_id, r.environment, COALESCE(j.serving_state_id, '') AS serving_state_id, j.model_id, j.kind, j.payload_json,
         r.id AS run_id, r.target_type, r.target_id, r.target_generation, r.trigger_type, j.attempt_count, j.lease_owner, j.lease_generation,
         ROW_NUMBER() OVER (
           PARTITION BY j.workspace_id
           ORDER BY COALESCE(NULLIF(j.queued_at, ''), j.created_at) ASC, j.id ASC
         ) AS workspace_position,
         COALESCE(NULLIF(j.queued_at, ''), j.created_at) AS queue_position
  FROM refresh_jobs j
  JOIN refresh_job_runs r ON r.job_id = j.id
  WHERE COALESCE(r.parent_run_id, '') = ''
    AND j.kind = ?2
    AND r.environment = ?3
    AND (
      (j.status = ?4 AND r.status = ?5)
      OR (j.status = ?6 AND (j.lease_expires_at IS NULL OR j.lease_expires_at <= CURRENT_TIMESTAMP))
    )
)
SELECT id, workspace_id, environment, serving_state_id, model_id, kind, payload_json,
       run_id, target_type, target_id, target_generation, trigger_type, attempt_count, lease_owner, lease_generation
FROM eligible
WHERE workspace_position = 1
ORDER BY queue_position ASC, id ASC
LIMIT ?1
`

type ListExecutableRefreshJobHeadsParams struct {
	ResultLimit         int64  `json:"result_limit"`
	RefreshPipelineKind string `json:"refresh_pipeline_kind"`
	Environment         string `json:"environment"`
	QueuedStatus        string `json:"queued_status"`
	RunQueuedStatus     string `json:"run_queued_status"`
	RunningStatus       string `json:"running_status"`
}

type ListExecutableRefreshJobHeadsRow struct {
	ID               string `json:"id"`
	WorkspaceID      string `json:"workspace_id"`
	Environment      string `json:"environment"`
	ServingStateID   string `json:"serving_state_id"`
	ModelID          string `json:"model_id"`
	Kind             string `json:"kind"`
	PayloadJson      string `json:"payload_json"`
	RunID            string `json:"run_id"`
	TargetType       string `json:"target_type"`
	TargetID         string `json:"target_id"`
	TargetGeneration int64  `json:"target_generation"`
	TriggerType      string `json:"trigger_type"`
	AttemptCount     int64  `json:"attempt_count"`
	LeaseOwner       string `json:"lease_owner"`
	LeaseGeneration  int64  `json:"lease_generation"`
}

func (q *Queries) ListExecutableRefreshJobHeads(ctx context.Context, arg ListExecutableRefreshJobHeadsParams) ([]ListExecutableRefreshJobHeadsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExecutableRefreshJobHeads,
		arg.ResultLimit,
		arg.RefreshPipelineKind,
		arg.Environment,
		arg.QueuedStatus,
		arg.RunQueuedStatus,
		arg.RunningStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExecutableRefreshJobHeadsRow{}
	for rows.Next() {
		var i ListExecutableRefreshJobHeadsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Environment,
			&i.ServingStateID,
			&i.ModelID,
			&i.Kind,
			&i.PayloadJson,
			&i.RunID,
			&i.TargetType,
			&i.TargetID,
			&i.TargetGeneration,
			&i.TriggerType,
			&i.AttemptCount,
			&i.LeaseOwner,
			&i.LeaseGeneration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterializationRuns = `-- name: ListMaterializationRuns :many
SELECT r.id, j.workspace_id, r.environment, j.serving_state_id, j.model_id, r.principal_id,
       COALESCE(NULLIF(p.display_name, ''), NULLIF(p.email, ''), r.principal_id, '') AS principal_display_name,
       r.target_type, r.target_id, r.target_generation, r.trigger_type, r.parent_run_id, r.retry_of, r.status,
       j.created_at, j.updated_at, r.started_at, r.finished_at, r.error
FROM refresh_job_runs r
JOIN refresh_jobs j ON j.id = r.job_id
LEFT JOIN principals p ON p.id = r.principal_id
WHERE j.workspace_id = ?1
  AND r.environment = ?2
  AND COALESCE(r.parent_run_id, '') = ''
  AND r.target_type = 'refresh_pipeline'
  AND (
    CAST(?3 AS TEXT) = ''
    OR j.created_at < CAST(?3 AS TEXT)
    OR (j.created_at = CAST(?3 AS TEXT) AND r.created_sequence < ?4)
  )
ORDER BY j.created_at DESC, r.created_sequence DESC
LIMIT ?5
`

type ListMaterializationRunsParams struct {
	WorkspaceID     string `json:"workspace_id"`
	Environment     string `json:"environment"`
	CursorCreatedAt string `json:"cursor_created_at"`
	CursorSequence  int64  `json:"cursor_sequence"`
	Limit           int64  `json:"limit"`
}

type ListMaterializationRunsRow struct {
	ID                   string         `json:"id"`
	WorkspaceID          string         `json:"workspace_id"`
	Environment          string         `json:"environment"`
	ServingStateID       sql.NullString `json:"serving_state_id"`
	ModelID              string         `json:"model_id"`
	PrincipalID          sql.NullString `json:"principal_id"`
	PrincipalDisplayName string         `json:"principal_display_name"`
	TargetType           string         `json:"target_type"`
	TargetID             string         `json:"target_id"`
	TargetGeneration     int64          `json:"target_generation"`
	TriggerType          string         `json:"trigger_type"`
	ParentRunID          sql.NullString `json:"parent_run_id"`
	RetryOf              sql.NullString `json:"retry_of"`
	Status               string         `json:"status"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
	StartedAt            string         `json:"started_at"`
	FinishedAt           sql.NullString `json:"finished_at"`
	Error                string         `json:"error"`
}

func (q *Queries) ListMaterializationRuns(ctx context.Context, arg ListMaterializationRunsParams) ([]ListMaterializationRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMaterializationRuns,
		arg.WorkspaceID,
		arg.Environment,
		arg.CursorCreatedAt,
		arg.CursorSequence,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaterializationRunsRow{}
	for rows.Next() {
		var i ListMaterializationRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Environment,
			&i.ServingStateID,
			&i.ModelID,
			&i.PrincipalID,
			&i.PrincipalDisplayName,
			&i.TargetType,
			&i.TargetID,
			&i.TargetGeneration,
			&i.TriggerType,
			&i.ParentRunID,
			&i.RetryOf,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetMaterializationRuns = `-- name: ListTargetMaterializationRuns :many
SELECT r.id, j.workspace_id, r.environment, j.serving_state_id, j.model_id, r.principal_id,
       COALESCE(NULLIF(p.display_name, ''), NULLIF(p.email, ''), r.principal_id, '') AS principal_display_name,
       r.target_type, r.target_id, r.target_generation, r.trigger_type, r.parent_run_id, r.retry_of, r.status,
       j.created_at, j.updated_at, r.started_at, r.finished_at, r.error
FROM refresh_job_runs r
JOIN refresh_jobs j ON j.id = r.job_id
LEFT JOIN principals p ON p.id = r.principal_id
WHERE j.workspace_id = ?1
  AND r.environment = ?2
  AND r.target_type = ?3
  AND r.target_id = ?4
  AND (
    CAST(?5 AS TEXT) = ''
    OR j.created_at < CAST(?5 AS TEXT)
    OR (j.created_at = CAST(?5 AS TEXT) AND r.created_sequence < ?6)
  )
ORDER BY j.created_at DESC, r.created_sequence DESC
LIMIT ?7
`

type ListTargetMaterializationRunsParams struct {
	WorkspaceID     string `json:"workspace_id"`
	Environment     string `json:"environment"`
	TargetType      string `json:"target_type"`
	TargetID        string `json:"target_id"`
	CursorCreatedAt string `json:"cursor_created_at"`
	CursorSequence  int64  `json:"cursor_sequence"`
	Limit           int64  `json:"limit"`
}

type ListTargetMaterializationRunsRow struct {
	ID                   string         `json:"id"`
	WorkspaceID          string         `json:"workspace_id"`
	Environment          string         `json:"environment"`
	ServingStateID       sql.NullString `json:"serving_state_id"`
	ModelID              string         `json:"model_id"`
	PrincipalID          sql.NullString `json:"principal_id"`
	PrincipalDisplayName string         `json:"principal_display_name"`
	TargetType           string         `json:"target_type"`
	TargetID             string         `json:"target_id"`
	TargetGeneration     int64          `json:"target_generation"`
	TriggerType          string         `json:"trigger_type"`
	ParentRunID          sql.NullString `json:"parent_run_id"`
	RetryOf              sql.NullString `json:"retry_of"`
	Status               string         `json:"status"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
	StartedAt            string         `json:"started_at"`
	FinishedAt           sql.NullString `json:"finished_at"`
	Error                string         `json:"error"`
}

func (q *Queries) ListTargetMaterializationRuns(ctx context.Context, arg ListTargetMaterializationRunsParams) ([]ListTargetMaterializationRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTargetMaterializationRuns,
		arg.WorkspaceID,
		arg.Environment,
		arg.TargetType,
		arg.TargetID,
		arg.CursorCreatedAt,
		arg.CursorSequence,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTargetMaterializationRunsRow{}
	for rows.Next() {
		var i ListTargetMaterializationRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Environment,
			&i.ServingStateID,
			&i.ModelID,
			&i.PrincipalID,
			&i.PrincipalDisplayName,
			&i.TargetType,
			&i.TargetID,
			&i.TargetGeneration,
			&i.TriggerType,
			&i.ParentRunID,
			&i.RetryOf,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMaterializationRunActive = `-- name: MarkMaterializationRunActive :execresult
UPDATE refresh_job_runs
SET status = ?1, finished_at = finished_at, error = ?2
WHERE refresh_job_runs.id = ?3
  AND job_id IN (SELECT refresh_jobs.id FROM refresh_jobs WHERE workspace_id = ?4)
`

type MarkMaterializationRunActiveParams struct {
	Status       string `json:"status"`
	ErrorMessage string `json:"error_message"`
	RunID        string `json:"run_id"`
	WorkspaceID  string `json:"workspace_id"`
}

func (q *Queries) MarkMaterializationRunActive(ctx context.Context, arg MarkMaterializationRunActiveParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markMaterializationRunActive,
		arg.Status,
		arg.ErrorMessage,
		arg.RunID,
		arg.WorkspaceID,
	)
}

const markMaterializationRunTerminal = `-- name: MarkMaterializationRunTerminal :execresult
UPDATE refresh_job_runs
SET status = ?1, finished_at = CURRENT_TIMESTAMP, error = ?2
WHERE refresh_job_runs.id = ?3
  AND refresh_job_runs.status IN ('queued', 'running', 'prepared')
  AND job_id IN (SELECT refresh_jobs.id FROM refresh_jobs WHERE workspace_id = ?4)
`

type MarkMaterializationRunTerminalParams struct {
	Status       string `json:"status"`
	ErrorMessage string `json:"error_message"`
	RunID        string `json:"run_id"`
	WorkspaceID  string `json:"workspace_id"`
}

func (q *Queries) MarkMaterializationRunTerminal(ctx context.Context, arg MarkMaterializationRunTerminalParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markMaterializationRunTerminal,
		arg.Status,
		arg.ErrorMessage,
		arg.RunID,
		arg.WorkspaceID,
	)
}

const markRefreshJobRunClaimed = `-- name: MarkRefreshJobRunClaimed :exec
UPDATE refresh_job_runs
SET status = ?1, started_at = CURRENT_TIMESTAMP, finished_at = NULL, error = ''
WHERE id = ?2
`

type MarkRefreshJobRunClaimedParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) MarkRefreshJobRunClaimed(ctx context.Context, arg MarkRefreshJobRunClaimedParams) error {
	_, err := q.db.ExecContext(ctx, markRefreshJobRunClaimed, arg.Status, arg.ID)
	return err
}

const markRefreshRunPrepared = `-- name: MarkRefreshRunPrepared :execrows
UPDATE refresh_job_runs
SET status = 'prepared', finished_at = NULL, error = ''
WHERE refresh_job_runs.id = ?1 AND refresh_job_runs.status = 'running'
  AND refresh_job_runs.job_id IN (
	SELECT refresh_jobs.id FROM refresh_jobs
    WHERE workspace_id = ?2 AND status = 'running'
      AND lease_owner = ?3 AND lease_generation = ?4
  )
`

type MarkRefreshRunPreparedParams struct {
	RunID           string `json:"run_id"`
	WorkspaceID     string `json:"workspace_id"`
	LeaseOwner      string `json:"lease_owner"`
	LeaseGeneration int64  `json:"lease_generation"`
}

func (q *Queries) MarkRefreshRunPrepared(ctx context.Context, arg MarkRefreshRunPreparedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markRefreshRunPrepared,
		arg.RunID,
		arg.WorkspaceID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markRefreshRunSuperseded = `-- name: MarkRefreshRunSuperseded :execrows
UPDATE refresh_job_runs
SET status = 'superseded', finished_at = CURRENT_TIMESTAMP, error = 'superseded by a newer target generation'
WHERE refresh_job_runs.id = ?1
  AND refresh_job_runs.job_id IN (SELECT refresh_jobs.id FROM refresh_jobs WHERE workspace_id = ?2)
  AND refresh_job_runs.status IN ('running', 'prepared')
`

type MarkRefreshRunSupersededParams struct {
	RunID       string `json:"run_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) MarkRefreshRunSuperseded(ctx context.Context, arg MarkRefreshRunSupersededParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markRefreshRunSuperseded, arg.RunID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const nextExecutableRefreshJob = `-- name: NextExecutableRefreshJob :one
SELECT j.id, j.workspace_id, r.environment, COALESCE(j.serving_state_id, '') AS serving_state_id, j.model_id, j.kind, j.payload_json,
       r.id AS run_id, r.target_type, r.target_id, r.target_generation, r.trigger_type, j.attempt_count, j.lease_owner, j.lease_generation
FROM refresh_jobs j
JOIN refresh_job_runs r ON r.job_id = j.id
WHERE COALESCE(r.parent_run_id, '') = ''
  AND j.kind = ?1
  AND r.environment = ?2
  AND (
    (j.status = ?3 AND r.status = ?4)
    OR (j.status = ?5 AND (j.lease_expires_at IS NULL OR j.lease_expires_at <= CURRENT_TIMESTAMP))
  )
ORDER BY COALESCE(NULLIF(j.queued_at, ''), j.created_at) ASC, j.id ASC
LIMIT 1
`

type NextExecutableRefreshJobParams struct {
	RefreshPipelineKind string `json:"refresh_pipeline_kind"`
	Environment         string `json:"environment"`
	QueuedStatus        string `json:"queued_status"`
	RunQueuedStatus     string `json:"run_queued_status"`
	RunningStatus       string `json:"running_status"`
}

type NextExecutableRefreshJobRow struct {
	ID               string `json:"id"`
	WorkspaceID      string `json:"workspace_id"`
	Environment      string `json:"environment"`
	ServingStateID   string `json:"serving_state_id"`
	ModelID          string `json:"model_id"`
	Kind             string `json:"kind"`
	PayloadJson      string `json:"payload_json"`
	RunID            string `json:"run_id"`
	TargetType       string `json:"target_type"`
	TargetID         string `json:"target_id"`
	TargetGeneration int64  `json:"target_generation"`
	TriggerType      string `json:"trigger_type"`
	AttemptCount     int64  `json:"attempt_count"`
	LeaseOwner       string `json:"lease_owner"`
	LeaseGeneration  int64  `json:"lease_generation"`
}

func (q *Queries) NextExecutableRefreshJob(ctx context.Context, arg NextExecutableRefreshJobParams) (NextExecutableRefreshJobRow, error) {
	row := q.db.QueryRowContext(ctx, nextExecutableRefreshJob,
		arg.RefreshPipelineKind,
		arg.Environment,
		arg.QueuedStatus,
		arg.RunQueuedStatus,
		arg.RunningStatus,
	)
	var i NextExecutableRefreshJobRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Environment,
		&i.ServingStateID,
		&i.ModelID,
		&i.Kind,
		&i.PayloadJson,
		&i.RunID,
		&i.TargetType,
		&i.TargetID,
		&i.TargetGeneration,
		&i.TriggerType,
		&i.AttemptCount,
		&i.LeaseOwner,
		&i.LeaseGeneration,
	)
	return i, err
}

const refreshRunMayPublish = `-- name: RefreshRunMayPublish :one
SELECT EXISTS(
  SELECT 1
  FROM refresh_job_runs candidate
  JOIN refresh_jobs candidate_job ON candidate_job.id = candidate.job_id
  WHERE candidate.id = ?1
    AND candidate_job.workspace_id = ?2
    AND candidate.status = 'prepared'
    AND candidate.target_generation = ?3
    AND candidate_job.status = 'running'
    AND candidate_job.lease_owner = ?4
    AND candidate_job.lease_generation = ?5
    AND NOT EXISTS (
      SELECT 1
      FROM refresh_job_runs newer
      JOIN refresh_jobs newer_job ON newer_job.id = newer.job_id
      WHERE newer_job.workspace_id = candidate_job.workspace_id
        AND newer.environment = candidate.environment
        AND newer.target_type = candidate.target_type
        AND newer.target_id = candidate.target_id
        AND newer.target_generation > candidate.target_generation
    )
) AS may_publish
`

type RefreshRunMayPublishParams struct {
	RunID            string `json:"run_id"`
	WorkspaceID      string `json:"workspace_id"`
	TargetGeneration int64  `json:"target_generation"`
	LeaseOwner       string `json:"lease_owner"`
	LeaseGeneration  int64  `json:"lease_generation"`
}

func (q *Queries) RefreshRunMayPublish(ctx context.Context, arg RefreshRunMayPublishParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, refreshRunMayPublish,
		arg.RunID,
		arg.WorkspaceID,
		arg.TargetGeneration,
		arg.LeaseOwner,
		arg.LeaseGeneration,
	)
	var may_publish int64
	err := row.Scan(&may_publish)
	return may_publish, err
}

const renewRefreshJobLease = `-- name: RenewRefreshJobLease :execrows
UPDATE refresh_jobs
SET lease_expires_at = datetime('now', CAST(?1 AS TEXT)), updated_at = CURRENT_TIMESTAMP
WHERE id = ?2 AND lease_owner = ?3
  AND lease_generation = ?4 AND status = ?5
`

type RenewRefreshJobLeaseParams struct {
	LeaseModifier   string `json:"lease_modifier"`
	ID              string `json:"id"`
	LeaseOwner      string `json:"lease_owner"`
	LeaseGeneration int64  `json:"lease_generation"`
	Status          string `json:"status"`
}

func (q *Queries) RenewRefreshJobLease(ctx context.Context, arg RenewRefreshJobLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewRefreshJobLease,
		arg.LeaseModifier,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const supersedeRefreshTargetJobs = `-- name: SupersedeRefreshTargetJobs :exec
UPDATE refresh_jobs
SET status = 'superseded', finished_at = CURRENT_TIMESTAMP, lease_owner = '', lease_expires_at = NULL,
    updated_at = CURRENT_TIMESTAMP, last_error = 'superseded by a newer target generation'
WHERE id IN (
  SELECT candidate.job_id
  FROM refresh_job_runs candidate
  JOIN refresh_jobs candidate_job ON candidate_job.id = candidate.job_id
  WHERE candidate_job.workspace_id = ?1
    AND candidate.environment = ?2
    AND candidate.status IN ('queued', 'running', 'prepared')
    AND (
      (candidate.parent_run_id IS NULL AND candidate.target_type = ?3 AND candidate.target_id = ?4)
      OR candidate.parent_run_id IN (
        SELECT root.id FROM refresh_job_runs root
        JOIN refresh_jobs root_job ON root_job.id = root.job_id
        WHERE root_job.workspace_id = ?1
          AND root.environment = ?2
          AND root.parent_run_id IS NULL
          AND root.target_type = ?3
          AND root.target_id = ?4
          AND root.status IN ('queued', 'running', 'prepared')
      )
    )
)
`

type SupersedeRefreshTargetJobsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
	TargetType  string `json:"target_type"`
	TargetID    string `json:"target_id"`
}

func (q *Queries) SupersedeRefreshTargetJobs(ctx context.Context, arg SupersedeRefreshTargetJobsParams) error {
	_, err := q.db.ExecContext(ctx, supersedeRefreshTargetJobs,
		arg.WorkspaceID,
		arg.Environment,
		arg.TargetType,
		arg.TargetID,
	)
	return err
}

const supersedeRefreshTargetRuns = `-- name: SupersedeRefreshTargetRuns :exec
UPDATE refresh_job_runs
SET status = 'superseded', finished_at = CURRENT_TIMESTAMP, error = 'superseded by a newer target generation'
WHERE id IN (
  SELECT candidate.id
  FROM refresh_job_runs candidate
  JOIN refresh_jobs candidate_job ON candidate_job.id = candidate.job_id
  WHERE candidate_job.workspace_id = ?1
    AND candidate.environment = ?2
    AND candidate.status IN ('queued', 'running', 'prepared')
    AND (
      (candidate.parent_run_id IS NULL AND candidate.target_type = ?3 AND candidate.target_id = ?4)
      OR candidate.parent_run_id IN (
        SELECT root.id FROM refresh_job_runs root
        JOIN refresh_jobs root_job ON root_job.id = root.job_id
        WHERE root_job.workspace_id = ?1
          AND root.environment = ?2
          AND root.parent_run_id IS NULL
          AND root.target_type = ?3
          AND root.target_id = ?4
          AND root.status IN ('queued', 'running', 'prepared')
      )
    )
)
`

type SupersedeRefreshTargetRunsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
	TargetType  string `json:"target_type"`
	TargetID    string `json:"target_id"`
}

func (q *Queries) SupersedeRefreshTargetRuns(ctx context.Context, arg SupersedeRefreshTargetRunsParams) error {
	_, err := q.db.ExecContext(ctx, supersedeRefreshTargetRuns,
		arg.WorkspaceID,
		arg.Environment,
		arg.TargetType,
		arg.TargetID,
	)
	return err
}

const updateRefreshJobForActiveRun = `-- name: UpdateRefreshJobForActiveRun :exec
UPDATE refresh_jobs
SET status = ?1, updated_at = CURRENT_TIMESTAMP
WHERE refresh_jobs.id = (SELECT job_id FROM refresh_job_runs WHERE refresh_job_runs.id = ?2)
  AND workspace_id = ?3
`

type UpdateRefreshJobForActiveRunParams struct {
	NewStatus   string `json:"new_status"`
	RunID       string `json:"run_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) UpdateRefreshJobForActiveRun(ctx context.Context, arg UpdateRefreshJobForActiveRunParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshJobForActiveRun, arg.NewStatus, arg.RunID, arg.WorkspaceID)
	return err
}
