// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_pipeline.sql

package materializedb

import (
	"context"
	"database/sql"
)

const advanceRefreshPipelineSchedule = `-- name: AdvanceRefreshPipelineSchedule :exec
UPDATE refresh_pipeline_schedules SET next_run_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE workspace_id = ? AND environment = ? AND pipeline_id = ? AND cron = ? AND timezone = ?
`

type AdvanceRefreshPipelineScheduleParams struct {
	NextRunAt   string `json:"next_run_at"`
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
	PipelineID  string `json:"pipeline_id"`
	Cron        string `json:"cron"`
	Timezone    string `json:"timezone"`
}

func (q *Queries) AdvanceRefreshPipelineSchedule(ctx context.Context, arg AdvanceRefreshPipelineScheduleParams) error {
	_, err := q.db.ExecContext(ctx, advanceRefreshPipelineSchedule,
		arg.NextRunAt,
		arg.WorkspaceID,
		arg.Environment,
		arg.PipelineID,
		arg.Cron,
		arg.Timezone,
	)
	return err
}

const attachRefreshPipelineRun = `-- name: AttachRefreshPipelineRun :execresult
UPDATE refresh_pipeline_occurrences SET run_id = ?
WHERE workspace_id = ? AND environment = ? AND pipeline_id = ? AND scheduled_at = ?
`

type AttachRefreshPipelineRunParams struct {
	RunID       sql.NullString `json:"run_id"`
	WorkspaceID string         `json:"workspace_id"`
	Environment string         `json:"environment"`
	PipelineID  string         `json:"pipeline_id"`
	ScheduledAt string         `json:"scheduled_at"`
}

func (q *Queries) AttachRefreshPipelineRun(ctx context.Context, arg AttachRefreshPipelineRunParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, attachRefreshPipelineRun,
		arg.RunID,
		arg.WorkspaceID,
		arg.Environment,
		arg.PipelineID,
		arg.ScheduledAt,
	)
}

const claimRefreshPipelineOccurrence = `-- name: ClaimRefreshPipelineOccurrence :execresult
INSERT OR IGNORE INTO refresh_pipeline_occurrences (
  workspace_id, environment, pipeline_id, artifact_digest, scheduled_at, claimed_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type ClaimRefreshPipelineOccurrenceParams struct {
	WorkspaceID    string `json:"workspace_id"`
	Environment    string `json:"environment"`
	PipelineID     string `json:"pipeline_id"`
	ArtifactDigest string `json:"artifact_digest"`
	ScheduledAt    string `json:"scheduled_at"`
	ClaimedAt      string `json:"claimed_at"`
}

func (q *Queries) ClaimRefreshPipelineOccurrence(ctx context.Context, arg ClaimRefreshPipelineOccurrenceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, claimRefreshPipelineOccurrence,
		arg.WorkspaceID,
		arg.Environment,
		arg.PipelineID,
		arg.ArtifactDigest,
		arg.ScheduledAt,
		arg.ClaimedAt,
	)
}

const createRefreshPipelineSchedule = `-- name: CreateRefreshPipelineSchedule :exec
INSERT INTO refresh_pipeline_schedules (
  workspace_id, environment, pipeline_id, semantic_model_id, artifact_digest, cron, timezone, next_run_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
`

type CreateRefreshPipelineScheduleParams struct {
	WorkspaceID     string `json:"workspace_id"`
	Environment     string `json:"environment"`
	PipelineID      string `json:"pipeline_id"`
	SemanticModelID string `json:"semantic_model_id"`
	ArtifactDigest  string `json:"artifact_digest"`
	Cron            string `json:"cron"`
	Timezone        string `json:"timezone"`
	NextRunAt       string `json:"next_run_at"`
}

func (q *Queries) CreateRefreshPipelineSchedule(ctx context.Context, arg CreateRefreshPipelineScheduleParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshPipelineSchedule,
		arg.WorkspaceID,
		arg.Environment,
		arg.PipelineID,
		arg.SemanticModelID,
		arg.ArtifactDigest,
		arg.Cron,
		arg.Timezone,
		arg.NextRunAt,
	)
	return err
}

const deleteAbandonedRefreshPipelineOccurrences = `-- name: DeleteAbandonedRefreshPipelineOccurrences :exec
DELETE FROM refresh_pipeline_occurrences
WHERE environment = ?1 AND run_id IS NULL AND claimed_at <= ?2
`

type DeleteAbandonedRefreshPipelineOccurrencesParams struct {
	Environment   string `json:"environment"`
	ClaimedBefore string `json:"claimed_before"`
}

func (q *Queries) DeleteAbandonedRefreshPipelineOccurrences(ctx context.Context, arg DeleteAbandonedRefreshPipelineOccurrencesParams) error {
	_, err := q.db.ExecContext(ctx, deleteAbandonedRefreshPipelineOccurrences, arg.Environment, arg.ClaimedBefore)
	return err
}

const deleteRefreshPipelineSchedules = `-- name: DeleteRefreshPipelineSchedules :exec
DELETE FROM refresh_pipeline_schedules
WHERE workspace_id = ? AND environment = ?
`

type DeleteRefreshPipelineSchedulesParams struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
}

func (q *Queries) DeleteRefreshPipelineSchedules(ctx context.Context, arg DeleteRefreshPipelineSchedulesParams) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshPipelineSchedules, arg.WorkspaceID, arg.Environment)
	return err
}

const deleteUnattachedRefreshPipelineOccurrence = `-- name: DeleteUnattachedRefreshPipelineOccurrence :execresult
DELETE FROM refresh_pipeline_occurrences
WHERE workspace_id = ? AND environment = ? AND pipeline_id = ? AND scheduled_at = ? AND run_id IS NULL
`

type DeleteUnattachedRefreshPipelineOccurrenceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
	PipelineID  string `json:"pipeline_id"`
	ScheduledAt string `json:"scheduled_at"`
}

func (q *Queries) DeleteUnattachedRefreshPipelineOccurrence(ctx context.Context, arg DeleteUnattachedRefreshPipelineOccurrenceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUnattachedRefreshPipelineOccurrence,
		arg.WorkspaceID,
		arg.Environment,
		arg.PipelineID,
		arg.ScheduledAt,
	)
}

const getRefreshPipelineNextRun = `-- name: GetRefreshPipelineNextRun :one
SELECT next_run_at
FROM refresh_pipeline_schedules
WHERE workspace_id = ? AND environment = ? AND pipeline_id = ?
ORDER BY next_run_at
LIMIT 1
`

type GetRefreshPipelineNextRunParams struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
	PipelineID  string `json:"pipeline_id"`
}

func (q *Queries) GetRefreshPipelineNextRun(ctx context.Context, arg GetRefreshPipelineNextRunParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getRefreshPipelineNextRun, arg.WorkspaceID, arg.Environment, arg.PipelineID)
	var next_run_at string
	err := row.Scan(&next_run_at)
	return next_run_at, err
}

const getSemanticModelDataVersion = `-- name: GetSemanticModelDataVersion :one
SELECT workspace_id, environment, semantic_model_id, snapshot_id, serving_state_id, refreshed_at, source,
       COALESCE(pipeline_id, '') AS pipeline_id, COALESCE(run_id, '') AS run_id
FROM semantic_model_data_versions
WHERE workspace_id = ? AND environment = ? AND semantic_model_id = ?
`

type GetSemanticModelDataVersionParams struct {
	WorkspaceID     string `json:"workspace_id"`
	Environment     string `json:"environment"`
	SemanticModelID string `json:"semantic_model_id"`
}

type GetSemanticModelDataVersionRow struct {
	WorkspaceID     string `json:"workspace_id"`
	Environment     string `json:"environment"`
	SemanticModelID string `json:"semantic_model_id"`
	SnapshotID      int64  `json:"snapshot_id"`
	ServingStateID  string `json:"serving_state_id"`
	RefreshedAt     string `json:"refreshed_at"`
	Source          string `json:"source"`
	PipelineID      string `json:"pipeline_id"`
	RunID           string `json:"run_id"`
}

func (q *Queries) GetSemanticModelDataVersion(ctx context.Context, arg GetSemanticModelDataVersionParams) (GetSemanticModelDataVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getSemanticModelDataVersion, arg.WorkspaceID, arg.Environment, arg.SemanticModelID)
	var i GetSemanticModelDataVersionRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.Environment,
		&i.SemanticModelID,
		&i.SnapshotID,
		&i.ServingStateID,
		&i.RefreshedAt,
		&i.Source,
		&i.PipelineID,
		&i.RunID,
	)
	return i, err
}

const listDueRefreshPipelineSchedules = `-- name: ListDueRefreshPipelineSchedules :many
SELECT workspace_id, environment, pipeline_id, semantic_model_id, cron, timezone, artifact_digest, next_run_at
FROM refresh_pipeline_schedules
WHERE environment = ?1 AND next_run_at <= ?2
ORDER BY workspace_id, environment, pipeline_id, next_run_at
`

type ListDueRefreshPipelineSchedulesParams struct {
	Environment string `json:"environment"`
	NextRunAt   string `json:"next_run_at"`
}

type ListDueRefreshPipelineSchedulesRow struct {
	WorkspaceID     string `json:"workspace_id"`
	Environment     string `json:"environment"`
	PipelineID      string `json:"pipeline_id"`
	SemanticModelID string `json:"semantic_model_id"`
	Cron            string `json:"cron"`
	Timezone        string `json:"timezone"`
	ArtifactDigest  string `json:"artifact_digest"`
	NextRunAt       string `json:"next_run_at"`
}

func (q *Queries) ListDueRefreshPipelineSchedules(ctx context.Context, arg ListDueRefreshPipelineSchedulesParams) ([]ListDueRefreshPipelineSchedulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDueRefreshPipelineSchedules, arg.Environment, arg.NextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueRefreshPipelineSchedulesRow{}
	for rows.Next() {
		var i ListDueRefreshPipelineSchedulesRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Environment,
			&i.PipelineID,
			&i.SemanticModelID,
			&i.Cron,
			&i.Timezone,
			&i.ArtifactDigest,
			&i.NextRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefreshPipelineSchedules = `-- name: ListRefreshPipelineSchedules :many
SELECT pipeline_id, cron, timezone, artifact_digest, next_run_at
FROM refresh_pipeline_schedules
WHERE workspace_id = ? AND environment = ?
`

type ListRefreshPipelineSchedulesParams struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
}

type ListRefreshPipelineSchedulesRow struct {
	PipelineID     string `json:"pipeline_id"`
	Cron           string `json:"cron"`
	Timezone       string `json:"timezone"`
	ArtifactDigest string `json:"artifact_digest"`
	NextRunAt      string `json:"next_run_at"`
}

func (q *Queries) ListRefreshPipelineSchedules(ctx context.Context, arg ListRefreshPipelineSchedulesParams) ([]ListRefreshPipelineSchedulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRefreshPipelineSchedules, arg.WorkspaceID, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRefreshPipelineSchedulesRow{}
	for rows.Next() {
		var i ListRefreshPipelineSchedulesRow
		if err := rows.Scan(
			&i.PipelineID,
			&i.Cron,
			&i.Timezone,
			&i.ArtifactDigest,
			&i.NextRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueAbandonedRefreshPipelineSchedules = `-- name: RequeueAbandonedRefreshPipelineSchedules :exec
UPDATE refresh_pipeline_schedules
SET next_run_at = (
  SELECT MIN(occurrence.scheduled_at)
  FROM refresh_pipeline_occurrences occurrence
  WHERE occurrence.workspace_id = refresh_pipeline_schedules.workspace_id
    AND occurrence.environment = refresh_pipeline_schedules.environment
    AND occurrence.pipeline_id = refresh_pipeline_schedules.pipeline_id
    AND occurrence.artifact_digest = refresh_pipeline_schedules.artifact_digest
    AND occurrence.run_id IS NULL
    AND occurrence.claimed_at <= ?1
), updated_at = CURRENT_TIMESTAMP
WHERE refresh_pipeline_schedules.environment = ?2
  AND EXISTS (
  SELECT 1
  FROM refresh_pipeline_occurrences occurrence
  WHERE occurrence.workspace_id = refresh_pipeline_schedules.workspace_id
    AND occurrence.environment = refresh_pipeline_schedules.environment
    AND occurrence.pipeline_id = refresh_pipeline_schedules.pipeline_id
    AND occurrence.artifact_digest = refresh_pipeline_schedules.artifact_digest
    AND occurrence.run_id IS NULL
    AND occurrence.claimed_at <= ?1
)
`

type RequeueAbandonedRefreshPipelineSchedulesParams struct {
	ClaimedBefore string `json:"claimed_before"`
	Environment   string `json:"environment"`
}

func (q *Queries) RequeueAbandonedRefreshPipelineSchedules(ctx context.Context, arg RequeueAbandonedRefreshPipelineSchedulesParams) error {
	_, err := q.db.ExecContext(ctx, requeueAbandonedRefreshPipelineSchedules, arg.ClaimedBefore, arg.Environment)
	return err
}

const retryRefreshPipelineSchedules = `-- name: RetryRefreshPipelineSchedules :exec
UPDATE refresh_pipeline_schedules SET next_run_at = ?1, updated_at = CURRENT_TIMESTAMP
WHERE workspace_id = ?2 AND environment = ?3
  AND pipeline_id = ?4 AND artifact_digest = ?5
  AND next_run_at > ?1
`

type RetryRefreshPipelineSchedulesParams struct {
	RetryAt        string `json:"retry_at"`
	WorkspaceID    string `json:"workspace_id"`
	Environment    string `json:"environment"`
	PipelineID     string `json:"pipeline_id"`
	ArtifactDigest string `json:"artifact_digest"`
}

func (q *Queries) RetryRefreshPipelineSchedules(ctx context.Context, arg RetryRefreshPipelineSchedulesParams) error {
	_, err := q.db.ExecContext(ctx, retryRefreshPipelineSchedules,
		arg.RetryAt,
		arg.WorkspaceID,
		arg.Environment,
		arg.PipelineID,
		arg.ArtifactDigest,
	)
	return err
}

const upsertSemanticModelDataVersion = `-- name: UpsertSemanticModelDataVersion :exec
INSERT INTO semantic_model_data_versions (
  workspace_id, environment, semantic_model_id, snapshot_id, serving_state_id, refreshed_at, source, pipeline_id, run_id
) VALUES (?, ?, ?, ?, ?, ?, ?, NULLIF(?8, ''), NULLIF(?9, ''))
ON CONFLICT (workspace_id, environment, semantic_model_id) DO UPDATE SET
  snapshot_id = excluded.snapshot_id,
  serving_state_id = excluded.serving_state_id,
  refreshed_at = excluded.refreshed_at,
  source = excluded.source,
  pipeline_id = excluded.pipeline_id,
  run_id = excluded.run_id
`

type UpsertSemanticModelDataVersionParams struct {
	WorkspaceID     string      `json:"workspace_id"`
	Environment     string      `json:"environment"`
	SemanticModelID string      `json:"semantic_model_id"`
	SnapshotID      int64       `json:"snapshot_id"`
	ServingStateID  string      `json:"serving_state_id"`
	RefreshedAt     string      `json:"refreshed_at"`
	Source          string      `json:"source"`
	PipelineID      interface{} `json:"pipeline_id"`
	RunID           interface{} `json:"run_id"`
}

func (q *Queries) UpsertSemanticModelDataVersion(ctx context.Context, arg UpsertSemanticModelDataVersionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSemanticModelDataVersion,
		arg.WorkspaceID,
		arg.Environment,
		arg.SemanticModelID,
		arg.SnapshotID,
		arg.ServingStateID,
		arg.RefreshedAt,
		arg.Source,
		arg.PipelineID,
		arg.RunID,
	)
	return err
}
