// Code generated by apigen data-contract Go emitter. DO NOT EDIT.
package ir

import (
	"bytes"
	"encoding/json"
	"fmt"
)

type CartesianVisualizationPresentation struct {
	VisualizationPresentation
	Smooth        bool                        `json:"smooth"`
	Stacked       bool                        `json:"stacked"`
	ShowSymbols   bool                        `json:"showSymbols"`
	DataZoom      bool                        `json:"dataZoom"`
	Area          bool                        `json:"area"`
	Step          bool                        `json:"step"`
	Orientation   *VisualizationOrientation   `json:"orientation,omitempty"`
	LabelPosition *VisualizationLabelPosition `json:"labelPosition,omitempty"`
	SymbolSize    *float64                    `json:"symbolSize,omitempty"`
	HistogramBins *int32                      `json:"histogramBins,omitempty"`
	ComboSeries   *[]VisualizationComboSeries `json:"comboSeries,omitempty"`
}

type CartesianVisualizationSpec struct {
	VisualizationSpecBase
	Kind         string                             `json:"kind"`
	Mark         VisualizationCartesianMark         `json:"mark"`
	X            VisualizationFieldRef              `json:"x"`
	Y            []VisualizationFieldRef            `json:"y"`
	Series       *VisualizationFieldRef             `json:"series,omitempty"`
	Presentation CartesianVisualizationPresentation `json:"presentation"`
}

type CompactVisualizationFormat struct {
	VisualizationFormatBase
	Kind                  string `json:"kind"`
	MaximumFractionDigits *int32 `json:"maximumFractionDigits,omitempty"`
}

type CurrencyVisualizationFormat struct {
	VisualizationFormatBase
	Kind                  string `json:"kind"`
	Currency              string `json:"currency"`
	MinimumFractionDigits *int32 `json:"minimumFractionDigits,omitempty"`
	MaximumFractionDigits *int32 `json:"maximumFractionDigits,omitempty"`
}

type CustomVisualizationSpec struct {
	VisualizationSpecBase
	Kind          string                    `json:"kind"`
	Engine        VisualizationCustomEngine `json:"engine"`
	Program       string                    `json:"program"`
	ProgramDigest string                    `json:"programDigest"`
}

type DurationVisualizationFormat struct {
	VisualizationFormatBase
	Kind string `json:"kind"`
	Unit string `json:"unit"`
}

type GeographicVisualizationPresentation struct {
	VisualizationPresentation
	Roam        bool `json:"roam"`
	ShowBasemap bool `json:"showBasemap"`
}

type GeographicVisualizationSpec struct {
	VisualizationSpecBase
	Kind         string                              `json:"kind"`
	Layers       []VisualizationGeographicLayer      `json:"layers"`
	Presentation GeographicVisualizationPresentation `json:"presentation"`
}

type GridVisualizationPresentation struct {
	RowHeight  int64 `json:"rowHeight"`
	Striped    bool  `json:"striped"`
	ShowHeader bool  `json:"showHeader"`
}

type HierarchyVisualizationPresentation struct {
	VisualizationPresentation
	Orientation  VisualizationOrientation      `json:"orientation"`
	InitialDepth *int32                        `json:"initialDepth,omitempty"`
	Roam         bool                          `json:"roam"`
	Layout       *VisualizationHierarchyLayout `json:"layout,omitempty"`
	Breadcrumb   *bool                         `json:"breadcrumb,omitempty"`
	NodeGap      *float64                      `json:"nodeGap,omitempty"`
	Curveness    *float64                      `json:"curveness,omitempty"`
	Focus        *VisualizationGraphFocus      `json:"focus,omitempty"`
}

type HierarchyVisualizationSpec struct {
	VisualizationSpecBase
	Kind         string                             `json:"kind"`
	Mark         VisualizationHierarchyMark         `json:"mark"`
	Node         VisualizationFieldRef              `json:"node"`
	Parent       *VisualizationFieldRef             `json:"parent,omitempty"`
	Source       *VisualizationFieldRef             `json:"source,omitempty"`
	Target       *VisualizationFieldRef             `json:"target,omitempty"`
	Value        *VisualizationFieldRef             `json:"value,omitempty"`
	Presentation HierarchyVisualizationPresentation `json:"presentation"`
}

type InlineVisualizationDataState struct {
	VisualizationDataStateBase
	Kind     string                       `json:"kind"`
	Datasets []VisualizationInlineDataset `json:"datasets"`
}

type KPIVisualizationPresentation struct {
	Trend      VisualizationKPITrend     `json:"trend"`
	Note       *string                   `json:"note,omitempty"`
	Tone       *VisualizationTone        `json:"tone,omitempty"`
	Thresholds *[]VisualizationThreshold `json:"thresholds,omitempty"`
}

type KPIVisualizationSpec struct {
	VisualizationSpecBase
	Kind         string                       `json:"kind"`
	Value        VisualizationFieldRef        `json:"value"`
	Comparison   *VisualizationFieldRef       `json:"comparison,omitempty"`
	Trend        *VisualizationFieldRef       `json:"trend,omitempty"`
	Presentation KPIVisualizationPresentation `json:"presentation"`
}

type MatrixVisualizationSpec struct {
	VisualizationSpecBase
	Kind              string                                        `json:"kind"`
	Rows              []VisualizationFieldRef                       `json:"rows"`
	Columns           []VisualizationFieldRef                       `json:"columns"`
	Measures          []VisualizationFieldRef                       `json:"measures"`
	MeasureFormatting map[string][]TableVisualizationFormattingRule `json:"measureFormatting"`
	Presentation      GridVisualizationPresentation                 `json:"presentation"`
}

type NumberVisualizationFormat struct {
	VisualizationFormatBase
	Kind                  string `json:"kind"`
	MinimumFractionDigits *int32 `json:"minimumFractionDigits,omitempty"`
	MaximumFractionDigits *int32 `json:"maximumFractionDigits,omitempty"`
}

type PercentVisualizationFormat struct {
	VisualizationFormatBase
	Kind                  string `json:"kind"`
	MinimumFractionDigits *int32 `json:"minimumFractionDigits,omitempty"`
	MaximumFractionDigits *int32 `json:"maximumFractionDigits,omitempty"`
}

type PivotVisualizationSpec struct {
	VisualizationSpecBase
	Kind              string                                        `json:"kind"`
	Rows              []VisualizationFieldRef                       `json:"rows"`
	Columns           []VisualizationFieldRef                       `json:"columns"`
	Measures          []VisualizationFieldRef                       `json:"measures"`
	MeasureFormatting map[string][]TableVisualizationFormattingRule `json:"measureFormatting"`
	Presentation      GridVisualizationPresentation                 `json:"presentation"`
}

type PolarVisualizationPresentation struct {
	VisualizationPresentation
	Minimum       *float64                  `json:"minimum,omitempty"`
	Maximum       *float64                  `json:"maximum,omitempty"`
	ShowPointer   bool                      `json:"showPointer"`
	Area          *bool                     `json:"area,omitempty"`
	ProgressWidth *float64                  `json:"progressWidth,omitempty"`
	Thresholds    *[]VisualizationThreshold `json:"thresholds,omitempty"`
}

type PolarVisualizationSpec struct {
	VisualizationSpecBase
	Kind         string                         `json:"kind"`
	Mark         VisualizationPolarMark         `json:"mark"`
	Category     *VisualizationFieldRef         `json:"category,omitempty"`
	Value        VisualizationFieldRef          `json:"value"`
	Series       *VisualizationFieldRef         `json:"series,omitempty"`
	Presentation PolarVisualizationPresentation `json:"presentation"`
}

type ProportionalVisualizationPresentation struct {
	VisualizationPresentation
	Orientation   VisualizationOrientation    `json:"orientation"`
	Rose          bool                        `json:"rose"`
	CenterLabel   *string                     `json:"centerLabel,omitempty"`
	LabelPosition *VisualizationLabelPosition `json:"labelPosition,omitempty"`
	InnerRadius   *float64                    `json:"innerRadius,omitempty"`
	OuterRadius   *float64                    `json:"outerRadius,omitempty"`
	Align         *string                     `json:"align,omitempty"`
	Sort          *VisualizationSortDirection `json:"sort,omitempty"`
}

type ProportionalVisualizationSpec struct {
	VisualizationSpecBase
	Kind         string                                `json:"kind"`
	Mark         VisualizationProportionalMark         `json:"mark"`
	Category     VisualizationFieldRef                 `json:"category"`
	Value        VisualizationFieldRef                 `json:"value"`
	Series       *VisualizationFieldRef                `json:"series,omitempty"`
	Presentation ProportionalVisualizationPresentation `json:"presentation"`
}

type TableBackgroundScaleFormattingRule struct {
	TableVisualizationFormattingRuleBase
	Kind      string   `json:"kind"`
	Minimum   *float64 `json:"minimum,omitempty"`
	Maximum   *float64 `json:"maximum,omitempty"`
	LowColor  *string  `json:"lowColor,omitempty"`
	HighColor *string  `json:"highColor,omitempty"`
}

type TableBadgeFormattingRule struct {
	TableVisualizationFormattingRuleBase
	Kind   string            `json:"kind"`
	Values map[string]string `json:"values"`
}

type TableDataBarFormattingRule struct {
	TableVisualizationFormattingRuleBase
	Kind       string   `json:"kind"`
	Minimum    *float64 `json:"minimum,omitempty"`
	Maximum    *float64 `json:"maximum,omitempty"`
	Color      string   `json:"color"`
	Background *string  `json:"background,omitempty"`
}

type TableTextColorFormattingRule struct {
	TableVisualizationFormattingRuleBase
	Kind    string             `json:"kind"`
	Color   string             `json:"color"`
	Values  *map[string]string `json:"values,omitempty"`
	Minimum *float64           `json:"minimum,omitempty"`
	Maximum *float64           `json:"maximum,omitempty"`
}

type TableVisualizationColumn struct {
	Field       VisualizationFieldRef              `json:"field"`
	Label       string                             `json:"label"`
	Width       *int64                             `json:"width,omitempty"`
	Group       *string                            `json:"group,omitempty"`
	Measure     *string                            `json:"measure,omitempty"`
	ColumnValue *string                            `json:"columnValue,omitempty"`
	Formatting  []TableVisualizationFormattingRule `json:"formatting"`
}

type TableVisualizationFormattingRuleVariant interface {
	isTableVisualizationFormattingRuleVariant()
}

type TableVisualizationFormattingRule struct {
	Value TableVisualizationFormattingRuleVariant
}

func (TableBackgroundScaleFormattingRule) isTableVisualizationFormattingRuleVariant() {}
func (TableBadgeFormattingRule) isTableVisualizationFormattingRuleVariant()           {}
func (TableDataBarFormattingRule) isTableVisualizationFormattingRuleVariant()         {}
func (TableTextColorFormattingRule) isTableVisualizationFormattingRuleVariant()       {}

func (value TableVisualizationFormattingRule) MarshalJSON() ([]byte, error) {
	switch variant := value.Value.(type) {
	case TableBackgroundScaleFormattingRule:
		return json.Marshal(variant)
	case *TableBackgroundScaleFormattingRule:
		if variant == nil {
			return nil, fmt.Errorf("TableVisualizationFormattingRule variant is nil")
		}
		return json.Marshal(variant)
	case TableBadgeFormattingRule:
		return json.Marshal(variant)
	case *TableBadgeFormattingRule:
		if variant == nil {
			return nil, fmt.Errorf("TableVisualizationFormattingRule variant is nil")
		}
		return json.Marshal(variant)
	case TableDataBarFormattingRule:
		return json.Marshal(variant)
	case *TableDataBarFormattingRule:
		if variant == nil {
			return nil, fmt.Errorf("TableVisualizationFormattingRule variant is nil")
		}
		return json.Marshal(variant)
	case TableTextColorFormattingRule:
		return json.Marshal(variant)
	case *TableTextColorFormattingRule:
		if variant == nil {
			return nil, fmt.Errorf("TableVisualizationFormattingRule variant is nil")
		}
		return json.Marshal(variant)
	case nil:
		return nil, fmt.Errorf("TableVisualizationFormattingRule variant is required")
	default:
		return nil, fmt.Errorf("unsupported TableVisualizationFormattingRule variant %T", variant)
	}
}

func (value *TableVisualizationFormattingRule) UnmarshalJSON(data []byte) error {
	if value == nil {
		return fmt.Errorf("cannot unmarshal TableVisualizationFormattingRule into nil receiver")
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return fmt.Errorf("decode TableVisualizationFormattingRule object: %w", err)
	}
	var tag struct {
		Kind string `json:"kind"`
	}
	if err := json.Unmarshal(data, &tag); err != nil {
		return fmt.Errorf("decode TableVisualizationFormattingRule discriminator: %w", err)
	}
	if tag.Kind == "" {
		return fmt.Errorf("TableVisualizationFormattingRule discriminator kind is required")
	}
	decode := func(dest any) error {
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		return decoder.Decode(dest)
	}
	switch tag.Kind {
	case "background_scale":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode TableVisualizationFormattingRule variant %q: required property kind is missing", tag.Kind)
		}
		var variant TableBackgroundScaleFormattingRule
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode TableVisualizationFormattingRule variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "badge":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode TableVisualizationFormattingRule variant %q: required property kind is missing", tag.Kind)
		}
		if _, ok := fields["values"]; !ok {
			return fmt.Errorf("decode TableVisualizationFormattingRule variant %q: required property values is missing", tag.Kind)
		}
		var variant TableBadgeFormattingRule
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode TableVisualizationFormattingRule variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "data_bar":
		if _, ok := fields["color"]; !ok {
			return fmt.Errorf("decode TableVisualizationFormattingRule variant %q: required property color is missing", tag.Kind)
		}
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode TableVisualizationFormattingRule variant %q: required property kind is missing", tag.Kind)
		}
		var variant TableDataBarFormattingRule
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode TableVisualizationFormattingRule variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "text_color":
		if _, ok := fields["color"]; !ok {
			return fmt.Errorf("decode TableVisualizationFormattingRule variant %q: required property color is missing", tag.Kind)
		}
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode TableVisualizationFormattingRule variant %q: required property kind is missing", tag.Kind)
		}
		var variant TableTextColorFormattingRule
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode TableVisualizationFormattingRule variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	default:
		return fmt.Errorf("unknown TableVisualizationFormattingRule discriminator %q", tag.Kind)
	}
	return nil
}

type TableVisualizationFormattingRuleBase struct {
	Kind string `json:"kind"`
}

type TableVisualizationSpec struct {
	VisualizationSpecBase
	Kind         string                        `json:"kind"`
	Columns      []TableVisualizationColumn    `json:"columns"`
	DefaultSort  *[]VisualizationSort          `json:"defaultSort,omitempty"`
	Presentation GridVisualizationPresentation `json:"presentation"`
}

type TemporalVisualizationFormat struct {
	VisualizationFormatBase
	Kind      string  `json:"kind"`
	DateStyle *string `json:"dateStyle,omitempty"`
	TimeStyle *string `json:"timeStyle,omitempty"`
}

type VisualizationAccessibility struct {
	Title           string  `json:"title"`
	Description     string  `json:"description"`
	Summary         *string `json:"summary,omitempty"`
	AnnounceChanges *bool   `json:"announceChanges,omitempty"`
}

type VisualizationAxis string

const (
	VisualizationAxisPrimary   VisualizationAxis = "primary"
	VisualizationAxisSecondary VisualizationAxis = "secondary"
)

type VisualizationCardinality struct {
	Kind  VisualizationCardinalityKind `json:"kind"`
	Count *int64                       `json:"count,omitempty"`
}

type VisualizationCardinalityKind string

const (
	VisualizationCardinalityKindUnknown    VisualizationCardinalityKind = "unknown"
	VisualizationCardinalityKindLowerBound VisualizationCardinalityKind = "lower_bound"
	VisualizationCardinalityKindEstimated  VisualizationCardinalityKind = "estimated"
	VisualizationCardinalityKindExact      VisualizationCardinalityKind = "exact"
)

type VisualizationCartesianMark string

const (
	VisualizationCartesianMarkLine        VisualizationCartesianMark = "line"
	VisualizationCartesianMarkArea        VisualizationCartesianMark = "area"
	VisualizationCartesianMarkBar         VisualizationCartesianMark = "bar"
	VisualizationCartesianMarkColumn      VisualizationCartesianMark = "column"
	VisualizationCartesianMarkScatter     VisualizationCartesianMark = "scatter"
	VisualizationCartesianMarkHistogram   VisualizationCartesianMark = "histogram"
	VisualizationCartesianMarkCombo       VisualizationCartesianMark = "combo"
	VisualizationCartesianMarkWaterfall   VisualizationCartesianMark = "waterfall"
	VisualizationCartesianMarkCandlestick VisualizationCartesianMark = "candlestick"
	VisualizationCartesianMarkBoxplot     VisualizationCartesianMark = "boxplot"
	VisualizationCartesianMarkHeatmap     VisualizationCartesianMark = "heatmap"
)

type VisualizationComboSeries struct {
	SeriesValue string                     `json:"seriesValue"`
	Mark        VisualizationCartesianMark `json:"mark"`
	Axis        VisualizationAxis          `json:"axis"`
}

type VisualizationCompleteness string

const (
	VisualizationCompletenessComplete  VisualizationCompleteness = "complete"
	VisualizationCompletenessTruncated VisualizationCompleteness = "truncated"
	VisualizationCompletenessPartial   VisualizationCompleteness = "partial"
	VisualizationCompletenessEmpty     VisualizationCompleteness = "empty"
)

type VisualizationCustomEngine string

const (
	VisualizationCustomEngineVegaLite VisualizationCustomEngine = "vega_lite"
)

type VisualizationDataBudget struct {
	MaxRows              int64                     `json:"maxRows"`
	RequiredCompleteness VisualizationCompleteness `json:"requiredCompleteness"`
}

type VisualizationDataStateVariant interface {
	isVisualizationDataStateVariant()
}

type VisualizationDataState struct {
	Value VisualizationDataStateVariant
}

func (InlineVisualizationDataState) isVisualizationDataStateVariant()   {}
func (WindowedVisualizationDataState) isVisualizationDataStateVariant() {}

func (value VisualizationDataState) MarshalJSON() ([]byte, error) {
	switch variant := value.Value.(type) {
	case InlineVisualizationDataState:
		return json.Marshal(variant)
	case *InlineVisualizationDataState:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationDataState variant is nil")
		}
		return json.Marshal(variant)
	case WindowedVisualizationDataState:
		return json.Marshal(variant)
	case *WindowedVisualizationDataState:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationDataState variant is nil")
		}
		return json.Marshal(variant)
	case nil:
		return nil, fmt.Errorf("VisualizationDataState variant is required")
	default:
		return nil, fmt.Errorf("unsupported VisualizationDataState variant %T", variant)
	}
}

func (value *VisualizationDataState) UnmarshalJSON(data []byte) error {
	if value == nil {
		return fmt.Errorf("cannot unmarshal VisualizationDataState into nil receiver")
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return fmt.Errorf("decode VisualizationDataState object: %w", err)
	}
	var tag struct {
		Kind string `json:"kind"`
	}
	if err := json.Unmarshal(data, &tag); err != nil {
		return fmt.Errorf("decode VisualizationDataState discriminator: %w", err)
	}
	if tag.Kind == "" {
		return fmt.Errorf("VisualizationDataState discriminator kind is required")
	}
	decode := func(dest any) error {
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		return decoder.Decode(dest)
	}
	switch tag.Kind {
	case "inline":
		if _, ok := fields["dataRevision"]; !ok {
			return fmt.Errorf("decode VisualizationDataState variant %q: required property dataRevision is missing", tag.Kind)
		}
		if _, ok := fields["datasets"]; !ok {
			return fmt.Errorf("decode VisualizationDataState variant %q: required property datasets is missing", tag.Kind)
		}
		if _, ok := fields["generation"]; !ok {
			return fmt.Errorf("decode VisualizationDataState variant %q: required property generation is missing", tag.Kind)
		}
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationDataState variant %q: required property kind is missing", tag.Kind)
		}
		if _, ok := fields["specRevision"]; !ok {
			return fmt.Errorf("decode VisualizationDataState variant %q: required property specRevision is missing", tag.Kind)
		}
		var variant InlineVisualizationDataState
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationDataState variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "windowed":
		if _, ok := fields["availableRows"]; !ok {
			return fmt.Errorf("decode VisualizationDataState variant %q: required property availableRows is missing", tag.Kind)
		}
		if _, ok := fields["blocks"]; !ok {
			return fmt.Errorf("decode VisualizationDataState variant %q: required property blocks is missing", tag.Kind)
		}
		if _, ok := fields["cardinality"]; !ok {
			return fmt.Errorf("decode VisualizationDataState variant %q: required property cardinality is missing", tag.Kind)
		}
		if _, ok := fields["chunkSize"]; !ok {
			return fmt.Errorf("decode VisualizationDataState variant %q: required property chunkSize is missing", tag.Kind)
		}
		if _, ok := fields["dataRevision"]; !ok {
			return fmt.Errorf("decode VisualizationDataState variant %q: required property dataRevision is missing", tag.Kind)
		}
		if _, ok := fields["generation"]; !ok {
			return fmt.Errorf("decode VisualizationDataState variant %q: required property generation is missing", tag.Kind)
		}
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationDataState variant %q: required property kind is missing", tag.Kind)
		}
		if _, ok := fields["resetVersion"]; !ok {
			return fmt.Errorf("decode VisualizationDataState variant %q: required property resetVersion is missing", tag.Kind)
		}
		if _, ok := fields["rowCap"]; !ok {
			return fmt.Errorf("decode VisualizationDataState variant %q: required property rowCap is missing", tag.Kind)
		}
		if _, ok := fields["schema"]; !ok {
			return fmt.Errorf("decode VisualizationDataState variant %q: required property schema is missing", tag.Kind)
		}
		if _, ok := fields["sort"]; !ok {
			return fmt.Errorf("decode VisualizationDataState variant %q: required property sort is missing", tag.Kind)
		}
		if _, ok := fields["specRevision"]; !ok {
			return fmt.Errorf("decode VisualizationDataState variant %q: required property specRevision is missing", tag.Kind)
		}
		var variant WindowedVisualizationDataState
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationDataState variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	default:
		return fmt.Errorf("unknown VisualizationDataState discriminator %q", tag.Kind)
	}
	return nil
}

type VisualizationDataStateBase struct {
	Kind         string `json:"kind"`
	SpecRevision string `json:"specRevision"`
	DataRevision int64  `json:"dataRevision"`
	Generation   int64  `json:"generation"`
}

type VisualizationDataType string

const (
	VisualizationDataTypeString     VisualizationDataType = "string"
	VisualizationDataTypeBoolean    VisualizationDataType = "boolean"
	VisualizationDataTypeInteger    VisualizationDataType = "integer"
	VisualizationDataTypeDecimal    VisualizationDataType = "decimal"
	VisualizationDataTypeTemporal   VisualizationDataType = "temporal"
	VisualizationDataTypeDate       VisualizationDataType = "date"
	VisualizationDataTypeGeographic VisualizationDataType = "geographic"
)

type VisualizationDatasetSchema struct {
	ID     string               `json:"id"`
	Fields []VisualizationField `json:"fields"`
}

type VisualizationDatumRef struct {
	Dataset      string         `json:"dataset"`
	DataRevision int64          `json:"dataRevision"`
	Identity     map[string]any `json:"identity"`
	ResetVersion *int64         `json:"resetVersion,omitempty"`
	BlockID      *string        `json:"blockID,omitempty"`
}

type VisualizationDiagnostic struct {
	Code     string                          `json:"code"`
	Severity VisualizationDiagnosticSeverity `json:"severity"`
	Message  string                          `json:"message"`
	FieldID  *string                         `json:"fieldID,omitempty"`
}

type VisualizationDiagnosticSeverity string

const (
	VisualizationDiagnosticSeverityInfo    VisualizationDiagnosticSeverity = "info"
	VisualizationDiagnosticSeverityWarning VisualizationDiagnosticSeverity = "warning"
	VisualizationDiagnosticSeverityError   VisualizationDiagnosticSeverity = "error"
)

type VisualizationEnvelope struct {
	SchemaVersion int32                         `json:"schemaVersion"`
	VisualID      string                        `json:"visualID"`
	RendererID    string                        `json:"rendererID"`
	SpecRevision  string                        `json:"specRevision"`
	Spec          VisualizationSpec             `json:"spec"`
	DataRevision  int64                         `json:"dataRevision"`
	DataState     VisualizationDataState        `json:"dataState"`
	Selection     []VisualizationSelectionEntry `json:"selection"`
	Status        VisualizationStatus           `json:"status"`
	Diagnostics   []VisualizationDiagnostic     `json:"diagnostics"`
}

type VisualizationField struct {
	ID         string                           `json:"id"`
	SourceRef  *string                          `json:"sourceRef,omitempty"`
	Role       VisualizationFieldRole           `json:"role"`
	DataType   VisualizationDataType            `json:"dataType"`
	Nullable   bool                             `json:"nullable"`
	Label      string                           `json:"label"`
	Format     *VisualizationFormat             `json:"format,omitempty"`
	Time       *VisualizationTemporalMetadata   `json:"time,omitempty"`
	Geographic *VisualizationGeographicMetadata `json:"geographic,omitempty"`
	Grid       *VisualizationGridFieldMetadata  `json:"grid,omitempty"`
}

type VisualizationFieldRef struct {
	Dataset string `json:"dataset"`
	Field   string `json:"field"`
}

type VisualizationFieldRole string

const (
	VisualizationFieldRoleDimension VisualizationFieldRole = "dimension"
	VisualizationFieldRoleMeasure   VisualizationFieldRole = "measure"
	VisualizationFieldRoleMetadata  VisualizationFieldRole = "metadata"
	VisualizationFieldRoleIdentity  VisualizationFieldRole = "identity"
)

type VisualizationFormatVariant interface {
	isVisualizationFormatVariant()
}

type VisualizationFormat struct {
	Value VisualizationFormatVariant
}

func (CompactVisualizationFormat) isVisualizationFormatVariant()  {}
func (CurrencyVisualizationFormat) isVisualizationFormatVariant() {}
func (DurationVisualizationFormat) isVisualizationFormatVariant() {}
func (NumberVisualizationFormat) isVisualizationFormatVariant()   {}
func (PercentVisualizationFormat) isVisualizationFormatVariant()  {}
func (TemporalVisualizationFormat) isVisualizationFormatVariant() {}

func (value VisualizationFormat) MarshalJSON() ([]byte, error) {
	switch variant := value.Value.(type) {
	case CompactVisualizationFormat:
		return json.Marshal(variant)
	case *CompactVisualizationFormat:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationFormat variant is nil")
		}
		return json.Marshal(variant)
	case CurrencyVisualizationFormat:
		return json.Marshal(variant)
	case *CurrencyVisualizationFormat:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationFormat variant is nil")
		}
		return json.Marshal(variant)
	case DurationVisualizationFormat:
		return json.Marshal(variant)
	case *DurationVisualizationFormat:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationFormat variant is nil")
		}
		return json.Marshal(variant)
	case NumberVisualizationFormat:
		return json.Marshal(variant)
	case *NumberVisualizationFormat:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationFormat variant is nil")
		}
		return json.Marshal(variant)
	case PercentVisualizationFormat:
		return json.Marshal(variant)
	case *PercentVisualizationFormat:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationFormat variant is nil")
		}
		return json.Marshal(variant)
	case TemporalVisualizationFormat:
		return json.Marshal(variant)
	case *TemporalVisualizationFormat:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationFormat variant is nil")
		}
		return json.Marshal(variant)
	case nil:
		return nil, fmt.Errorf("VisualizationFormat variant is required")
	default:
		return nil, fmt.Errorf("unsupported VisualizationFormat variant %T", variant)
	}
}

func (value *VisualizationFormat) UnmarshalJSON(data []byte) error {
	if value == nil {
		return fmt.Errorf("cannot unmarshal VisualizationFormat into nil receiver")
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return fmt.Errorf("decode VisualizationFormat object: %w", err)
	}
	var tag struct {
		Kind string `json:"kind"`
	}
	if err := json.Unmarshal(data, &tag); err != nil {
		return fmt.Errorf("decode VisualizationFormat discriminator: %w", err)
	}
	if tag.Kind == "" {
		return fmt.Errorf("VisualizationFormat discriminator kind is required")
	}
	decode := func(dest any) error {
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		return decoder.Decode(dest)
	}
	switch tag.Kind {
	case "compact":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationFormat variant %q: required property kind is missing", tag.Kind)
		}
		var variant CompactVisualizationFormat
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationFormat variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "currency":
		if _, ok := fields["currency"]; !ok {
			return fmt.Errorf("decode VisualizationFormat variant %q: required property currency is missing", tag.Kind)
		}
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationFormat variant %q: required property kind is missing", tag.Kind)
		}
		var variant CurrencyVisualizationFormat
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationFormat variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "duration":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationFormat variant %q: required property kind is missing", tag.Kind)
		}
		if _, ok := fields["unit"]; !ok {
			return fmt.Errorf("decode VisualizationFormat variant %q: required property unit is missing", tag.Kind)
		}
		var variant DurationVisualizationFormat
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationFormat variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "number":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationFormat variant %q: required property kind is missing", tag.Kind)
		}
		var variant NumberVisualizationFormat
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationFormat variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "percent":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationFormat variant %q: required property kind is missing", tag.Kind)
		}
		var variant PercentVisualizationFormat
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationFormat variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "temporal":
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationFormat variant %q: required property kind is missing", tag.Kind)
		}
		var variant TemporalVisualizationFormat
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationFormat variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	default:
		return fmt.Errorf("unknown VisualizationFormat discriminator %q", tag.Kind)
	}
	return nil
}

type VisualizationFormatBase struct {
	Kind string `json:"kind"`
}

type VisualizationGeographicLayer struct {
	ID        string                           `json:"id"`
	Kind      VisualizationGeographicLayerKind `json:"kind"`
	Geometry  *VisualizationGeometryAsset      `json:"geometry,omitempty"`
	Join      *VisualizationFieldRef           `json:"join,omitempty"`
	Value     *VisualizationFieldRef           `json:"value,omitempty"`
	Latitude  *VisualizationFieldRef           `json:"latitude,omitempty"`
	Longitude *VisualizationFieldRef           `json:"longitude,omitempty"`
}

type VisualizationGeographicLayerKind string

const (
	VisualizationGeographicLayerKindChoropleth VisualizationGeographicLayerKind = "choropleth"
	VisualizationGeographicLayerKindPoint      VisualizationGeographicLayerKind = "point"
	VisualizationGeographicLayerKindHeat       VisualizationGeographicLayerKind = "heat"
	VisualizationGeographicLayerKindDensity    VisualizationGeographicLayerKind = "density"
)

type VisualizationGeographicMetadata struct {
	IdentifierSystem string `json:"identifierSystem"`
	GeometryAsset    string `json:"geometryAsset"`
	JoinField        string `json:"joinField"`
	UnmatchedPolicy  string `json:"unmatchedPolicy"`
}

type VisualizationGeometryAsset struct {
	ID               string `json:"id"`
	Digest           string `json:"digest"`
	Source           string `json:"source"`
	License          string `json:"license"`
	Attribution      string `json:"attribution"`
	IdentifierSystem string `json:"identifierSystem"`
	URL              string `json:"url"`
}

type VisualizationGraphFocus string

const (
	VisualizationGraphFocusNone      VisualizationGraphFocus = "none"
	VisualizationGraphFocusAdjacency VisualizationGraphFocus = "adjacency"
)

type VisualizationGridFieldMetadata struct {
	Group       *string                            `json:"group,omitempty"`
	Measure     *string                            `json:"measure,omitempty"`
	ColumnValue *string                            `json:"columnValue,omitempty"`
	Formatting  []TableVisualizationFormattingRule `json:"formatting"`
}

type VisualizationHierarchyLayout string

const (
	VisualizationHierarchyLayoutStandard VisualizationHierarchyLayout = "standard"
	VisualizationHierarchyLayoutCircular VisualizationHierarchyLayout = "circular"
)

type VisualizationHierarchyMark string

const (
	VisualizationHierarchyMarkTreemap  VisualizationHierarchyMark = "treemap"
	VisualizationHierarchyMarkSunburst VisualizationHierarchyMark = "sunburst"
	VisualizationHierarchyMarkTree     VisualizationHierarchyMark = "tree"
	VisualizationHierarchyMarkSankey   VisualizationHierarchyMark = "sankey"
	VisualizationHierarchyMarkGraph    VisualizationHierarchyMark = "graph"
)

type VisualizationInlineDataset struct {
	ID           string                    `json:"id"`
	SpecRevision string                    `json:"specRevision"`
	DataRevision int64                     `json:"dataRevision"`
	Generation   int64                     `json:"generation"`
	Columns      []string                  `json:"columns"`
	Rows         [][]any                   `json:"rows"`
	Completeness VisualizationCompleteness `json:"completeness"`
}

type VisualizationInteraction struct {
	ID                     string                            `json:"id"`
	Kind                   VisualizationInteractionKind      `json:"kind"`
	Mappings               []VisualizationInteractionMapping `json:"mappings"`
	Targets                []string                          `json:"targets"`
	Mode                   VisualizationSelectionMode        `json:"mode"`
	RequiresStableIdentity bool                              `json:"requiresStableIdentity"`
}

type VisualizationInteractionKind string

const (
	VisualizationInteractionKindSelect   VisualizationInteractionKind = "select"
	VisualizationInteractionKindFilter   VisualizationInteractionKind = "filter"
	VisualizationInteractionKindDrill    VisualizationInteractionKind = "drill"
	VisualizationInteractionKindNavigate VisualizationInteractionKind = "navigate"
)

type VisualizationInteractionMapping struct {
	Source        VisualizationFieldRef  `json:"source"`
	TargetFieldID string                 `json:"targetFieldID"`
	TargetFactID  *string                `json:"targetFactID,omitempty"`
	Grain         *string                `json:"grain,omitempty"`
	Label         *VisualizationFieldRef `json:"label,omitempty"`
}

type VisualizationKPITrend string

const (
	VisualizationKPITrendNeutral  VisualizationKPITrend = "neutral"
	VisualizationKPITrendPositive VisualizationKPITrend = "positive"
	VisualizationKPITrendNegative VisualizationKPITrend = "negative"
)

type VisualizationLabelPosition string

const (
	VisualizationLabelPositionAutomatic VisualizationLabelPosition = "automatic"
	VisualizationLabelPositionInside    VisualizationLabelPosition = "inside"
	VisualizationLabelPositionOutside   VisualizationLabelPosition = "outside"
	VisualizationLabelPositionTop       VisualizationLabelPosition = "top"
)

type VisualizationLegendPosition string

const (
	VisualizationLegendPositionHidden VisualizationLegendPosition = "hidden"
	VisualizationLegendPositionTop    VisualizationLegendPosition = "top"
	VisualizationLegendPositionRight  VisualizationLegendPosition = "right"
	VisualizationLegendPositionBottom VisualizationLegendPosition = "bottom"
	VisualizationLegendPositionLeft   VisualizationLegendPosition = "left"
)

type VisualizationOrientation string

const (
	VisualizationOrientationHorizontal VisualizationOrientation = "horizontal"
	VisualizationOrientationVertical   VisualizationOrientation = "vertical"
)

type VisualizationPolarMark string

const (
	VisualizationPolarMarkRadar VisualizationPolarMark = "radar"
	VisualizationPolarMarkGauge VisualizationPolarMark = "gauge"
)

type VisualizationPresentation struct {
	Legend     VisualizationLegendPosition `json:"legend"`
	ShowLabels bool                        `json:"showLabels"`
}

type VisualizationProportionalMark string

const (
	VisualizationProportionalMarkPie    VisualizationProportionalMark = "pie"
	VisualizationProportionalMarkDonut  VisualizationProportionalMark = "donut"
	VisualizationProportionalMarkFunnel VisualizationProportionalMark = "funnel"
)

type VisualizationSelectionEntry struct {
	Datum VisualizationDatumRef `json:"datum"`
	Label *string               `json:"label,omitempty"`
}

type VisualizationSelectionMode string

const (
	VisualizationSelectionModeSingle   VisualizationSelectionMode = "single"
	VisualizationSelectionModeMultiple VisualizationSelectionMode = "multiple"
)

type VisualizationSort struct {
	Field     VisualizationFieldRef      `json:"field"`
	Direction VisualizationSortDirection `json:"direction"`
}

type VisualizationSortDirection string

const (
	VisualizationSortDirectionAscending  VisualizationSortDirection = "ascending"
	VisualizationSortDirectionDescending VisualizationSortDirection = "descending"
)

type VisualizationSpecVariant interface {
	isVisualizationSpecVariant()
}

type VisualizationSpec struct {
	Value VisualizationSpecVariant
}

func (CartesianVisualizationSpec) isVisualizationSpecVariant()    {}
func (CustomVisualizationSpec) isVisualizationSpecVariant()       {}
func (GeographicVisualizationSpec) isVisualizationSpecVariant()   {}
func (HierarchyVisualizationSpec) isVisualizationSpecVariant()    {}
func (KPIVisualizationSpec) isVisualizationSpecVariant()          {}
func (MatrixVisualizationSpec) isVisualizationSpecVariant()       {}
func (PivotVisualizationSpec) isVisualizationSpecVariant()        {}
func (PolarVisualizationSpec) isVisualizationSpecVariant()        {}
func (ProportionalVisualizationSpec) isVisualizationSpecVariant() {}
func (TableVisualizationSpec) isVisualizationSpecVariant()        {}

func (value VisualizationSpec) MarshalJSON() ([]byte, error) {
	switch variant := value.Value.(type) {
	case CartesianVisualizationSpec:
		return json.Marshal(variant)
	case *CartesianVisualizationSpec:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationSpec variant is nil")
		}
		return json.Marshal(variant)
	case CustomVisualizationSpec:
		return json.Marshal(variant)
	case *CustomVisualizationSpec:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationSpec variant is nil")
		}
		return json.Marshal(variant)
	case GeographicVisualizationSpec:
		return json.Marshal(variant)
	case *GeographicVisualizationSpec:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationSpec variant is nil")
		}
		return json.Marshal(variant)
	case HierarchyVisualizationSpec:
		return json.Marshal(variant)
	case *HierarchyVisualizationSpec:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationSpec variant is nil")
		}
		return json.Marshal(variant)
	case KPIVisualizationSpec:
		return json.Marshal(variant)
	case *KPIVisualizationSpec:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationSpec variant is nil")
		}
		return json.Marshal(variant)
	case MatrixVisualizationSpec:
		return json.Marshal(variant)
	case *MatrixVisualizationSpec:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationSpec variant is nil")
		}
		return json.Marshal(variant)
	case PivotVisualizationSpec:
		return json.Marshal(variant)
	case *PivotVisualizationSpec:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationSpec variant is nil")
		}
		return json.Marshal(variant)
	case PolarVisualizationSpec:
		return json.Marshal(variant)
	case *PolarVisualizationSpec:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationSpec variant is nil")
		}
		return json.Marshal(variant)
	case ProportionalVisualizationSpec:
		return json.Marshal(variant)
	case *ProportionalVisualizationSpec:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationSpec variant is nil")
		}
		return json.Marshal(variant)
	case TableVisualizationSpec:
		return json.Marshal(variant)
	case *TableVisualizationSpec:
		if variant == nil {
			return nil, fmt.Errorf("VisualizationSpec variant is nil")
		}
		return json.Marshal(variant)
	case nil:
		return nil, fmt.Errorf("VisualizationSpec variant is required")
	default:
		return nil, fmt.Errorf("unsupported VisualizationSpec variant %T", variant)
	}
}

func (value *VisualizationSpec) UnmarshalJSON(data []byte) error {
	if value == nil {
		return fmt.Errorf("cannot unmarshal VisualizationSpec into nil receiver")
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return fmt.Errorf("decode VisualizationSpec object: %w", err)
	}
	var tag struct {
		Kind string `json:"kind"`
	}
	if err := json.Unmarshal(data, &tag); err != nil {
		return fmt.Errorf("decode VisualizationSpec discriminator: %w", err)
	}
	if tag.Kind == "" {
		return fmt.Errorf("VisualizationSpec discriminator kind is required")
	}
	decode := func(dest any) error {
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		return decoder.Decode(dest)
	}
	switch tag.Kind {
	case "cartesian":
		if _, ok := fields["accessibility"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property accessibility is missing", tag.Kind)
		}
		if _, ok := fields["dataBudget"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property dataBudget is missing", tag.Kind)
		}
		if _, ok := fields["datasets"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property datasets is missing", tag.Kind)
		}
		if _, ok := fields["interactions"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property interactions is missing", tag.Kind)
		}
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property kind is missing", tag.Kind)
		}
		if _, ok := fields["mark"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property mark is missing", tag.Kind)
		}
		if _, ok := fields["presentation"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property presentation is missing", tag.Kind)
		}
		if _, ok := fields["title"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property title is missing", tag.Kind)
		}
		if _, ok := fields["x"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property x is missing", tag.Kind)
		}
		if _, ok := fields["y"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property y is missing", tag.Kind)
		}
		var variant CartesianVisualizationSpec
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationSpec variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "custom":
		if _, ok := fields["accessibility"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property accessibility is missing", tag.Kind)
		}
		if _, ok := fields["dataBudget"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property dataBudget is missing", tag.Kind)
		}
		if _, ok := fields["datasets"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property datasets is missing", tag.Kind)
		}
		if _, ok := fields["engine"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property engine is missing", tag.Kind)
		}
		if _, ok := fields["interactions"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property interactions is missing", tag.Kind)
		}
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property kind is missing", tag.Kind)
		}
		if _, ok := fields["program"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property program is missing", tag.Kind)
		}
		if _, ok := fields["programDigest"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property programDigest is missing", tag.Kind)
		}
		if _, ok := fields["title"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property title is missing", tag.Kind)
		}
		var variant CustomVisualizationSpec
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationSpec variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "geographic":
		if _, ok := fields["accessibility"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property accessibility is missing", tag.Kind)
		}
		if _, ok := fields["dataBudget"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property dataBudget is missing", tag.Kind)
		}
		if _, ok := fields["datasets"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property datasets is missing", tag.Kind)
		}
		if _, ok := fields["interactions"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property interactions is missing", tag.Kind)
		}
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property kind is missing", tag.Kind)
		}
		if _, ok := fields["layers"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property layers is missing", tag.Kind)
		}
		if _, ok := fields["presentation"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property presentation is missing", tag.Kind)
		}
		if _, ok := fields["title"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property title is missing", tag.Kind)
		}
		var variant GeographicVisualizationSpec
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationSpec variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "hierarchy":
		if _, ok := fields["accessibility"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property accessibility is missing", tag.Kind)
		}
		if _, ok := fields["dataBudget"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property dataBudget is missing", tag.Kind)
		}
		if _, ok := fields["datasets"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property datasets is missing", tag.Kind)
		}
		if _, ok := fields["interactions"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property interactions is missing", tag.Kind)
		}
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property kind is missing", tag.Kind)
		}
		if _, ok := fields["mark"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property mark is missing", tag.Kind)
		}
		if _, ok := fields["node"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property node is missing", tag.Kind)
		}
		if _, ok := fields["presentation"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property presentation is missing", tag.Kind)
		}
		if _, ok := fields["title"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property title is missing", tag.Kind)
		}
		var variant HierarchyVisualizationSpec
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationSpec variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "kpi":
		if _, ok := fields["accessibility"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property accessibility is missing", tag.Kind)
		}
		if _, ok := fields["dataBudget"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property dataBudget is missing", tag.Kind)
		}
		if _, ok := fields["datasets"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property datasets is missing", tag.Kind)
		}
		if _, ok := fields["interactions"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property interactions is missing", tag.Kind)
		}
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property kind is missing", tag.Kind)
		}
		if _, ok := fields["presentation"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property presentation is missing", tag.Kind)
		}
		if _, ok := fields["title"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property title is missing", tag.Kind)
		}
		if _, ok := fields["value"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property value is missing", tag.Kind)
		}
		var variant KPIVisualizationSpec
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationSpec variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "matrix":
		if _, ok := fields["accessibility"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property accessibility is missing", tag.Kind)
		}
		if _, ok := fields["columns"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property columns is missing", tag.Kind)
		}
		if _, ok := fields["dataBudget"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property dataBudget is missing", tag.Kind)
		}
		if _, ok := fields["datasets"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property datasets is missing", tag.Kind)
		}
		if _, ok := fields["interactions"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property interactions is missing", tag.Kind)
		}
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property kind is missing", tag.Kind)
		}
		if _, ok := fields["measureFormatting"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property measureFormatting is missing", tag.Kind)
		}
		if _, ok := fields["measures"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property measures is missing", tag.Kind)
		}
		if _, ok := fields["presentation"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property presentation is missing", tag.Kind)
		}
		if _, ok := fields["rows"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property rows is missing", tag.Kind)
		}
		if _, ok := fields["title"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property title is missing", tag.Kind)
		}
		var variant MatrixVisualizationSpec
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationSpec variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "pivot":
		if _, ok := fields["accessibility"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property accessibility is missing", tag.Kind)
		}
		if _, ok := fields["columns"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property columns is missing", tag.Kind)
		}
		if _, ok := fields["dataBudget"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property dataBudget is missing", tag.Kind)
		}
		if _, ok := fields["datasets"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property datasets is missing", tag.Kind)
		}
		if _, ok := fields["interactions"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property interactions is missing", tag.Kind)
		}
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property kind is missing", tag.Kind)
		}
		if _, ok := fields["measureFormatting"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property measureFormatting is missing", tag.Kind)
		}
		if _, ok := fields["measures"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property measures is missing", tag.Kind)
		}
		if _, ok := fields["presentation"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property presentation is missing", tag.Kind)
		}
		if _, ok := fields["rows"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property rows is missing", tag.Kind)
		}
		if _, ok := fields["title"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property title is missing", tag.Kind)
		}
		var variant PivotVisualizationSpec
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationSpec variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "polar":
		if _, ok := fields["accessibility"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property accessibility is missing", tag.Kind)
		}
		if _, ok := fields["dataBudget"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property dataBudget is missing", tag.Kind)
		}
		if _, ok := fields["datasets"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property datasets is missing", tag.Kind)
		}
		if _, ok := fields["interactions"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property interactions is missing", tag.Kind)
		}
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property kind is missing", tag.Kind)
		}
		if _, ok := fields["mark"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property mark is missing", tag.Kind)
		}
		if _, ok := fields["presentation"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property presentation is missing", tag.Kind)
		}
		if _, ok := fields["title"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property title is missing", tag.Kind)
		}
		if _, ok := fields["value"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property value is missing", tag.Kind)
		}
		var variant PolarVisualizationSpec
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationSpec variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "proportional":
		if _, ok := fields["accessibility"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property accessibility is missing", tag.Kind)
		}
		if _, ok := fields["category"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property category is missing", tag.Kind)
		}
		if _, ok := fields["dataBudget"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property dataBudget is missing", tag.Kind)
		}
		if _, ok := fields["datasets"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property datasets is missing", tag.Kind)
		}
		if _, ok := fields["interactions"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property interactions is missing", tag.Kind)
		}
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property kind is missing", tag.Kind)
		}
		if _, ok := fields["mark"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property mark is missing", tag.Kind)
		}
		if _, ok := fields["presentation"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property presentation is missing", tag.Kind)
		}
		if _, ok := fields["title"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property title is missing", tag.Kind)
		}
		if _, ok := fields["value"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property value is missing", tag.Kind)
		}
		var variant ProportionalVisualizationSpec
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationSpec variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	case "table":
		if _, ok := fields["accessibility"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property accessibility is missing", tag.Kind)
		}
		if _, ok := fields["columns"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property columns is missing", tag.Kind)
		}
		if _, ok := fields["dataBudget"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property dataBudget is missing", tag.Kind)
		}
		if _, ok := fields["datasets"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property datasets is missing", tag.Kind)
		}
		if _, ok := fields["interactions"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property interactions is missing", tag.Kind)
		}
		if _, ok := fields["kind"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property kind is missing", tag.Kind)
		}
		if _, ok := fields["presentation"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property presentation is missing", tag.Kind)
		}
		if _, ok := fields["title"]; !ok {
			return fmt.Errorf("decode VisualizationSpec variant %q: required property title is missing", tag.Kind)
		}
		var variant TableVisualizationSpec
		if err := decode(&variant); err != nil {
			return fmt.Errorf("decode VisualizationSpec variant %q: %w", tag.Kind, err)
		}
		value.Value = &variant
	default:
		return fmt.Errorf("unknown VisualizationSpec discriminator %q", tag.Kind)
	}
	return nil
}

type VisualizationSpecBase struct {
	Kind          string                       `json:"kind"`
	Title         string                       `json:"title"`
	Datasets      []VisualizationDatasetSchema `json:"datasets"`
	DataBudget    VisualizationDataBudget      `json:"dataBudget"`
	Accessibility VisualizationAccessibility   `json:"accessibility"`
	Interactions  []VisualizationInteraction   `json:"interactions"`
}

type VisualizationStatus struct {
	Kind    VisualizationStatusKind `json:"kind"`
	Message *string                 `json:"message,omitempty"`
}

type VisualizationStatusKind string

const (
	VisualizationStatusKindIdle    VisualizationStatusKind = "idle"
	VisualizationStatusKindLoading VisualizationStatusKind = "loading"
	VisualizationStatusKindReady   VisualizationStatusKind = "ready"
	VisualizationStatusKindNoData  VisualizationStatusKind = "no_data"
	VisualizationStatusKindPartial VisualizationStatusKind = "partial"
	VisualizationStatusKindError   VisualizationStatusKind = "error"
)

type VisualizationTemporalMeaning string

const (
	VisualizationTemporalMeaningInstant VisualizationTemporalMeaning = "instant"
	VisualizationTemporalMeaningBucket  VisualizationTemporalMeaning = "bucket"
)

type VisualizationTemporalMetadata struct {
	Grain     string                       `json:"grain"`
	Timezone  string                       `json:"timezone"`
	Calendar  string                       `json:"calendar"`
	WeekStart VisualizationWeekStart       `json:"weekStart"`
	Meaning   VisualizationTemporalMeaning `json:"meaning"`
}

type VisualizationThreshold struct {
	Value float64           `json:"value"`
	Tone  VisualizationTone `json:"tone"`
}

type VisualizationTone string

const (
	VisualizationToneNeutral VisualizationTone = "neutral"
	VisualizationToneInk     VisualizationTone = "ink"
	VisualizationToneSuccess VisualizationTone = "success"
	VisualizationToneWarning VisualizationTone = "warning"
	VisualizationToneDanger  VisualizationTone = "danger"
)

type VisualizationWeekStart string

const (
	VisualizationWeekStartMonday    VisualizationWeekStart = "monday"
	VisualizationWeekStartTuesday   VisualizationWeekStart = "tuesday"
	VisualizationWeekStartWednesday VisualizationWeekStart = "wednesday"
	VisualizationWeekStartThursday  VisualizationWeekStart = "thursday"
	VisualizationWeekStartFriday    VisualizationWeekStart = "friday"
	VisualizationWeekStartSaturday  VisualizationWeekStart = "saturday"
	VisualizationWeekStartSunday    VisualizationWeekStart = "sunday"
)

type VisualizationWindowBlock struct {
	ID           string              `json:"id"`
	Start        int64               `json:"start"`
	Rows         [][]any             `json:"rows"`
	RequestSeq   int64               `json:"requestSeq"`
	ResetVersion int64               `json:"resetVersion"`
	Sort         []VisualizationSort `json:"sort"`
}

type WindowedVisualizationDataState struct {
	VisualizationDataStateBase
	Kind          string                              `json:"kind"`
	Schema        VisualizationDatasetSchema          `json:"schema"`
	Cardinality   VisualizationCardinality            `json:"cardinality"`
	AvailableRows int64                               `json:"availableRows"`
	RowCap        int64                               `json:"rowCap"`
	ChunkSize     int64                               `json:"chunkSize"`
	ResetVersion  int64                               `json:"resetVersion"`
	Sort          []VisualizationSort                 `json:"sort"`
	Blocks        map[string]VisualizationWindowBlock `json:"blocks"`
}
