// Package instanceidentity validates durable, non-secret LeapView instance IDs.
package instanceidentity

import "regexp"

var pattern = regexp.MustCompile(`^(?:lvinst_[A-Za-z0-9_-]{32}|instance_[0-9a-f]{32})$`)

// Valid reports whether value is a supported opaque LeapView instance ID.
// lvinst_ IDs are generated by the platform store. instance_ IDs remain valid
// for desktop profiles created against the original desktop contract.
func Valid(value string) bool {
	return pattern.MatchString(value)
}
