// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querydb

type QueryEvent struct {
	ID               string `json:"id"`
	WorkspaceID      string `json:"workspace_id"`
	PrincipalID      string `json:"principal_id"`
	Surface          string `json:"surface"`
	Operation        string `json:"operation"`
	QueryKind        string `json:"query_kind"`
	ModelID          string `json:"model_id"`
	Target           string `json:"target"`
	ObjectType       string `json:"object_type"`
	ObjectID         string `json:"object_id"`
	RequestID        string `json:"request_id"`
	CorrelationID    string `json:"correlation_id"`
	Status           string `json:"status"`
	DurationMs       int64  `json:"duration_ms"`
	RowsReturned     int64  `json:"rows_returned"`
	BytesEstimate    int64  `json:"bytes_estimate"`
	Error            string `json:"error"`
	SqlText          string `json:"sql_text"`
	PlanText         string `json:"plan_text"`
	QueryJson        string `json:"query_json"`
	CreatedAt        string `json:"created_at"`
	QueueWaitMs      int64  `json:"queue_wait_ms"`
	ExecutionMs      int64  `json:"execution_ms"`
	ExecutionState   string `json:"execution_state"`
	PlanningMs       int64  `json:"planning_ms"`
	ConnectionWaitMs int64  `json:"connection_wait_ms"`
	DatabaseMs       int64  `json:"database_ms"`
}
