// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type DashboardPublication struct {
	ID                     string         `json:"id"`
	ProjectID              string         `json:"project_id"`
	WorkspaceID            string         `json:"workspace_id"`
	Name                   string         `json:"name"`
	PublicID               string         `json:"public_id"`
	Dashboard              string         `json:"dashboard"`
	DefaultPage            string         `json:"default_page"`
	ConfigurationDigest    string         `json:"configuration_digest"`
	AllowedOriginsJson     string         `json:"allowed_origins_json"`
	DependencyAssetIdsJson string         `json:"dependency_asset_ids_json"`
	Configured             int64          `json:"configured"`
	ActiveServingStateID   sql.NullString `json:"active_serving_state_id"`
	SuspendedAt            sql.NullString `json:"suspended_at"`
	SuspendedBy            string         `json:"suspended_by"`
	ConfiguredAt           sql.NullString `json:"configured_at"`
	DisabledAt             sql.NullString `json:"disabled_at"`
	RotatedAt              sql.NullString `json:"rotated_at"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
}
