// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: publication.sql

package db

import (
	"context"
	"database/sql"
)

const createDashboardPublication = `-- name: CreateDashboardPublication :exec
INSERT INTO dashboard_publications
  (id, project_id, workspace_id, name, public_id, dashboard, default_page,
   configuration_digest, allowed_origins_json, dependency_asset_ids_json,
   configured, active_serving_state_id, configured_at)
VALUES
  (?1, ?2, ?3, ?4,
   ?5, ?6, ?7,
   ?8, ?9,
   ?10, 1, ?11,
   CURRENT_TIMESTAMP)
`

type CreateDashboardPublicationParams struct {
	ID                     string         `json:"id"`
	ProjectID              string         `json:"project_id"`
	WorkspaceID            string         `json:"workspace_id"`
	Name                   string         `json:"name"`
	PublicID               string         `json:"public_id"`
	Dashboard              string         `json:"dashboard"`
	DefaultPage            string         `json:"default_page"`
	ConfigurationDigest    string         `json:"configuration_digest"`
	AllowedOriginsJson     string         `json:"allowed_origins_json"`
	DependencyAssetIdsJson string         `json:"dependency_asset_ids_json"`
	ActiveServingStateID   sql.NullString `json:"active_serving_state_id"`
}

func (q *Queries) CreateDashboardPublication(ctx context.Context, arg CreateDashboardPublicationParams) error {
	_, err := q.db.ExecContext(ctx, createDashboardPublication,
		arg.ID,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.Name,
		arg.PublicID,
		arg.Dashboard,
		arg.DefaultPage,
		arg.ConfigurationDigest,
		arg.AllowedOriginsJson,
		arg.DependencyAssetIdsJson,
		arg.ActiveServingStateID,
	)
	return err
}

const dashboardPublicationStreamIsActive = `-- name: DashboardPublicationStreamIsActive :one
SELECT EXISTS(
  SELECT 1
  FROM dashboard_publication_streams
  WHERE publication_id = ?1
    AND stream_id = ?2
    AND public_id = ?3
    AND serving_state_id = ?4
    AND expires_at > ?5
)
`

type DashboardPublicationStreamIsActiveParams struct {
	PublicationID  string `json:"publication_id"`
	StreamID       string `json:"stream_id"`
	PublicID       string `json:"public_id"`
	ServingStateID string `json:"serving_state_id"`
	Now            string `json:"now"`
}

func (q *Queries) DashboardPublicationStreamIsActive(ctx context.Context, arg DashboardPublicationStreamIsActiveParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, dashboardPublicationStreamIsActive,
		arg.PublicationID,
		arg.StreamID,
		arg.PublicID,
		arg.ServingStateID,
		arg.Now,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteDashboardPublicationStreamRegistration = `-- name: DeleteDashboardPublicationStreamRegistration :exec
DELETE FROM dashboard_publication_streams
WHERE publication_id = ?1
  AND stream_id = ?2
  AND registration_id = ?3
`

type DeleteDashboardPublicationStreamRegistrationParams struct {
	PublicationID  string `json:"publication_id"`
	StreamID       string `json:"stream_id"`
	RegistrationID string `json:"registration_id"`
}

func (q *Queries) DeleteDashboardPublicationStreamRegistration(ctx context.Context, arg DeleteDashboardPublicationStreamRegistrationParams) error {
	_, err := q.db.ExecContext(ctx, deleteDashboardPublicationStreamRegistration, arg.PublicationID, arg.StreamID, arg.RegistrationID)
	return err
}

const deleteDashboardPublicationStreams = `-- name: DeleteDashboardPublicationStreams :exec
DELETE FROM dashboard_publication_streams
WHERE publication_id = ?1
`

func (q *Queries) DeleteDashboardPublicationStreams(ctx context.Context, publicationID string) error {
	_, err := q.db.ExecContext(ctx, deleteDashboardPublicationStreams, publicationID)
	return err
}

const deleteExpiredDashboardPublicationStreamEvents = `-- name: DeleteExpiredDashboardPublicationStreamEvents :exec
DELETE FROM dashboard_publication_stream_events
WHERE created_at <= ?1
`

func (q *Queries) DeleteExpiredDashboardPublicationStreamEvents(ctx context.Context, cutoff string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredDashboardPublicationStreamEvents, cutoff)
	return err
}

const deleteExpiredDashboardPublicationStreams = `-- name: DeleteExpiredDashboardPublicationStreams :exec
DELETE FROM dashboard_publication_streams
WHERE expires_at <= ?1
`

func (q *Queries) DeleteExpiredDashboardPublicationStreams(ctx context.Context, now string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredDashboardPublicationStreams, now)
	return err
}

const disableDashboardPublication = `-- name: DisableDashboardPublication :exec
UPDATE dashboard_publications
SET configured = 0,
    active_serving_state_id = NULL,
    disabled_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
`

func (q *Queries) DisableDashboardPublication(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, disableDashboardPublication, id)
	return err
}

const extendDashboardPublicationStreamRegistration = `-- name: ExtendDashboardPublicationStreamRegistration :execresult
UPDATE dashboard_publication_streams
SET expires_at = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE publication_id = ?2
  AND stream_id = ?3
  AND registration_id = ?4
`

type ExtendDashboardPublicationStreamRegistrationParams struct {
	ExpiresAt      string `json:"expires_at"`
	PublicationID  string `json:"publication_id"`
	StreamID       string `json:"stream_id"`
	RegistrationID string `json:"registration_id"`
}

func (q *Queries) ExtendDashboardPublicationStreamRegistration(ctx context.Context, arg ExtendDashboardPublicationStreamRegistrationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, extendDashboardPublicationStreamRegistration,
		arg.ExpiresAt,
		arg.PublicationID,
		arg.StreamID,
		arg.RegistrationID,
	)
}

const getConfiguredDashboardPublication = `-- name: GetConfiguredDashboardPublication :one
SELECT id, project_id, workspace_id, name, public_id, dashboard, default_page, configuration_digest, allowed_origins_json, dependency_asset_ids_json, configured, active_serving_state_id, suspended_at, suspended_by, configured_at, disabled_at, rotated_at, created_at, updated_at
FROM dashboard_publications
WHERE workspace_id = ?1
  AND name = ?2
  AND configured = 1
`

type GetConfiguredDashboardPublicationParams struct {
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) GetConfiguredDashboardPublication(ctx context.Context, arg GetConfiguredDashboardPublicationParams) (DashboardPublication, error) {
	row := q.db.QueryRowContext(ctx, getConfiguredDashboardPublication, arg.WorkspaceID, arg.Name)
	var i DashboardPublication
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.Name,
		&i.PublicID,
		&i.Dashboard,
		&i.DefaultPage,
		&i.ConfigurationDigest,
		&i.AllowedOriginsJson,
		&i.DependencyAssetIdsJson,
		&i.Configured,
		&i.ActiveServingStateID,
		&i.SuspendedAt,
		&i.SuspendedBy,
		&i.ConfiguredAt,
		&i.DisabledAt,
		&i.RotatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDashboardPublication = `-- name: GetDashboardPublication :one
SELECT id, project_id, workspace_id, name, public_id, dashboard, default_page, configuration_digest, allowed_origins_json, dependency_asset_ids_json, configured, active_serving_state_id, suspended_at, suspended_by, configured_at, disabled_at, rotated_at, created_at, updated_at
FROM dashboard_publications
WHERE workspace_id = ?1
  AND name = ?2
ORDER BY configured DESC, updated_at DESC
LIMIT 1
`

type GetDashboardPublicationParams struct {
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) GetDashboardPublication(ctx context.Context, arg GetDashboardPublicationParams) (DashboardPublication, error) {
	row := q.db.QueryRowContext(ctx, getDashboardPublication, arg.WorkspaceID, arg.Name)
	var i DashboardPublication
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.Name,
		&i.PublicID,
		&i.Dashboard,
		&i.DefaultPage,
		&i.ConfigurationDigest,
		&i.AllowedOriginsJson,
		&i.DependencyAssetIdsJson,
		&i.Configured,
		&i.ActiveServingStateID,
		&i.SuspendedAt,
		&i.SuspendedBy,
		&i.ConfiguredAt,
		&i.DisabledAt,
		&i.RotatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDashboardPublicationByPublicID = `-- name: GetDashboardPublicationByPublicID :one
SELECT id, project_id, workspace_id, name, public_id, dashboard, default_page, configuration_digest, allowed_origins_json, dependency_asset_ids_json, configured, active_serving_state_id, suspended_at, suspended_by, configured_at, disabled_at, rotated_at, created_at, updated_at
FROM dashboard_publications
WHERE public_id = ?1
  AND configured = 1
  AND active_serving_state_id IS NOT NULL
`

func (q *Queries) GetDashboardPublicationByPublicID(ctx context.Context, publicID string) (DashboardPublication, error) {
	row := q.db.QueryRowContext(ctx, getDashboardPublicationByPublicID, publicID)
	var i DashboardPublication
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.Name,
		&i.PublicID,
		&i.Dashboard,
		&i.DefaultPage,
		&i.ConfigurationDigest,
		&i.AllowedOriginsJson,
		&i.DependencyAssetIdsJson,
		&i.Configured,
		&i.ActiveServingStateID,
		&i.SuspendedAt,
		&i.SuspendedBy,
		&i.ConfiguredAt,
		&i.DisabledAt,
		&i.RotatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDashboardPublicationCommandState = `-- name: GetDashboardPublicationCommandState :one
SELECT filters_json, generation
FROM dashboard_publication_streams
WHERE publication_id = ?1
  AND stream_id = ?2
  AND public_id = ?3
  AND serving_state_id = ?4
  AND expires_at > ?5
`

type GetDashboardPublicationCommandStateParams struct {
	PublicationID  string `json:"publication_id"`
	StreamID       string `json:"stream_id"`
	PublicID       string `json:"public_id"`
	ServingStateID string `json:"serving_state_id"`
	Now            string `json:"now"`
}

type GetDashboardPublicationCommandStateRow struct {
	FiltersJson string `json:"filters_json"`
	Generation  int64  `json:"generation"`
}

func (q *Queries) GetDashboardPublicationCommandState(ctx context.Context, arg GetDashboardPublicationCommandStateParams) (GetDashboardPublicationCommandStateRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardPublicationCommandState,
		arg.PublicationID,
		arg.StreamID,
		arg.PublicID,
		arg.ServingStateID,
		arg.Now,
	)
	var i GetDashboardPublicationCommandStateRow
	err := row.Scan(&i.FiltersJson, &i.Generation)
	return i, err
}

const getDashboardPublicationConfiguredState = `-- name: GetDashboardPublicationConfiguredState :one
SELECT configured
FROM dashboard_publications
WHERE workspace_id = ?1
  AND name = ?2
ORDER BY configured DESC
LIMIT 1
`

type GetDashboardPublicationConfiguredStateParams struct {
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) GetDashboardPublicationConfiguredState(ctx context.Context, arg GetDashboardPublicationConfiguredStateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDashboardPublicationConfiguredState, arg.WorkspaceID, arg.Name)
	var configured int64
	err := row.Scan(&configured)
	return configured, err
}

const getLatestDashboardPublicationStreamEventID = `-- name: GetLatestDashboardPublicationStreamEventID :one
SELECT CAST(COALESCE(MAX(id), 0) AS INTEGER)
FROM dashboard_publication_stream_events
WHERE stream_id = ?1
`

func (q *Queries) GetLatestDashboardPublicationStreamEventID(ctx context.Context, streamID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLatestDashboardPublicationStreamEventID, streamID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertDashboardPublicationEvent = `-- name: InsertDashboardPublicationEvent :exec
INSERT INTO dashboard_publication_events
  (publication_id, event_type, actor_id, serving_state_id)
VALUES
  (?1, ?2, ?3, NULLIF(?4, ''))
`

type InsertDashboardPublicationEventParams struct {
	PublicationID  string      `json:"publication_id"`
	EventType      string      `json:"event_type"`
	ActorID        string      `json:"actor_id"`
	ServingStateID interface{} `json:"serving_state_id"`
}

func (q *Queries) InsertDashboardPublicationEvent(ctx context.Context, arg InsertDashboardPublicationEventParams) error {
	_, err := q.db.ExecContext(ctx, insertDashboardPublicationEvent,
		arg.PublicationID,
		arg.EventType,
		arg.ActorID,
		arg.ServingStateID,
	)
	return err
}

const insertDashboardPublicationStreamEvent = `-- name: InsertDashboardPublicationStreamEvent :exec
INSERT INTO dashboard_publication_stream_events
  (stream_id, envelope_json, created_at)
VALUES
  (?1, ?2, ?3)
`

type InsertDashboardPublicationStreamEventParams struct {
	StreamID     string `json:"stream_id"`
	EnvelopeJson string `json:"envelope_json"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) InsertDashboardPublicationStreamEvent(ctx context.Context, arg InsertDashboardPublicationStreamEventParams) error {
	_, err := q.db.ExecContext(ctx, insertDashboardPublicationStreamEvent, arg.StreamID, arg.EnvelopeJson, arg.CreatedAt)
	return err
}

const listActiveDashboardPublicationStreamRegistrations = `-- name: ListActiveDashboardPublicationStreamRegistrations :many
SELECT publication_id, stream_id, registration_id
FROM dashboard_publication_streams
WHERE expires_at > ?1
`

type ListActiveDashboardPublicationStreamRegistrationsRow struct {
	PublicationID  string `json:"publication_id"`
	StreamID       string `json:"stream_id"`
	RegistrationID string `json:"registration_id"`
}

func (q *Queries) ListActiveDashboardPublicationStreamRegistrations(ctx context.Context, now string) ([]ListActiveDashboardPublicationStreamRegistrationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDashboardPublicationStreamRegistrations, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveDashboardPublicationStreamRegistrationsRow{}
	for rows.Next() {
		var i ListActiveDashboardPublicationStreamRegistrationsRow
		if err := rows.Scan(&i.PublicationID, &i.StreamID, &i.RegistrationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDashboardPublications = `-- name: ListAllDashboardPublications :many
SELECT id, project_id, workspace_id, name, public_id, dashboard, default_page, configuration_digest, allowed_origins_json, dependency_asset_ids_json, configured, active_serving_state_id, suspended_at, suspended_by, configured_at, disabled_at, rotated_at, created_at, updated_at
FROM dashboard_publications
ORDER BY workspace_id, name, project_id
`

func (q *Queries) ListAllDashboardPublications(ctx context.Context) ([]DashboardPublication, error) {
	rows, err := q.db.QueryContext(ctx, listAllDashboardPublications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardPublication{}
	for rows.Next() {
		var i DashboardPublication
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.Name,
			&i.PublicID,
			&i.Dashboard,
			&i.DefaultPage,
			&i.ConfigurationDigest,
			&i.AllowedOriginsJson,
			&i.DependencyAssetIdsJson,
			&i.Configured,
			&i.ActiveServingStateID,
			&i.SuspendedAt,
			&i.SuspendedBy,
			&i.ConfiguredAt,
			&i.DisabledAt,
			&i.RotatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardPublicationEvents = `-- name: ListDashboardPublicationEvents :many
SELECT event_type, actor_id, COALESCE(serving_state_id, '') AS serving_state_id, created_at
FROM dashboard_publication_events
WHERE publication_id = ?1
ORDER BY id DESC
`

type ListDashboardPublicationEventsRow struct {
	EventType      string `json:"event_type"`
	ActorID        string `json:"actor_id"`
	ServingStateID string `json:"serving_state_id"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) ListDashboardPublicationEvents(ctx context.Context, publicationID string) ([]ListDashboardPublicationEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDashboardPublicationEvents, publicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDashboardPublicationEventsRow{}
	for rows.Next() {
		var i ListDashboardPublicationEventsRow
		if err := rows.Scan(
			&i.EventType,
			&i.ActorID,
			&i.ServingStateID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardPublicationStreamEventsAfter = `-- name: ListDashboardPublicationStreamEventsAfter :many
SELECT id, envelope_json
FROM dashboard_publication_stream_events
WHERE stream_id = ?1
  AND id > ?2
ORDER BY id
`

type ListDashboardPublicationStreamEventsAfterParams struct {
	StreamID string `json:"stream_id"`
	Cursor   int64  `json:"cursor"`
}

type ListDashboardPublicationStreamEventsAfterRow struct {
	ID           int64  `json:"id"`
	EnvelopeJson string `json:"envelope_json"`
}

func (q *Queries) ListDashboardPublicationStreamEventsAfter(ctx context.Context, arg ListDashboardPublicationStreamEventsAfterParams) ([]ListDashboardPublicationStreamEventsAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listDashboardPublicationStreamEventsAfter, arg.StreamID, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDashboardPublicationStreamEventsAfterRow{}
	for rows.Next() {
		var i ListDashboardPublicationStreamEventsAfterRow
		if err := rows.Scan(&i.ID, &i.EnvelopeJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardPublications = `-- name: ListDashboardPublications :many
SELECT id, project_id, workspace_id, name, public_id, dashboard, default_page, configuration_digest, allowed_origins_json, dependency_asset_ids_json, configured, active_serving_state_id, suspended_at, suspended_by, configured_at, disabled_at, rotated_at, created_at, updated_at
FROM dashboard_publications
WHERE workspace_id = ?1
ORDER BY name, project_id
`

func (q *Queries) ListDashboardPublications(ctx context.Context, workspaceID string) ([]DashboardPublication, error) {
	rows, err := q.db.QueryContext(ctx, listDashboardPublications, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardPublication{}
	for rows.Next() {
		var i DashboardPublication
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.Name,
			&i.PublicID,
			&i.Dashboard,
			&i.DefaultPage,
			&i.ConfigurationDigest,
			&i.AllowedOriginsJson,
			&i.DependencyAssetIdsJson,
			&i.Configured,
			&i.ActiveServingStateID,
			&i.SuspendedAt,
			&i.SuspendedBy,
			&i.ConfiguredAt,
			&i.DisabledAt,
			&i.RotatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectDashboardPublicationStates = `-- name: ListProjectDashboardPublicationStates :many
SELECT id, name, configured, configuration_digest
FROM dashboard_publications
WHERE project_id = ?1
  AND workspace_id = ?2
`

type ListProjectDashboardPublicationStatesParams struct {
	ProjectID   string `json:"project_id"`
	WorkspaceID string `json:"workspace_id"`
}

type ListProjectDashboardPublicationStatesRow struct {
	ID                  string `json:"id"`
	Name                string `json:"name"`
	Configured          int64  `json:"configured"`
	ConfigurationDigest string `json:"configuration_digest"`
}

func (q *Queries) ListProjectDashboardPublicationStates(ctx context.Context, arg ListProjectDashboardPublicationStatesParams) ([]ListProjectDashboardPublicationStatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectDashboardPublicationStates, arg.ProjectID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectDashboardPublicationStatesRow{}
	for rows.Next() {
		var i ListProjectDashboardPublicationStatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Configured,
			&i.ConfigurationDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupersededDashboardPublicationIDs = `-- name: ListSupersededDashboardPublicationIDs :many
SELECT id
FROM dashboard_publications
WHERE workspace_id = ?1
  AND project_id <> ?2
  AND configured = 1
`

type ListSupersededDashboardPublicationIDsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
}

func (q *Queries) ListSupersededDashboardPublicationIDs(ctx context.Context, arg ListSupersededDashboardPublicationIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSupersededDashboardPublicationIDs, arg.WorkspaceID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resumeDashboardPublication = `-- name: ResumeDashboardPublication :execresult
UPDATE dashboard_publications
SET suspended_at = NULL,
    suspended_by = '',
    updated_at = CURRENT_TIMESTAMP
WHERE workspace_id = ?1
  AND name = ?2
  AND configured = 1
`

type ResumeDashboardPublicationParams struct {
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) ResumeDashboardPublication(ctx context.Context, arg ResumeDashboardPublicationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, resumeDashboardPublication, arg.WorkspaceID, arg.Name)
}

const rotateDashboardPublication = `-- name: RotateDashboardPublication :execresult
UPDATE dashboard_publications
SET public_id = ?1,
    rotated_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE workspace_id = ?2
  AND name = ?3
  AND configured = 1
`

type RotateDashboardPublicationParams struct {
	PublicID    string `json:"public_id"`
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) RotateDashboardPublication(ctx context.Context, arg RotateDashboardPublicationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, rotateDashboardPublication, arg.PublicID, arg.WorkspaceID, arg.Name)
}

const suspendDashboardPublication = `-- name: SuspendDashboardPublication :execresult
UPDATE dashboard_publications
SET suspended_at = COALESCE(suspended_at, CURRENT_TIMESTAMP),
    suspended_by = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE workspace_id = ?2
  AND name = ?3
  AND configured = 1
`

type SuspendDashboardPublicationParams struct {
	ActorID     string `json:"actor_id"`
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) SuspendDashboardPublication(ctx context.Context, arg SuspendDashboardPublicationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, suspendDashboardPublication, arg.ActorID, arg.WorkspaceID, arg.Name)
}

const updateDashboardPublicationCommandState = `-- name: UpdateDashboardPublicationCommandState :execresult
UPDATE dashboard_publication_streams
SET filters_json = ?1,
    generation = ?2,
    expires_at = ?3,
    updated_at = CURRENT_TIMESTAMP
WHERE publication_id = ?4
  AND stream_id = ?5
  AND public_id = ?6
  AND serving_state_id = ?7
  AND generation = ?8
  AND expires_at > ?9
`

type UpdateDashboardPublicationCommandStateParams struct {
	FiltersJson       string `json:"filters_json"`
	NextGeneration    int64  `json:"next_generation"`
	ExpiresAt         string `json:"expires_at"`
	PublicationID     string `json:"publication_id"`
	StreamID          string `json:"stream_id"`
	PublicID          string `json:"public_id"`
	ServingStateID    string `json:"serving_state_id"`
	CurrentGeneration int64  `json:"current_generation"`
	Now               string `json:"now"`
}

func (q *Queries) UpdateDashboardPublicationCommandState(ctx context.Context, arg UpdateDashboardPublicationCommandStateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateDashboardPublicationCommandState,
		arg.FiltersJson,
		arg.NextGeneration,
		arg.ExpiresAt,
		arg.PublicationID,
		arg.StreamID,
		arg.PublicID,
		arg.ServingStateID,
		arg.CurrentGeneration,
		arg.Now,
	)
}

const updateDashboardPublicationConfiguration = `-- name: UpdateDashboardPublicationConfiguration :exec
UPDATE dashboard_publications
SET dashboard = ?1,
    default_page = ?2,
    configuration_digest = ?3,
    allowed_origins_json = ?4,
    dependency_asset_ids_json = ?5,
    configured = 1,
    active_serving_state_id = ?6,
    configured_at = CASE WHEN configured = 0 THEN CURRENT_TIMESTAMP ELSE configured_at END,
    disabled_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?7
`

type UpdateDashboardPublicationConfigurationParams struct {
	Dashboard              string         `json:"dashboard"`
	DefaultPage            string         `json:"default_page"`
	ConfigurationDigest    string         `json:"configuration_digest"`
	AllowedOriginsJson     string         `json:"allowed_origins_json"`
	DependencyAssetIdsJson string         `json:"dependency_asset_ids_json"`
	ActiveServingStateID   sql.NullString `json:"active_serving_state_id"`
	ID                     string         `json:"id"`
}

func (q *Queries) UpdateDashboardPublicationConfiguration(ctx context.Context, arg UpdateDashboardPublicationConfigurationParams) error {
	_, err := q.db.ExecContext(ctx, updateDashboardPublicationConfiguration,
		arg.Dashboard,
		arg.DefaultPage,
		arg.ConfigurationDigest,
		arg.AllowedOriginsJson,
		arg.DependencyAssetIdsJson,
		arg.ActiveServingStateID,
		arg.ID,
	)
	return err
}

const upsertDashboardPublicationStream = `-- name: UpsertDashboardPublicationStream :exec
INSERT INTO dashboard_publication_streams
  (publication_id, stream_id, public_id, serving_state_id, registration_id, filters_json, expires_at)
VALUES
  (?1, ?2, ?3,
   ?4, ?5, ?6,
   ?7)
ON CONFLICT(publication_id, stream_id) DO UPDATE SET
  public_id = excluded.public_id,
  serving_state_id = excluded.serving_state_id,
  registration_id = excluded.registration_id,
  filters_json = excluded.filters_json,
  generation = 1,
  expires_at = excluded.expires_at,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertDashboardPublicationStreamParams struct {
	PublicationID  string `json:"publication_id"`
	StreamID       string `json:"stream_id"`
	PublicID       string `json:"public_id"`
	ServingStateID string `json:"serving_state_id"`
	RegistrationID string `json:"registration_id"`
	FiltersJson    string `json:"filters_json"`
	ExpiresAt      string `json:"expires_at"`
}

func (q *Queries) UpsertDashboardPublicationStream(ctx context.Context, arg UpsertDashboardPublicationStreamParams) error {
	_, err := q.db.ExecContext(ctx, upsertDashboardPublicationStream,
		arg.PublicationID,
		arg.StreamID,
		arg.PublicID,
		arg.ServingStateID,
		arg.RegistrationID,
		arg.FiltersJson,
		arg.ExpiresAt,
	)
	return err
}
