// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"
	"database/sql"
)

const compareAndSwapDashboardViewSession = `-- name: CompareAndSwapDashboardViewSession :execresult
UPDATE dashboard_view_sessions
SET version = version + 1,
    state_json = ?1,
    expires_at = ?2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?3
  AND version = ?4
  AND expires_at > ?5
`

type CompareAndSwapDashboardViewSessionParams struct {
	StateJson string `json:"state_json"`
	ExpiresAt string `json:"expires_at"`
	ID        string `json:"id"`
	Version   int64  `json:"version"`
	Now       string `json:"now"`
}

func (q *Queries) CompareAndSwapDashboardViewSession(ctx context.Context, arg CompareAndSwapDashboardViewSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, compareAndSwapDashboardViewSession,
		arg.StateJson,
		arg.ExpiresAt,
		arg.ID,
		arg.Version,
		arg.Now,
	)
}

const createDashboardViewSession = `-- name: CreateDashboardViewSession :exec
INSERT INTO dashboard_view_sessions
  (id, key_json, version, state_json, expires_at)
VALUES
  (?1, ?2, 1, ?3, ?4)
`

type CreateDashboardViewSessionParams struct {
	ID        string `json:"id"`
	KeyJson   string `json:"key_json"`
	StateJson string `json:"state_json"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) CreateDashboardViewSession(ctx context.Context, arg CreateDashboardViewSessionParams) error {
	_, err := q.db.ExecContext(ctx, createDashboardViewSession,
		arg.ID,
		arg.KeyJson,
		arg.StateJson,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredDashboardViewSessions = `-- name: DeleteExpiredDashboardViewSessions :exec
DELETE FROM dashboard_view_sessions
WHERE expires_at <= ?1
`

func (q *Queries) DeleteExpiredDashboardViewSessions(ctx context.Context, now string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredDashboardViewSessions, now)
	return err
}

const getActiveDashboardViewSession = `-- name: GetActiveDashboardViewSession :one
SELECT key_json, version, state_json, expires_at
FROM dashboard_view_sessions
WHERE id = ?1
  AND expires_at > ?2
`

type GetActiveDashboardViewSessionParams struct {
	ID  string `json:"id"`
	Now string `json:"now"`
}

type GetActiveDashboardViewSessionRow struct {
	KeyJson   string `json:"key_json"`
	Version   int64  `json:"version"`
	StateJson string `json:"state_json"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) GetActiveDashboardViewSession(ctx context.Context, arg GetActiveDashboardViewSessionParams) (GetActiveDashboardViewSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveDashboardViewSession, arg.ID, arg.Now)
	var i GetActiveDashboardViewSessionRow
	err := row.Scan(
		&i.KeyJson,
		&i.Version,
		&i.StateJson,
		&i.ExpiresAt,
	)
	return i, err
}

const touchDashboardViewSession = `-- name: TouchDashboardViewSession :execresult
UPDATE dashboard_view_sessions
SET expires_at = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
  AND expires_at > ?3
`

type TouchDashboardViewSessionParams struct {
	ExpiresAt string `json:"expires_at"`
	ID        string `json:"id"`
	Now       string `json:"now"`
}

func (q *Queries) TouchDashboardViewSession(ctx context.Context, arg TouchDashboardViewSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, touchDashboardViewSession, arg.ExpiresAt, arg.ID, arg.Now)
}
