// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace.sql

package workspacedb

import (
	"context"
	"database/sql"
)

const getActiveServingState = `-- name: GetActiveServingState :one

SELECT d.id, d.workspace_id, d.status, d.digest, d.manifest_json, d.created_by, d.created_at, d.activated_at, d.error, d.environment, d.ducklake_snapshot_id, d.source, d.superseded_at, d.project_id, d.project_digest, d.project_workspaces_json, d.access_policy_json, d.dashboard_publications_json
FROM serving_states d
JOIN workspace_active_serving_states active ON active.serving_state_id = d.id
WHERE active.workspace_id = ? AND active.environment = ?
`

type GetActiveServingStateParams struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
}

// Workspace-owned catalog projection over the active serving generation.
func (q *Queries) GetActiveServingState(ctx context.Context, arg GetActiveServingStateParams) (ServingState, error) {
	row := q.db.QueryRowContext(ctx, getActiveServingState, arg.WorkspaceID, arg.Environment)
	var i ServingState
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Status,
		&i.Digest,
		&i.ManifestJson,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.Error,
		&i.Environment,
		&i.DucklakeSnapshotID,
		&i.Source,
		&i.SupersededAt,
		&i.ProjectID,
		&i.ProjectDigest,
		&i.ProjectWorkspacesJson,
		&i.AccessPolicyJson,
		&i.DashboardPublicationsJson,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, title, description, created_at, updated_at FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceWithActiveMetadata = `-- name: GetWorkspaceWithActiveMetadata :one
SELECT
  w.id,
  CASE WHEN a.title IS NOT NULL AND a.title <> '' THEN a.title ELSE w.title END AS title,
  CASE WHEN a.description IS NOT NULL THEN a.description ELSE w.description END AS description,
  COALESCE(active.serving_state_id, '') AS active_serving_state_id,
  w.created_at,
  w.updated_at
FROM workspaces w
LEFT JOIN workspace_active_serving_states active
  ON active.workspace_id = w.id AND active.environment = ?
LEFT JOIN assets a
  ON a.serving_state_id = active.serving_state_id
 AND a.asset_type = 'catalog'
 AND a.logical_asset_id = 'catalog:' || w.id
WHERE w.id = ?
`

type GetWorkspaceWithActiveMetadataParams struct {
	Environment string `json:"environment"`
	ID          string `json:"id"`
}

type GetWorkspaceWithActiveMetadataRow struct {
	ID                   string      `json:"id"`
	Title                interface{} `json:"title"`
	Description          interface{} `json:"description"`
	ActiveServingStateID string      `json:"active_serving_state_id"`
	CreatedAt            string      `json:"created_at"`
	UpdatedAt            string      `json:"updated_at"`
}

func (q *Queries) GetWorkspaceWithActiveMetadata(ctx context.Context, arg GetWorkspaceWithActiveMetadataParams) (GetWorkspaceWithActiveMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceWithActiveMetadata, arg.Environment, arg.ID)
	var i GetWorkspaceWithActiveMetadataRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ActiveServingStateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssetEdgesByServingState = `-- name: ListAssetEdgesByServingState :many
SELECT id, workspace_id, serving_state_id, from_logical_asset_id, to_logical_asset_id, edge_type, created_at FROM asset_edges WHERE serving_state_id = ? ORDER BY edge_type, from_logical_asset_id, to_logical_asset_id
`

func (q *Queries) ListAssetEdgesByServingState(ctx context.Context, servingStateID string) ([]AssetEdge, error) {
	rows, err := q.db.QueryContext(ctx, listAssetEdgesByServingState, servingStateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetEdge{}
	for rows.Next() {
		var i AssetEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ServingStateID,
			&i.FromLogicalAssetID,
			&i.ToLogicalAssetID,
			&i.EdgeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetVersions = `-- name: ListAssetVersions :many
SELECT
  d.id AS serving_state_id,
  d.workspace_id,
  d.environment,
  d.status,
  d.digest,
  d.created_by,
  d.created_at,
  d.activated_at,
  a.snapshot_id,
  a.logical_asset_id,
  a.source_file,
  a.content_hash
FROM serving_states d
JOIN assets a ON a.serving_state_id = d.id
WHERE d.workspace_id = ?
  AND d.environment = ?
  AND a.logical_asset_id = ?
  AND d.source = 'publish'
  AND d.status IN ('active', 'draining', 'inactive', 'validated')
  AND NOT EXISTS (
    SELECT 1
    FROM serving_states newer
    JOIN assets newer_asset ON newer_asset.serving_state_id = newer.id
    WHERE newer.workspace_id = d.workspace_id
      AND newer.environment = d.environment
      AND newer.source = 'publish'
      AND newer.status IN ('active', 'draining', 'inactive', 'validated')
      AND newer_asset.logical_asset_id = a.logical_asset_id
      AND newer_asset.content_hash = a.content_hash
      AND (
        COALESCE(newer.activated_at, newer.created_at) > COALESCE(d.activated_at, d.created_at)
        OR (
          COALESCE(newer.activated_at, newer.created_at) = COALESCE(d.activated_at, d.created_at)
          AND newer.created_at > d.created_at
        )
        OR (
          COALESCE(newer.activated_at, newer.created_at) = COALESCE(d.activated_at, d.created_at)
          AND newer.created_at = d.created_at
          AND newer.id > d.id
        )
      )
  )
ORDER BY
  COALESCE(d.activated_at, d.created_at) DESC,
  d.created_at DESC,
  d.id DESC
`

type ListAssetVersionsParams struct {
	WorkspaceID    string `json:"workspace_id"`
	Environment    string `json:"environment"`
	LogicalAssetID string `json:"logical_asset_id"`
}

type ListAssetVersionsRow struct {
	ServingStateID string         `json:"serving_state_id"`
	WorkspaceID    string         `json:"workspace_id"`
	Environment    string         `json:"environment"`
	Status         string         `json:"status"`
	Digest         string         `json:"digest"`
	CreatedBy      string         `json:"created_by"`
	CreatedAt      string         `json:"created_at"`
	ActivatedAt    sql.NullString `json:"activated_at"`
	SnapshotID     string         `json:"snapshot_id"`
	LogicalAssetID string         `json:"logical_asset_id"`
	SourceFile     string         `json:"source_file"`
	ContentHash    string         `json:"content_hash"`
}

func (q *Queries) ListAssetVersions(ctx context.Context, arg ListAssetVersionsParams) ([]ListAssetVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetVersions, arg.WorkspaceID, arg.Environment, arg.LogicalAssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetVersionsRow{}
	for rows.Next() {
		var i ListAssetVersionsRow
		if err := rows.Scan(
			&i.ServingStateID,
			&i.WorkspaceID,
			&i.Environment,
			&i.Status,
			&i.Digest,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.SnapshotID,
			&i.LogicalAssetID,
			&i.SourceFile,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByServingState = `-- name: ListAssetsByServingState :many
SELECT snapshot_id, logical_asset_id, workspace_id, serving_state_id, asset_type, asset_key, parent_logical_asset_id, title, description, payload_schema, payload_json, content_hash, created_at, source_file FROM assets WHERE serving_state_id = ? ORDER BY asset_type, asset_key
`

func (q *Queries) ListAssetsByServingState(ctx context.Context, servingStateID string) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsByServingState, servingStateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.SnapshotID,
			&i.LogicalAssetID,
			&i.WorkspaceID,
			&i.ServingStateID,
			&i.AssetType,
			&i.AssetKey,
			&i.ParentLogicalAssetID,
			&i.Title,
			&i.Description,
			&i.PayloadSchema,
			&i.PayloadJson,
			&i.ContentHash,
			&i.CreatedAt,
			&i.SourceFile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, title, description, created_at, updated_at FROM workspaces ORDER BY created_at
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesWithActiveMetadata = `-- name: ListWorkspacesWithActiveMetadata :many
SELECT
  w.id,
  CASE WHEN a.title IS NOT NULL AND a.title <> '' THEN a.title ELSE w.title END AS title,
  CASE WHEN a.description IS NOT NULL THEN a.description ELSE w.description END AS description,
  COALESCE(active.serving_state_id, '') AS active_serving_state_id,
  w.created_at,
  w.updated_at
FROM workspaces w
LEFT JOIN workspace_active_serving_states active
  ON active.workspace_id = w.id AND active.environment = ?
LEFT JOIN assets a
  ON a.serving_state_id = active.serving_state_id
 AND a.asset_type = 'catalog'
 AND a.logical_asset_id = 'catalog:' || w.id
ORDER BY w.created_at
`

type ListWorkspacesWithActiveMetadataRow struct {
	ID                   string      `json:"id"`
	Title                interface{} `json:"title"`
	Description          interface{} `json:"description"`
	ActiveServingStateID string      `json:"active_serving_state_id"`
	CreatedAt            string      `json:"created_at"`
	UpdatedAt            string      `json:"updated_at"`
}

func (q *Queries) ListWorkspacesWithActiveMetadata(ctx context.Context, environment string) ([]ListWorkspacesWithActiveMetadataRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesWithActiveMetadata, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesWithActiveMetadataRow{}
	for rows.Next() {
		var i ListWorkspacesWithActiveMetadataRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ActiveServingStateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkspace = `-- name: UpsertWorkspace :exec
INSERT INTO workspaces (id, title, description, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
  title = excluded.title,
  description = excluded.description,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertWorkspaceParams struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkspace, arg.ID, arg.Title, arg.Description)
	return err
}
