// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package idempotencydb

import (
	"context"
	"database/sql"
)

const abandonAPIIdempotencyRecord = `-- name: AbandonAPIIdempotencyRecord :execrows
DELETE FROM api_idempotency_records
WHERE scope = ? AND request_digest = ? AND owner_id = ? AND state = 'pending'
`

type AbandonAPIIdempotencyRecordParams struct {
	Scope         string `json:"scope"`
	RequestDigest string `json:"request_digest"`
	OwnerID       string `json:"owner_id"`
}

func (q *Queries) AbandonAPIIdempotencyRecord(ctx context.Context, arg AbandonAPIIdempotencyRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, abandonAPIIdempotencyRecord, arg.Scope, arg.RequestDigest, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeAPIIdempotencyRecord = `-- name: CompleteAPIIdempotencyRecord :execrows
UPDATE api_idempotency_records SET state = 'completed', response_status = ?, response_headers_json = ?,
  response_body = ?, updated_at = ?
WHERE scope = ? AND request_digest = ? AND owner_id = ? AND state = 'pending'
`

type CompleteAPIIdempotencyRecordParams struct {
	ResponseStatus      sql.NullInt64  `json:"response_status"`
	ResponseHeadersJson sql.NullString `json:"response_headers_json"`
	ResponseBody        []byte         `json:"response_body"`
	UpdatedAt           string         `json:"updated_at"`
	Scope               string         `json:"scope"`
	RequestDigest       string         `json:"request_digest"`
	OwnerID             string         `json:"owner_id"`
}

func (q *Queries) CompleteAPIIdempotencyRecord(ctx context.Context, arg CompleteAPIIdempotencyRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeAPIIdempotencyRecord,
		arg.ResponseStatus,
		arg.ResponseHeadersJson,
		arg.ResponseBody,
		arg.UpdatedAt,
		arg.Scope,
		arg.RequestDigest,
		arg.OwnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createAPIIdempotencyRecord = `-- name: CreateAPIIdempotencyRecord :execrows
INSERT INTO api_idempotency_records
  (scope, request_digest, state, owner_id, lease_expires_at, created_at, updated_at, expires_at)
VALUES (?, ?, 'pending', ?, ?, ?, ?, ?) ON CONFLICT(scope) DO NOTHING
`

type CreateAPIIdempotencyRecordParams struct {
	Scope          string `json:"scope"`
	RequestDigest  string `json:"request_digest"`
	OwnerID        string `json:"owner_id"`
	LeaseExpiresAt string `json:"lease_expires_at"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
	ExpiresAt      string `json:"expires_at"`
}

func (q *Queries) CreateAPIIdempotencyRecord(ctx context.Context, arg CreateAPIIdempotencyRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAPIIdempotencyRecord,
		arg.Scope,
		arg.RequestDigest,
		arg.OwnerID,
		arg.LeaseExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredAPIIdempotencyRecord = `-- name: DeleteExpiredAPIIdempotencyRecord :exec

DELETE FROM api_idempotency_records WHERE scope = ? AND expires_at <= ?
`

type DeleteExpiredAPIIdempotencyRecordParams struct {
	Scope     string `json:"scope"`
	ExpiresAt string `json:"expires_at"`
}

// Public API idempotency records and execution leases.
func (q *Queries) DeleteExpiredAPIIdempotencyRecord(ctx context.Context, arg DeleteExpiredAPIIdempotencyRecordParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAPIIdempotencyRecord, arg.Scope, arg.ExpiresAt)
	return err
}

const getAPIIdempotencyRecord = `-- name: GetAPIIdempotencyRecord :one
SELECT request_digest, state, owner_id, lease_expires_at, response_status,
  response_headers_json, response_body FROM api_idempotency_records WHERE scope = ?
`

type GetAPIIdempotencyRecordRow struct {
	RequestDigest       string         `json:"request_digest"`
	State               string         `json:"state"`
	OwnerID             string         `json:"owner_id"`
	LeaseExpiresAt      string         `json:"lease_expires_at"`
	ResponseStatus      sql.NullInt64  `json:"response_status"`
	ResponseHeadersJson sql.NullString `json:"response_headers_json"`
	ResponseBody        []byte         `json:"response_body"`
}

func (q *Queries) GetAPIIdempotencyRecord(ctx context.Context, scope string) (GetAPIIdempotencyRecordRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIIdempotencyRecord, scope)
	var i GetAPIIdempotencyRecordRow
	err := row.Scan(
		&i.RequestDigest,
		&i.State,
		&i.OwnerID,
		&i.LeaseExpiresAt,
		&i.ResponseStatus,
		&i.ResponseHeadersJson,
		&i.ResponseBody,
	)
	return i, err
}

const reclaimAPIIdempotencyRecord = `-- name: ReclaimAPIIdempotencyRecord :execrows
UPDATE api_idempotency_records SET owner_id = ?1,
  lease_expires_at = ?2, updated_at = ?3
WHERE scope = ?4 AND request_digest = ?5
  AND state = 'pending' AND lease_expires_at <= ?6
`

type ReclaimAPIIdempotencyRecordParams struct {
	OwnerID           string `json:"owner_id"`
	NewLeaseExpiresAt string `json:"new_lease_expires_at"`
	UpdatedAt         string `json:"updated_at"`
	Scope             string `json:"scope"`
	RequestDigest     string `json:"request_digest"`
	Now               string `json:"now"`
}

func (q *Queries) ReclaimAPIIdempotencyRecord(ctx context.Context, arg ReclaimAPIIdempotencyRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reclaimAPIIdempotencyRecord,
		arg.OwnerID,
		arg.NewLeaseExpiresAt,
		arg.UpdatedAt,
		arg.Scope,
		arg.RequestDigest,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renewAPIIdempotencyRecord = `-- name: RenewAPIIdempotencyRecord :execrows
UPDATE api_idempotency_records SET lease_expires_at = ?, updated_at = ?
WHERE scope = ? AND request_digest = ? AND owner_id = ? AND state = 'pending'
`

type RenewAPIIdempotencyRecordParams struct {
	LeaseExpiresAt string `json:"lease_expires_at"`
	UpdatedAt      string `json:"updated_at"`
	Scope          string `json:"scope"`
	RequestDigest  string `json:"request_digest"`
	OwnerID        string `json:"owner_id"`
}

func (q *Queries) RenewAPIIdempotencyRecord(ctx context.Context, arg RenewAPIIdempotencyRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewAPIIdempotencyRecord,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.Scope,
		arg.RequestDigest,
		arg.OwnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
