package main

import (
	"strings"
	"testing"
)

func TestGenerateAPIGenAuthorizationRegistry(t *testing.T) {
	ir := []byte(`{
		"endpoints": [
			{
				"operation_id": "zOperation",
				"extensions": {"x-authz": {"mode": "privilege", "privilege": "VIEW_ITEM"}}
			},
			{
				"operation_id": "aOperation",
				"extensions": {"x-authz": {"mode": "privilege", "privilege": "MANAGE_GRANTS"}}
			}
		]
	}`)

	generated, err := generateAPIGenAuthorizationRegistry(ir)
	if err != nil {
		t.Fatalf("generate authorization registry: %v", err)
	}
	text := string(generated)
	for _, want := range []string{
		"// Code generated by internal/tools/apigenpostprocess; DO NOT EDIT.",
		"package app",
		`"aOperation": access.Privilege("MANAGE_GRANTS")`,
		`"zOperation": access.Privilege("VIEW_ITEM")`,
	} {
		if !strings.Contains(text, want) {
			t.Errorf("generated registry missing %q:\n%s", want, text)
		}
	}
	if strings.Index(text, `"aOperation"`) > strings.Index(text, `"zOperation"`) {
		t.Fatalf("generated operations are not sorted:\n%s", text)
	}
}

func TestGenerateAPIGenAuthorizationRegistryRejectsInvalidContracts(t *testing.T) {
	tests := []struct {
		name      string
		endpoints string
		want      string
	}{
		{
			name:      "invalid document",
			endpoints: `not-json`,
			want:      "decode APIGen IR",
		},
		{
			name:      "no endpoints",
			endpoints: `[]`,
			want:      "contains no endpoints",
		},
		{
			name:      "missing operation id",
			endpoints: `[ {"extensions": {"x-authz": {"mode": "privilege", "privilege": "VIEW_ITEM"}}} ]`,
			want:      "missing operation_id",
		},
		{
			name:      "operation id whitespace",
			endpoints: `[ {"operation_id": " listThings", "extensions": {"x-authz": {"mode": "privilege", "privilege": "VIEW_ITEM"}}} ]`,
			want:      "contains surrounding whitespace",
		},
		{
			name:      "missing authorization",
			endpoints: `[ {"operation_id": "listThings", "extensions": {}} ]`,
			want:      "listThings: missing x-authz",
		},
		{
			name:      "malformed authorization",
			endpoints: `[ {"operation_id": "listThings", "extensions": {"x-authz": "privilege"}} ]`,
			want:      "listThings: decode x-authz",
		},
		{
			name:      "unsupported mode",
			endpoints: `[ {"operation_id": "listThings", "extensions": {"x-authz": {"mode": "public", "privilege": "VIEW_ITEM"}}} ]`,
			want:      `listThings: authorization mode "public"`,
		},
		{
			name:      "unknown privilege",
			endpoints: `[ {"operation_id": "listThings", "extensions": {"x-authz": {"mode": "privilege", "privilege": "SUPERUSER"}}} ]`,
			want:      `listThings: unknown privilege "SUPERUSER"`,
		},
		{
			name: "duplicate operation",
			endpoints: `[
				{"operation_id": "listThings", "extensions": {"x-authz": {"mode": "privilege", "privilege": "VIEW_ITEM"}}},
				{"operation_id": "listThings", "extensions": {"x-authz": {"mode": "privilege", "privilege": "VIEW_ITEM"}}}
			]`,
			want: "duplicate operation_id",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			_, err := generateAPIGenAuthorizationRegistry([]byte(`{"endpoints":` + test.endpoints + `}`))
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("error = %v, want containing %q", err, test.want)
			}
		})
	}
}
