package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"github.com/Yacobolo/libredash/internal/access"
)

type apiGenIR struct {
	Endpoints []apiGenEndpoint `json:"endpoints"`
}

type apiGenEndpoint struct {
	OperationID string                     `json:"operation_id"`
	Extensions  map[string]json.RawMessage `json:"extensions"`
}

type apiGenAuthorization struct {
	Mode      string `json:"mode"`
	Privilege string `json:"privilege"`
}

type apiGenOperationPrivilege struct {
	OperationID string
	Privilege   access.Privilege
}

func writeAPIGenAuthorizationRegistry(irPath, outputPath string) error {
	ir, err := os.ReadFile(irPath)
	if err != nil {
		return fmt.Errorf("read APIGen IR: %w", err)
	}
	generated, err := generateAPIGenAuthorizationRegistry(ir)
	if err != nil {
		return err
	}
	if err := os.WriteFile(outputPath, generated, 0o644); err != nil {
		return fmt.Errorf("write APIGen authorization registry: %w", err)
	}
	return nil
}

func generateAPIGenAuthorizationRegistry(ir []byte) ([]byte, error) {
	var document apiGenIR
	if err := json.Unmarshal(ir, &document); err != nil {
		return nil, fmt.Errorf("decode APIGen IR: %w", err)
	}
	if len(document.Endpoints) == 0 {
		return nil, fmt.Errorf("APIGen IR contains no endpoints")
	}

	knownPrivileges := make(map[access.Privilege]struct{})
	for _, privilege := range access.KnownPrivileges() {
		knownPrivileges[privilege] = struct{}{}
	}
	operations := make([]apiGenOperationPrivilege, 0, len(document.Endpoints))
	seen := make(map[string]struct{}, len(document.Endpoints))
	for index, endpoint := range document.Endpoints {
		operationID := strings.TrimSpace(endpoint.OperationID)
		if operationID == "" {
			return nil, fmt.Errorf("endpoint %d: missing operation_id", index)
		}
		if operationID != endpoint.OperationID {
			return nil, fmt.Errorf("endpoint %d: operation_id %q contains surrounding whitespace", index, endpoint.OperationID)
		}
		if _, duplicate := seen[operationID]; duplicate {
			return nil, fmt.Errorf("duplicate operation_id %q", operationID)
		}
		seen[operationID] = struct{}{}

		rawAuthz, ok := endpoint.Extensions["x-authz"]
		if !ok {
			return nil, fmt.Errorf("%s: missing x-authz", operationID)
		}
		var authz apiGenAuthorization
		if err := json.Unmarshal(rawAuthz, &authz); err != nil {
			return nil, fmt.Errorf("%s: decode x-authz: %w", operationID, err)
		}
		if authz.Mode != "privilege" {
			return nil, fmt.Errorf("%s: authorization mode %q is not supported", operationID, authz.Mode)
		}
		privilege := access.Privilege(authz.Privilege)
		if _, known := knownPrivileges[privilege]; !known {
			return nil, fmt.Errorf("%s: unknown privilege %q", operationID, authz.Privilege)
		}
		operations = append(operations, apiGenOperationPrivilege{OperationID: operationID, Privilege: privilege})
	}
	sort.Slice(operations, func(i, j int) bool {
		return operations[i].OperationID < operations[j].OperationID
	})

	var output strings.Builder
	output.WriteString("// Code generated by internal/tools/apigenpostprocess; DO NOT EDIT.\n\n")
	output.WriteString("package app\n\n")
	output.WriteString("import \"github.com/Yacobolo/libredash/internal/access\"\n\n")
	output.WriteString("var apigenOperationPrivileges = map[string]access.Privilege{\n")
	for _, operation := range operations {
		fmt.Fprintf(&output, "\t%q: access.Privilege(%q),\n", operation.OperationID, operation.Privilege)
	}
	output.WriteString("}\n")

	formatted, err := format.Source([]byte(output.String()))
	if err != nil {
		return nil, fmt.Errorf("format APIGen authorization registry: %w", err)
	}
	return formatted, nil
}
