// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: async_job.sql

package jobdb

import (
	"context"
)

const appendAPIAsyncEvent = `-- name: AppendAPIAsyncEvent :one
INSERT INTO api_async_events (resource_kind, resource_id, event_id, event_type, data_json)
SELECT ?1, ?2, COALESCE(MAX(event_id), 0) + 1,
  ?3, ?4
FROM api_async_events existing
WHERE existing.resource_kind = ?1 AND existing.resource_id = ?2
RETURNING event_id, resource_kind, resource_id, event_type, data_json, created_at
`

type AppendAPIAsyncEventParams struct {
	ResourceKind string `json:"resource_kind"`
	ResourceID   string `json:"resource_id"`
	EventType    string `json:"event_type"`
	DataJson     string `json:"data_json"`
}

type AppendAPIAsyncEventRow struct {
	EventID      int64  `json:"event_id"`
	ResourceKind string `json:"resource_kind"`
	ResourceID   string `json:"resource_id"`
	EventType    string `json:"event_type"`
	DataJson     string `json:"data_json"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) AppendAPIAsyncEvent(ctx context.Context, arg AppendAPIAsyncEventParams) (AppendAPIAsyncEventRow, error) {
	row := q.db.QueryRowContext(ctx, appendAPIAsyncEvent,
		arg.ResourceKind,
		arg.ResourceID,
		arg.EventType,
		arg.DataJson,
	)
	var i AppendAPIAsyncEventRow
	err := row.Scan(
		&i.EventID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.EventType,
		&i.DataJson,
		&i.CreatedAt,
	)
	return i, err
}

const appendAPIAsyncWorkflowEvent = `-- name: AppendAPIAsyncWorkflowEvent :one
INSERT INTO api_async_events (resource_kind, resource_id, event_id, event_type, data_json, event_key)
SELECT ?1, ?2, COALESCE(MAX(event_id), 0) + 1,
  ?3, ?4, ?5
FROM api_async_events existing
WHERE existing.resource_kind = ?1 AND existing.resource_id = ?2
ON CONFLICT(resource_kind, resource_id, event_key) WHERE event_key <> '' DO UPDATE SET event_key = excluded.event_key
RETURNING event_id, resource_kind, resource_id, event_type, data_json, created_at
`

type AppendAPIAsyncWorkflowEventParams struct {
	ResourceKind string `json:"resource_kind"`
	ResourceID   string `json:"resource_id"`
	EventType    string `json:"event_type"`
	DataJson     string `json:"data_json"`
	EventKey     string `json:"event_key"`
}

type AppendAPIAsyncWorkflowEventRow struct {
	EventID      int64  `json:"event_id"`
	ResourceKind string `json:"resource_kind"`
	ResourceID   string `json:"resource_id"`
	EventType    string `json:"event_type"`
	DataJson     string `json:"data_json"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) AppendAPIAsyncWorkflowEvent(ctx context.Context, arg AppendAPIAsyncWorkflowEventParams) (AppendAPIAsyncWorkflowEventRow, error) {
	row := q.db.QueryRowContext(ctx, appendAPIAsyncWorkflowEvent,
		arg.ResourceKind,
		arg.ResourceID,
		arg.EventType,
		arg.DataJson,
		arg.EventKey,
	)
	var i AppendAPIAsyncWorkflowEventRow
	err := row.Scan(
		&i.EventID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.EventType,
		&i.DataJson,
		&i.CreatedAt,
	)
	return i, err
}

const cancelClaimedAPIAsyncJob = `-- name: CancelClaimedAPIAsyncJob :execrows
UPDATE api_async_jobs SET status = 'cancelled', finished_at = CURRENT_TIMESTAMP,
  lease_owner = '', lease_expires_at = NULL
WHERE id = ?1 AND status = 'running' AND lease_owner = ?2
  AND lease_generation = ?3
`

type CancelClaimedAPIAsyncJobParams struct {
	ID              string `json:"id"`
	LeaseOwner      string `json:"lease_owner"`
	LeaseGeneration int64  `json:"lease_generation"`
}

func (q *Queries) CancelClaimedAPIAsyncJob(ctx context.Context, arg CancelClaimedAPIAsyncJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelClaimedAPIAsyncJob, arg.ID, arg.LeaseOwner, arg.LeaseGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelQueuedAPIAsyncJob = `-- name: CancelQueuedAPIAsyncJob :execrows
UPDATE api_async_jobs SET status = 'cancelled', finished_at = CURRENT_TIMESTAMP,
  lease_owner = '', lease_expires_at = NULL WHERE id = ? AND status = 'queued'
`

func (q *Queries) CancelQueuedAPIAsyncJob(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelQueuedAPIAsyncJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimAPIAsyncJobByID = `-- name: ClaimAPIAsyncJobByID :one
UPDATE api_async_jobs SET status = 'running', started_at = COALESCE(started_at, CURRENT_TIMESTAMP),
  lease_owner = ?1, lease_expires_at = datetime('now', ?2),
  attempt_count = attempt_count + 1, lease_generation = lease_generation + 1
WHERE id = ?3
  AND workload_class = ?4
  AND (status = 'queued' OR (status = 'running' AND lease_expires_at < CURRENT_TIMESTAMP))
RETURNING id, job_kind, workload_class, workspace_id, resource_kind, resource_id, payload_json, status, attempt_count, lease_owner, lease_generation,
  COALESCE(lease_expires_at, '') AS lease_expires_at, created_at, COALESCE(started_at, '') AS started_at,
  COALESCE(finished_at, '') AS finished_at, error_json
`

type ClaimAPIAsyncJobByIDParams struct {
	LeaseOwner    string      `json:"lease_owner"`
	LeaseModifier interface{} `json:"lease_modifier"`
	ID            string      `json:"id"`
	WorkloadClass string      `json:"workload_class"`
}

type ClaimAPIAsyncJobByIDRow struct {
	ID              string `json:"id"`
	JobKind         string `json:"job_kind"`
	WorkloadClass   string `json:"workload_class"`
	WorkspaceID     string `json:"workspace_id"`
	ResourceKind    string `json:"resource_kind"`
	ResourceID      string `json:"resource_id"`
	PayloadJson     string `json:"payload_json"`
	Status          string `json:"status"`
	AttemptCount    int64  `json:"attempt_count"`
	LeaseOwner      string `json:"lease_owner"`
	LeaseGeneration int64  `json:"lease_generation"`
	LeaseExpiresAt  string `json:"lease_expires_at"`
	CreatedAt       string `json:"created_at"`
	StartedAt       string `json:"started_at"`
	FinishedAt      string `json:"finished_at"`
	ErrorJson       string `json:"error_json"`
}

func (q *Queries) ClaimAPIAsyncJobByID(ctx context.Context, arg ClaimAPIAsyncJobByIDParams) (ClaimAPIAsyncJobByIDRow, error) {
	row := q.db.QueryRowContext(ctx, claimAPIAsyncJobByID,
		arg.LeaseOwner,
		arg.LeaseModifier,
		arg.ID,
		arg.WorkloadClass,
	)
	var i ClaimAPIAsyncJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.JobKind,
		&i.WorkloadClass,
		&i.WorkspaceID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.PayloadJson,
		&i.Status,
		&i.AttemptCount,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorJson,
	)
	return i, err
}

const completeAPIAsyncJob = `-- name: CompleteAPIAsyncJob :execrows
UPDATE api_async_jobs SET status = 'succeeded', finished_at = CURRENT_TIMESTAMP,
  lease_owner = '', lease_expires_at = NULL, error_json = '{}'
WHERE id = ?1 AND status = 'running' AND lease_owner = ?2
  AND lease_generation = ?3
`

type CompleteAPIAsyncJobParams struct {
	ID              string `json:"id"`
	LeaseOwner      string `json:"lease_owner"`
	LeaseGeneration int64  `json:"lease_generation"`
}

func (q *Queries) CompleteAPIAsyncJob(ctx context.Context, arg CompleteAPIAsyncJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeAPIAsyncJob, arg.ID, arg.LeaseOwner, arg.LeaseGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const enqueueAPIAsyncJob = `-- name: EnqueueAPIAsyncJob :exec

INSERT INTO api_async_jobs (id, job_kind, workload_class, workspace_id, resource_kind, resource_id, payload_json, request_digest, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'queued')
`

type EnqueueAPIAsyncJobParams struct {
	ID            string `json:"id"`
	JobKind       string `json:"job_kind"`
	WorkloadClass string `json:"workload_class"`
	WorkspaceID   string `json:"workspace_id"`
	ResourceKind  string `json:"resource_kind"`
	ResourceID    string `json:"resource_id"`
	PayloadJson   string `json:"payload_json"`
	RequestDigest string `json:"request_digest"`
}

// Shared API async jobs and events.
func (q *Queries) EnqueueAPIAsyncJob(ctx context.Context, arg EnqueueAPIAsyncJobParams) error {
	_, err := q.db.ExecContext(ctx, enqueueAPIAsyncJob,
		arg.ID,
		arg.JobKind,
		arg.WorkloadClass,
		arg.WorkspaceID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.PayloadJson,
		arg.RequestDigest,
	)
	return err
}

const failAPIAsyncJob = `-- name: FailAPIAsyncJob :execrows
UPDATE api_async_jobs SET status = 'failed', finished_at = CURRENT_TIMESTAMP,
  lease_owner = '', lease_expires_at = NULL, error_json = ?
WHERE id = ?2 AND status = 'running' AND lease_owner = ?3
  AND lease_generation = ?4
`

type FailAPIAsyncJobParams struct {
	ErrorJson       string `json:"error_json"`
	ID              string `json:"id"`
	LeaseOwner      string `json:"lease_owner"`
	LeaseGeneration int64  `json:"lease_generation"`
}

func (q *Queries) FailAPIAsyncJob(ctx context.Context, arg FailAPIAsyncJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failAPIAsyncJob,
		arg.ErrorJson,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAPIAsyncEvent = `-- name: GetAPIAsyncEvent :one
SELECT event_id, resource_kind, resource_id, event_type, data_json, created_at FROM api_async_events
WHERE resource_kind = ? AND resource_id = ? AND event_id = ?
`

type GetAPIAsyncEventParams struct {
	ResourceKind string `json:"resource_kind"`
	ResourceID   string `json:"resource_id"`
	EventID      int64  `json:"event_id"`
}

type GetAPIAsyncEventRow struct {
	EventID      int64  `json:"event_id"`
	ResourceKind string `json:"resource_kind"`
	ResourceID   string `json:"resource_id"`
	EventType    string `json:"event_type"`
	DataJson     string `json:"data_json"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) GetAPIAsyncEvent(ctx context.Context, arg GetAPIAsyncEventParams) (GetAPIAsyncEventRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIAsyncEvent, arg.ResourceKind, arg.ResourceID, arg.EventID)
	var i GetAPIAsyncEventRow
	err := row.Scan(
		&i.EventID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.EventType,
		&i.DataJson,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIAsyncJob = `-- name: GetAPIAsyncJob :one
SELECT id, job_kind, workload_class, workspace_id, resource_kind, resource_id, payload_json, status, attempt_count, lease_owner, lease_generation,
  COALESCE(lease_expires_at, '') AS lease_expires_at, created_at, COALESCE(started_at, '') AS started_at,
  COALESCE(finished_at, '') AS finished_at, error_json
FROM api_async_jobs WHERE id = ?
`

type GetAPIAsyncJobRow struct {
	ID              string `json:"id"`
	JobKind         string `json:"job_kind"`
	WorkloadClass   string `json:"workload_class"`
	WorkspaceID     string `json:"workspace_id"`
	ResourceKind    string `json:"resource_kind"`
	ResourceID      string `json:"resource_id"`
	PayloadJson     string `json:"payload_json"`
	Status          string `json:"status"`
	AttemptCount    int64  `json:"attempt_count"`
	LeaseOwner      string `json:"lease_owner"`
	LeaseGeneration int64  `json:"lease_generation"`
	LeaseExpiresAt  string `json:"lease_expires_at"`
	CreatedAt       string `json:"created_at"`
	StartedAt       string `json:"started_at"`
	FinishedAt      string `json:"finished_at"`
	ErrorJson       string `json:"error_json"`
}

func (q *Queries) GetAPIAsyncJob(ctx context.Context, id string) (GetAPIAsyncJobRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIAsyncJob, id)
	var i GetAPIAsyncJobRow
	err := row.Scan(
		&i.ID,
		&i.JobKind,
		&i.WorkloadClass,
		&i.WorkspaceID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.PayloadJson,
		&i.Status,
		&i.AttemptCount,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorJson,
	)
	return i, err
}

const getAPIAsyncJobDigest = `-- name: GetAPIAsyncJobDigest :one
SELECT request_digest FROM api_async_jobs WHERE id = ?
`

func (q *Queries) GetAPIAsyncJobDigest(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAPIAsyncJobDigest, id)
	var request_digest string
	err := row.Scan(&request_digest)
	return request_digest, err
}

const listAPIAsyncEvents = `-- name: ListAPIAsyncEvents :many
SELECT event_id, resource_kind, resource_id, event_type, data_json, created_at FROM api_async_events
WHERE resource_kind = ? AND resource_id = ? AND event_id > ? ORDER BY event_id LIMIT ?
`

type ListAPIAsyncEventsParams struct {
	ResourceKind string `json:"resource_kind"`
	ResourceID   string `json:"resource_id"`
	EventID      int64  `json:"event_id"`
	Limit        int64  `json:"limit"`
}

type ListAPIAsyncEventsRow struct {
	EventID      int64  `json:"event_id"`
	ResourceKind string `json:"resource_kind"`
	ResourceID   string `json:"resource_id"`
	EventType    string `json:"event_type"`
	DataJson     string `json:"data_json"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) ListAPIAsyncEvents(ctx context.Context, arg ListAPIAsyncEventsParams) ([]ListAPIAsyncEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIAsyncEvents,
		arg.ResourceKind,
		arg.ResourceID,
		arg.EventID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIAsyncEventsRow{}
	for rows.Next() {
		var i ListAPIAsyncEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.ResourceKind,
			&i.ResourceID,
			&i.EventType,
			&i.DataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIAsyncJobCandidates = `-- name: ListAPIAsyncJobCandidates :many
WITH eligible AS (
  SELECT id, job_kind, workload_class, workspace_id, resource_kind, resource_id, payload_json, status,
    attempt_count, lease_owner, lease_generation, COALESCE(lease_expires_at, '') AS lease_expires_at, created_at,
    COALESCE(started_at, '') AS started_at, COALESCE(finished_at, '') AS finished_at, error_json,
    ROW_NUMBER() OVER (PARTITION BY workspace_id ORDER BY created_at, id) AS workspace_position
  FROM api_async_jobs
  WHERE workload_class = ?2
    AND (status = 'queued' OR (status = 'running' AND lease_expires_at < CURRENT_TIMESTAMP))
)
SELECT id, job_kind, workload_class, workspace_id, resource_kind, resource_id, payload_json, status,
  attempt_count, lease_owner, lease_generation, lease_expires_at, created_at, started_at, finished_at, error_json
FROM eligible
WHERE workspace_position = 1
ORDER BY created_at, id
LIMIT ?1
`

type ListAPIAsyncJobCandidatesParams struct {
	ResultLimit   int64  `json:"result_limit"`
	WorkloadClass string `json:"workload_class"`
}

type ListAPIAsyncJobCandidatesRow struct {
	ID              string `json:"id"`
	JobKind         string `json:"job_kind"`
	WorkloadClass   string `json:"workload_class"`
	WorkspaceID     string `json:"workspace_id"`
	ResourceKind    string `json:"resource_kind"`
	ResourceID      string `json:"resource_id"`
	PayloadJson     string `json:"payload_json"`
	Status          string `json:"status"`
	AttemptCount    int64  `json:"attempt_count"`
	LeaseOwner      string `json:"lease_owner"`
	LeaseGeneration int64  `json:"lease_generation"`
	LeaseExpiresAt  string `json:"lease_expires_at"`
	CreatedAt       string `json:"created_at"`
	StartedAt       string `json:"started_at"`
	FinishedAt      string `json:"finished_at"`
	ErrorJson       string `json:"error_json"`
}

func (q *Queries) ListAPIAsyncJobCandidates(ctx context.Context, arg ListAPIAsyncJobCandidatesParams) ([]ListAPIAsyncJobCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIAsyncJobCandidates, arg.ResultLimit, arg.WorkloadClass)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIAsyncJobCandidatesRow{}
	for rows.Next() {
		var i ListAPIAsyncJobCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.JobKind,
			&i.WorkloadClass,
			&i.WorkspaceID,
			&i.ResourceKind,
			&i.ResourceID,
			&i.PayloadJson,
			&i.Status,
			&i.AttemptCount,
			&i.LeaseOwner,
			&i.LeaseGeneration,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewAPIAsyncJob = `-- name: RenewAPIAsyncJob :execrows
UPDATE api_async_jobs SET lease_expires_at = datetime('now', ?1)
WHERE id = ?2 AND status = 'running' AND lease_owner = ?3
  AND lease_generation = ?4
`

type RenewAPIAsyncJobParams struct {
	LeaseModifier   interface{} `json:"lease_modifier"`
	ID              string      `json:"id"`
	LeaseOwner      string      `json:"lease_owner"`
	LeaseGeneration int64       `json:"lease_generation"`
}

func (q *Queries) RenewAPIAsyncJob(ctx context.Context, arg RenewAPIAsyncJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewAPIAsyncJob,
		arg.LeaseModifier,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
