// Code generated by apigen data-contract Go emitter. DO NOT EDIT.
package signals

type AdminAgentSignal struct {
	CanWrite     bool                   `json:"canWrite"`
	Enabled      bool                   `json:"enabled"`
	Model        *string                `json:"model,omitempty"`
	SystemPrompt string                 `json:"systemPrompt"`
	Tools        []AdminAgentToolSignal `json:"tools"`
	UpdatePath   string                 `json:"updatePath"`
}

type AdminAgentToolSignal struct {
	Defaults     map[string]any `json:"defaults"`
	Description  string         `json:"description"`
	Effect       string         `json:"effect"`
	InputSchema  map[string]any `json:"inputSchema"`
	Name         string         `json:"name"`
	OutputSchema map[string]any `json:"outputSchema"`
}

type AdminContentSectionSignal struct {
	Facts *[]DefinitionFactSignal `json:"facts,omitempty"`
	Table *RecordTableSignal      `json:"table,omitempty"`
	Title string                  `json:"title"`
}

type AdminMetricSignal struct {
	Detail *string `json:"detail,omitempty"`
	Label  string  `json:"label"`
	Value  string  `json:"value"`
}

type AdminPageEnvelope struct {
	Chrome  ChromeSignal       `json:"chrome"`
	Page    AdminPageSignal    `json:"page"`
	Runtime RouteRuntimeSignal `json:"runtime"`
	Status  DashboardStatus    `json:"status"`
}

type AdminPageSignal struct {
	Active       string                       `json:"active"`
	Agent        *AdminAgentSignal            `json:"agent,omitempty"`
	Empty        *string                      `json:"empty,omitempty"`
	HeaderDetail string                       `json:"headerDetail"`
	HeaderTitle  string                       `json:"headerTitle"`
	Kind         RouteKind                    `json:"kind"`
	Metrics      *[]AdminMetricSignal         `json:"metrics,omitempty"`
	Sections     *[]AdminContentSectionSignal `json:"sections,omitempty"`
	Sidebar      SubSidebarSignal             `json:"sidebar"`
	Storage      *AdminStorageSignal          `json:"storage,omitempty"`
	Title        string                       `json:"title"`
}

type AdminQueryDetailSignal struct {
	CorrelationID *string `json:"correlationId,omitempty"`
	CreatedAt     *string `json:"createdAt,omitempty"`
	DurationMS    int64   `json:"durationMs"`
	Error         *string `json:"error,omitempty"`
	EventID       *string `json:"eventId,omitempty"`
	Loading       bool    `json:"loading"`
	ModelID       *string `json:"modelId,omitempty"`
	ObjectID      *string `json:"objectId,omitempty"`
	ObjectType    *string `json:"objectType,omitempty"`
	Operation     *string `json:"operation,omitempty"`
	PlanText      *string `json:"planText,omitempty"`
	PrincipalID   *string `json:"principalId,omitempty"`
	QueryError    *string `json:"queryError,omitempty"`
	QueryJSON     *string `json:"queryJson,omitempty"`
	QueryKind     *string `json:"queryKind,omitempty"`
	RequestID     *string `json:"requestId,omitempty"`
	RowsReturned  int64   `json:"rowsReturned"`
	SQL           *string `json:"sql,omitempty"`
	Status        *string `json:"status,omitempty"`
	StatusLabel   *string `json:"statusLabel,omitempty"`
	Surface       *string `json:"surface,omitempty"`
	Target        *string `json:"target,omitempty"`
	WorkspaceID   *string `json:"workspaceId,omitempty"`
}

type AdminQueryEventSignal struct {
	CorrelationID string `json:"correlationId"`
	CreatedAt     string `json:"createdAt"`
	DurationMS    int64  `json:"durationMs"`
	Error         string `json:"error"`
	ID            string `json:"id"`
	ModelID       string `json:"modelId"`
	ObjectID      string `json:"objectId"`
	ObjectType    string `json:"objectType"`
	Operation     string `json:"operation"`
	PlanText      string `json:"planText"`
	PrincipalID   string `json:"principalId"`
	QueryJSON     string `json:"queryJson"`
	QueryKind     string `json:"queryKind"`
	RequestID     string `json:"requestId"`
	RowsReturned  int64  `json:"rowsReturned"`
	SQL           string `json:"sql"`
	Status        string `json:"status"`
	Surface       string `json:"surface"`
	Target        string `json:"target"`
	WorkspaceID   string `json:"workspaceId"`
}

type AdminQueryHistoryCommand struct {
	Action     string                   `json:"action"`
	EventID    *string                  `json:"eventId,omitempty"`
	FilterMenu *FilterMenuCommand       `json:"filterMenu,omitempty"`
	Filters    AdminQueryHistoryFilters `json:"filters"`
	Limit      *int64                   `json:"limit,omitempty"`
	PageToken  *string                  `json:"pageToken,omitempty"`
}

type AdminQueryHistoryFilters struct {
	From       *string   `json:"from,omitempty"`
	Kinds      *[]string `json:"kinds,omitempty"`
	Principals *[]string `json:"principals,omitempty"`
	Search     *string   `json:"search,omitempty"`
	Statuses   *[]string `json:"statuses,omitempty"`
	Surfaces   *[]string `json:"surfaces,omitempty"`
	Target     *string   `json:"target,omitempty"`
	To         *string   `json:"to,omitempty"`
	Workspaces *[]string `json:"workspaces,omitempty"`
}

type AdminQueryHistorySignal struct {
	Error            string                   `json:"error"`
	FilterMenus      *[]FilterMenuSignal      `json:"filterMenus,omitempty"`
	Filters          AdminQueryHistoryFilters `json:"filters"`
	HasMore          bool                     `json:"hasMore"`
	Limit            int64                    `json:"limit"`
	LoadedCountLabel string                   `json:"loadedCountLabel"`
	Loading          bool                     `json:"loading"`
	NextCursor       string                   `json:"nextCursor"`
	Table            RecordTableSignal        `json:"table"`
}

type AdminStorageColumnSignal struct {
	BeginSnapshot       int64  `json:"beginSnapshot"`
	ContainsNaN         string `json:"containsNan"`
	ContainsNull        string `json:"containsNull"`
	Default             string `json:"default"`
	DefaultValueDialect string `json:"defaultValueDialect"`
	DefaultValueType    string `json:"defaultValueType"`
	ExtraStats          string `json:"extraStats"`
	ID                  int64  `json:"id"`
	InitialDefault      string `json:"initialDefault"`
	MaxValue            string `json:"maxValue"`
	MinValue            string `json:"minValue"`
	Name                string `json:"name"`
	Nullable            string `json:"nullable"`
	Ordinal             int64  `json:"ordinal"`
	Type                string `json:"type"`
}

type AdminStorageCommand struct {
	DatabaseID string `json:"databaseId"`
	Schema     string `json:"schema"`
	Table      string `json:"table"`
}

type AdminStorageFileSignal struct {
	BeginSnapshot    int64  `json:"beginSnapshot"`
	EndSnapshot      int64  `json:"endSnapshot"`
	Format           string `json:"format"`
	ID               int64  `json:"id"`
	Path             string `json:"path"`
	RecordCount      int64  `json:"recordCount"`
	RecordCountLabel string `json:"recordCountLabel"`
	SizeBytes        int64  `json:"sizeBytes"`
	SizeLabel        string `json:"sizeLabel"`
}

type AdminStorageServingStateSignal struct {
	ActivatedAt    string `json:"activatedAt"`
	Active         bool   `json:"active"`
	Digest         string `json:"digest"`
	Environment    string `json:"environment"`
	ServingStateID string `json:"servingStateId"`
	SnapshotID     int64  `json:"snapshotId"`
	Status         string `json:"status"`
	WorkspaceID    string `json:"workspaceId"`
}

type AdminStorageSignal struct {
	SelectedKey   string                           `json:"selectedKey"`
	SelectedTable *AdminStorageTableSignal         `json:"selectedTable,omitempty"`
	ServingStates []AdminStorageServingStateSignal `json:"servingStates"`
	Snapshots     []AdminStorageSnapshotSignal     `json:"snapshots"`
	Status        string                           `json:"status"`
	Summary       AdminStorageSummary              `json:"summary"`
	Tables        []AdminStorageTableSignal        `json:"tables"`
	Warnings      []string                         `json:"warnings"`
}

type AdminStorageSnapshotSignal struct {
	Author            string `json:"author"`
	Changes           string `json:"changes"`
	ExtraInfo         string `json:"extraInfo"`
	ID                int64  `json:"id"`
	Message           string `json:"message"`
	Protected         bool   `json:"protected"`
	SchemaVersion     int64  `json:"schemaVersion"`
	ServingStateCount int64  `json:"servingStateCount"`
	Time              string `json:"time"`
}

type AdminStorageSummary struct {
	CatalogPath        string `json:"catalogPath"`
	CatalogSizeLabel   string `json:"catalogSizeLabel"`
	DataFileCount      int64  `json:"dataFileCount"`
	DataPath           string `json:"dataPath"`
	DataSizeLabel      string `json:"dataSizeLabel"`
	DatabaseCount      int64  `json:"databaseCount"`
	SnapshotCount      int64  `json:"snapshotCount"`
	TableCount         int64  `json:"tableCount"`
	TotalDataSizeLabel string `json:"totalDataSizeLabel"`
	TotalSizeLabel     string `json:"totalSizeLabel"`
}

type AdminStorageTableHistorySignal struct {
	Author        string `json:"author"`
	Changes       string `json:"changes"`
	ExtraInfo     string `json:"extraInfo"`
	Message       string `json:"message"`
	SchemaVersion int64  `json:"schemaVersion"`
	SnapshotID    int64  `json:"snapshotId"`
	Source        string `json:"source"`
	Time          string `json:"time"`
}

type AdminStorageTableSignal struct {
	BeginSnapshot int64                             `json:"beginSnapshot"`
	ColumnCount   int64                             `json:"columnCount"`
	Columns       *[]AdminStorageColumnSignal       `json:"columns,omitempty"`
	DatabaseID    string                            `json:"databaseId"`
	DatabaseName  string                            `json:"databaseName"`
	DatabasePath  string                            `json:"databasePath"`
	DuckLakePath  string                            `json:"duckLakePath"`
	EndSnapshot   int64                             `json:"endSnapshot"`
	FileCount     int64                             `json:"fileCount"`
	Files         *[]AdminStorageFileSignal         `json:"files,omitempty"`
	History       *[]AdminStorageTableHistorySignal `json:"history,omitempty"`
	Key           string                            `json:"key"`
	ModelID       string                            `json:"modelId"`
	ModelName     string                            `json:"modelName"`
	Name          string                            `json:"name"`
	RowCount      int64                             `json:"rowCount"`
	RowCountLabel string                            `json:"rowCountLabel"`
	Schema        string                            `json:"schema"`
	ServingStates *[]AdminStorageServingStateSignal `json:"servingStates,omitempty"`
	SizeBytes     int64                             `json:"sizeBytes"`
	SizeLabel     string                            `json:"sizeLabel"`
	TableID       int64                             `json:"tableId"`
	TableUUID     string                            `json:"tableUuid"`
	Type          string                            `json:"type"`
}

type AssetLineageEdgeSignal struct {
	ID     string  `json:"id"`
	Kind   string  `json:"kind"`
	Label  *string `json:"label,omitempty"`
	Source string  `json:"source"`
	Target string  `json:"target"`
}

type AssetLineageGraphSignal struct {
	Edges []AssetLineageEdgeSignal `json:"edges"`
	Nodes []AssetLineageNodeSignal `json:"nodes"`
}

type AssetLineageNodeSignal struct {
	ContainedCount         *int64  `json:"containedCount,omitempty"`
	ContainedSummary       *string `json:"containedSummary,omitempty"`
	Href                   *string `json:"href,omitempty"`
	ID                     string  `json:"id"`
	Kind                   string  `json:"kind"`
	Label                  string  `json:"label"`
	Meta                   *string `json:"meta,omitempty"`
	Rank                   int64   `json:"rank"`
	Selected               *bool   `json:"selected,omitempty"`
	Side                   string  `json:"side"`
	UsedByCount            *int64  `json:"usedByCount,omitempty"`
	UsesCount              *int64  `json:"usesCount,omitempty"`
	VisibleDownstreamCount *int64  `json:"visibleDownstreamCount,omitempty"`
	VisibleUpstreamCount   *int64  `json:"visibleUpstreamCount,omitempty"`
}

type CatalogDashboardSignal struct {
	Description   *string   `json:"description,omitempty"`
	Href          string    `json:"href"`
	ID            string    `json:"id"`
	PageCount     int64     `json:"pageCount"`
	SemanticModel *string   `json:"semanticModel,omitempty"`
	Tags          *[]string `json:"tags,omitempty"`
	Title         string    `json:"title"`
}

type CatalogPageEnvelope struct {
	Chrome  ChromeSignal       `json:"chrome"`
	Page    CatalogPageSignal  `json:"page"`
	Runtime RouteRuntimeSignal `json:"runtime"`
	Status  DashboardStatus    `json:"status"`
}

type CatalogPageSignal struct {
	Dashboards  []CatalogDashboardSignal `json:"dashboards"`
	Description string                   `json:"description"`
	Kind        RouteKind                `json:"kind"`
	Title       string                   `json:"title"`
}

type ChatArtifactSignal struct {
	ID      string  `json:"id"`
	Kind    string  `json:"kind"`
	Summary *string `json:"summary,omitempty"`
}

type ChatConversationSummary struct {
	ArchivedAt      *string `json:"archivedAt,omitempty"`
	CreatedAt       string  `json:"createdAt"`
	ID              string  `json:"id"`
	LastMessageText *string `json:"lastMessageText,omitempty"`
	MessageCount    int64   `json:"messageCount"`
	PrincipalID     string  `json:"principalId"`
	Status          string  `json:"status"`
	Title           string  `json:"title"`
	TitlePending    *bool   `json:"titlePending,omitempty"`
	UpdatedAt       string  `json:"updatedAt"`
	WorkspaceID     string  `json:"workspaceId"`
}

type ChatEnvelope struct {
	Agent   ChatSignal                 `json:"agent"`
	Chrome  ChromeSignal               `json:"chrome"`
	Page    ChatPageSignal             `json:"page"`
	Runtime RouteRuntimeSignal         `json:"runtime"`
	Tables  map[string]DashboardTable  `json:"tables"`
	Visuals map[string]DashboardVisual `json:"visuals"`
}

type ChatPageSignal struct {
	Description string    `json:"description"`
	Kind        RouteKind `json:"kind"`
	Title       string    `json:"title"`
	View        string    `json:"view"`
}

type ChatSignal struct {
	ActiveConversationID string                     `json:"activeConversationId"`
	Composer             ComposerSignal             `json:"composer"`
	Conversations        []ChatConversationSummary  `json:"conversations"`
	Status               ChatStatus                 `json:"status"`
	Transcript           []ChatTranscriptItemSignal `json:"transcript"`
}

type ChatStatus struct {
	Enabled bool    `json:"enabled"`
	Error   *string `json:"error,omitempty"`
	Running bool    `json:"running"`
}

type ChatTranscriptItemSignal struct {
	ArgumentsJSON  *string             `json:"argumentsJson,omitempty"`
	Artifact       *ChatArtifactSignal `json:"artifact,omitempty"`
	ConversationID *string             `json:"conversationId,omitempty"`
	CreatedAt      *string             `json:"createdAt,omitempty"`
	Error          *string             `json:"error,omitempty"`
	ID             string              `json:"id"`
	InputFormat    *string             `json:"inputFormat,omitempty"`
	InputJSON      *string             `json:"inputJson,omitempty"`
	Kind           string              `json:"kind"`
	Markdown       *string             `json:"markdown,omitempty"`
	Name           *string             `json:"name,omitempty"`
	ResultFormat   *string             `json:"resultFormat,omitempty"`
	ResultJSON     *string             `json:"resultJson,omitempty"`
	ResultSummary  *string             `json:"resultSummary,omitempty"`
	RunID          *string             `json:"runId,omitempty"`
	Status         *string             `json:"status,omitempty"`
	Summary        *string             `json:"summary,omitempty"`
	Text           *string             `json:"text,omitempty"`
	Title          *string             `json:"title,omitempty"`
	ToolCallID     *string             `json:"toolCallId,omitempty"`
}

type ChromeSignal struct {
	Sidebar SidebarSignal `json:"sidebar"`
}

type ComposerSignal struct {
	Disabled    bool   `json:"disabled"`
	Placeholder string `json:"placeholder"`
	Value       string `json:"value"`
}

type ConnectionsPageEnvelope struct {
	Chrome  ChromeSignal          `json:"chrome"`
	Page    ConnectionsPageSignal `json:"page"`
	Runtime RouteRuntimeSignal    `json:"runtime"`
	Status  DashboardStatus       `json:"status"`
}

type ConnectionsPageSignal struct {
	AssetList   *WorkspaceAssetListSignal `json:"assetList,omitempty"`
	Description *string                   `json:"description,omitempty"`
	Environment *string                   `json:"environment,omitempty"`
	Kind        RouteKind                 `json:"kind"`
	Title       string                    `json:"title"`
	WorkspaceID *string                   `json:"workspaceId,omitempty"`
}

type DashboardComponentSignal struct {
	Badges      *[]string              `json:"badges,omitempty"`
	Description *string                `json:"description,omitempty"`
	Eyebrow     *string                `json:"eyebrow,omitempty"`
	Filter      *string                `json:"filter,omitempty"`
	Height      float64                `json:"height"`
	ID          string                 `json:"id"`
	Kind        string                 `json:"kind"`
	Placement   DashboardPagePlacement `json:"placement"`
	Subtitle    *string                `json:"subtitle,omitempty"`
	Table       *string                `json:"table,omitempty"`
	Title       *string                `json:"title,omitempty"`
	Visual      *string                `json:"visual,omitempty"`
	Width       float64                `json:"width"`
	X           float64                `json:"x"`
	Y           float64                `json:"y"`
}

type DashboardEnvelope struct {
	Chrome             ChromeSignal                       `json:"chrome"`
	FilterConfig       []ReportFilterConfig               `json:"filterConfig"`
	FilterOptions      map[string][]DashboardFilterOption `json:"filterOptions"`
	Filters            DashboardFilters                   `json:"filters"`
	InteractionCommand DashboardInteractionCommand        `json:"interactionCommand"`
	Page               DashboardPageSignal                `json:"page"`
	Runtime            RouteRuntimeSignal                 `json:"runtime"`
	Status             DashboardStatus                    `json:"status"`
	TableCommand       DashboardTableRequest              `json:"tableCommand"`
	Tables             map[string]DashboardTable          `json:"tables"`
	URLParamShape      map[string]any                     `json:"urlParamShape"`
	URLParams          map[string]any                     `json:"urlParams"`
	Visuals            map[string]DashboardVisual         `json:"visuals"`
}

type DashboardFilterControl struct {
	From     *string   `json:"from,omitempty"`
	Operator *string   `json:"operator,omitempty"`
	Preset   *string   `json:"preset,omitempty"`
	To       *string   `json:"to,omitempty"`
	Type     string    `json:"type"`
	Value    *string   `json:"value,omitempty"`
	Values   *[]string `json:"values,omitempty"`
}

type DashboardFilterOption struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

type DashboardFilters struct {
	Controls   map[string]DashboardFilterControl `json:"controls"`
	Selections []DashboardInteractionSelection   `json:"selections"`
}

type DashboardInteractionCommand struct {
	Action          string                               `json:"action"`
	InteractionKind string                               `json:"interactionKind"`
	Mappings        []DashboardInteractionCommandMapping `json:"mappings"`
	SourceID        string                               `json:"sourceId"`
	SourceKind      string                               `json:"sourceKind"`
	Toggle          bool                                 `json:"toggle"`
}

type DashboardInteractionCommandMapping struct {
	Field string  `json:"field"`
	Label *string `json:"label,omitempty"`
	Value string  `json:"value"`
}

type DashboardInteractionConfig struct {
	Kind     string                              `json:"kind"`
	Mappings []DashboardInteractionConfigMapping `json:"mappings"`
	Targets  *[]string                           `json:"targets,omitempty"`
	Toggle   bool                                `json:"toggle"`
}

type DashboardInteractionConfigMapping struct {
	Field string  `json:"field"`
	Label *string `json:"label,omitempty"`
	Value string  `json:"value"`
}

type DashboardInteractionSelection struct {
	Entries         []DashboardInteractionSelectionEntry `json:"entries"`
	ID              string                               `json:"id"`
	InteractionKind string                               `json:"interactionKind"`
	Label           string                               `json:"label"`
	Order           int64                                `json:"order"`
	SourceID        string                               `json:"sourceId"`
	SourceKind      string                               `json:"sourceKind"`
}

type DashboardInteractionSelectionEntry struct {
	Label    *string                                `json:"label,omitempty"`
	Mappings []DashboardInteractionSelectionMapping `json:"mappings"`
}

type DashboardInteractionSelectionMapping struct {
	Field string  `json:"field"`
	Label *string `json:"label,omitempty"`
	Value string  `json:"value"`
}

type DashboardPageCanvas struct {
	Height int64 `json:"height"`
	Width  int64 `json:"width"`
}

type DashboardPageGrid struct {
	Columns   int64 `json:"columns"`
	Gap       int64 `json:"gap"`
	Padding   int64 `json:"padding"`
	RowHeight int64 `json:"rowHeight"`
}

type DashboardPageNavSignal struct {
	Active bool   `json:"active"`
	Href   string `json:"href"`
	ID     string `json:"id"`
	Title  string `json:"title"`
}

type DashboardPagePlacement struct {
	Col     int64 `json:"col"`
	ColSpan int64 `json:"colSpan"`
	Row     int64 `json:"row"`
	RowSpan int64 `json:"rowSpan"`
}

type DashboardPageSignal struct {
	Canvas         DashboardPageCanvas        `json:"canvas"`
	Components     []DashboardComponentSignal `json:"components"`
	DashboardID    string                     `json:"dashboardId"`
	DashboardTitle string                     `json:"dashboardTitle"`
	Description    *string                    `json:"description,omitempty"`
	Grid           DashboardPageGrid          `json:"grid"`
	HeaderDetail   string                     `json:"headerDetail"`
	Kind           RouteKind                  `json:"kind"`
	ModelID        string                     `json:"modelId"`
	ModelTitle     string                     `json:"modelTitle"`
	PageID         string                     `json:"pageId"`
	PageTitle      string                     `json:"pageTitle"`
	Pages          []DashboardPageNavSignal   `json:"pages"`
	Title          string                     `json:"title"`
}

type DashboardStatus struct {
	DataDirectory string `json:"dataDirectory"`
	Error         string `json:"error"`
	LastUpdated   string `json:"lastUpdated"`
	Loading       bool   `json:"loading"`
	SetupRequired bool   `json:"setupRequired"`
}

type DashboardTable struct {
	AvailableRows int64                                `json:"availableRows"`
	Blocks        map[string]DashboardTableBlock       `json:"blocks"`
	ChunkSize     int64                                `json:"chunkSize"`
	Columns       []DashboardTableColumn               `json:"columns"`
	Error         string                               `json:"error"`
	Interaction   DashboardInteractionConfig           `json:"interaction"`
	IsCapped      bool                                 `json:"isCapped"`
	Kind          string                               `json:"kind"`
	LoadingBlock  string                               `json:"loadingBlock"`
	ResetVersion  int64                                `json:"resetVersion"`
	RowCap        int64                                `json:"rowCap"`
	RowHeight     int64                                `json:"rowHeight"`
	Selection     []DashboardInteractionSelectionEntry `json:"selection"`
	Sort          DashboardTableSort                   `json:"sort"`
	Style         DashboardTableStyle                  `json:"style"`
	Title         string                               `json:"title"`
	TotalRows     int64                                `json:"totalRows"`
	Version       int64                                `json:"version"`
}

type DashboardTableBlock struct {
	RequestSeq   int64              `json:"requestSeq"`
	ResetVersion int64              `json:"resetVersion"`
	Rows         []map[string]any   `json:"rows"`
	Sort         DashboardTableSort `json:"sort"`
	Start        int64              `json:"start"`
}

type DashboardTableColumn struct {
	Align       *string                         `json:"align,omitempty"`
	ColumnValue *string                         `json:"columnValue,omitempty"`
	Format      *string                         `json:"format,omitempty"`
	Formatting  *[]DashboardTableFormattingRule `json:"formatting,omitempty"`
	Group       *string                         `json:"group,omitempty"`
	Key         string                          `json:"key"`
	Label       string                          `json:"label"`
	Measure     *string                         `json:"measure,omitempty"`
	Role        *string                         `json:"role,omitempty"`
	Width       *int64                          `json:"width,omitempty"`
}

type DashboardTableFormattingRule struct {
	Background *string            `json:"background,omitempty"`
	Color      *string            `json:"color,omitempty"`
	HighColor  *string            `json:"highColor,omitempty"`
	Kind       string             `json:"kind"`
	LowColor   *string            `json:"lowColor,omitempty"`
	Max        *float64           `json:"max,omitempty"`
	Min        *float64           `json:"min,omitempty"`
	Values     *map[string]string `json:"values,omitempty"`
}

type DashboardTableRequest struct {
	Block        string             `json:"block"`
	Count        int64              `json:"count"`
	RequestSeq   int64              `json:"requestSeq"`
	ResetVersion int64              `json:"resetVersion"`
	Sort         DashboardTableSort `json:"sort"`
	Start        int64              `json:"start"`
	Table        string             `json:"table"`
}

type DashboardTableSort struct {
	Direction string `json:"direction"`
	Key       string `json:"key"`
}

type DashboardTableStyle struct {
	Density string `json:"density"`
	Grid    string `json:"grid"`
	Zebra   bool   `json:"zebra"`
}

type DashboardVisual struct {
	Data            []map[string]any                     `json:"data"`
	Dimensions      []string                             `json:"dimensions"`
	Format          *string                              `json:"format,omitempty"`
	ID              string                               `json:"id"`
	Interaction     DashboardInteractionConfig           `json:"interaction"`
	Kind            string                               `json:"kind"`
	Measure         string                               `json:"measure"`
	Measures        []string                             `json:"measures"`
	Options         map[string]any                       `json:"options"`
	Renderer        string                               `json:"renderer"`
	RendererOptions map[string]map[string]any            `json:"rendererOptions"`
	Selection       []DashboardInteractionSelectionEntry `json:"selection"`
	Series          []string                             `json:"series"`
	Shape           string                               `json:"shape"`
	Title           string                               `json:"title"`
	Type            string                               `json:"type"`
	Unit            string                               `json:"unit"`
	Version         int64                                `json:"version"`
}

type DataExplorerCommand struct {
	Block          *string               `json:"block,omitempty"`
	ColumnWidths   *map[string]float64   `json:"columnWidths,omitempty"`
	Count          int64                 `json:"count"`
	Limit          int64                 `json:"limit"`
	ObjectKey      *string               `json:"objectKey,omitempty"`
	Offset         int64                 `json:"offset"`
	RequestSeq     int64                 `json:"requestSeq"`
	ResetVersion   int64                 `json:"resetVersion"`
	Sort           DataPreviewSortSignal `json:"sort"`
	Start          int64                 `json:"start"`
	VisibleColumns *[]string             `json:"visibleColumns,omitempty"`
	WorkspaceID    *string               `json:"workspaceId,omitempty"`
}

type DataExplorerObjectSignal struct {
	AssetID        *string                    `json:"assetId,omitempty"`
	ColumnCount    int64                      `json:"columnCount"`
	Columns        *[]DataPreviewColumnSignal `json:"columns,omitempty"`
	Description    *string                    `json:"description,omitempty"`
	DetailHref     *string                    `json:"detailHref,omitempty"`
	Key            string                     `json:"key"`
	Layer          string                     `json:"layer"`
	ModelID        *string                    `json:"modelId,omitempty"`
	RowCountLabel  *string                    `json:"rowCountLabel,omitempty"`
	Source         *string                    `json:"source,omitempty"`
	Table          *string                    `json:"table,omitempty"`
	Title          string                     `json:"title"`
	WorkspaceID    string                     `json:"workspaceId"`
	WorkspaceTitle *string                    `json:"workspaceTitle,omitempty"`
}

type DataExplorerPageEnvelope struct {
	Chrome       ChromeSignal           `json:"chrome"`
	DataExplorer DataExplorerSignal     `json:"dataExplorer"`
	Page         DataExplorerPageSignal `json:"page"`
	Runtime      RouteRuntimeSignal     `json:"runtime"`
	Status       DashboardStatus        `json:"status"`
}

type DataExplorerPageSignal struct {
	Description         *string                       `json:"description,omitempty"`
	Kind                RouteKind                     `json:"kind"`
	SelectedObject      *string                       `json:"selectedObject,omitempty"`
	SelectedWorkspaceID *string                       `json:"selectedWorkspaceId,omitempty"`
	Tabs                []WorkspaceTabSignal          `json:"tabs"`
	Title               string                        `json:"title"`
	WorkspaceID         *string                       `json:"workspaceId,omitempty"`
	Workspaces          []DataExplorerWorkspaceSignal `json:"workspaces"`
}

type DataExplorerSignal struct {
	Command             DataExplorerCommand        `json:"command"`
	Objects             []DataExplorerObjectSignal `json:"objects"`
	Preview             DataPreviewSignal          `json:"preview"`
	SelectedKey         *string                    `json:"selectedKey,omitempty"`
	SelectedObject      *DataExplorerObjectSignal  `json:"selectedObject,omitempty"`
	SelectedWorkspaceID *string                    `json:"selectedWorkspaceId,omitempty"`
	Warnings            *[]string                  `json:"warnings,omitempty"`
}

type DataExplorerWorkspaceSignal struct {
	Active      bool   `json:"active"`
	Href        string `json:"href"`
	ID          string `json:"id"`
	ObjectCount int64  `json:"objectCount"`
	Title       string `json:"title"`
}

type DataPreviewBlockSignal struct {
	RequestSeq   int64                 `json:"requestSeq"`
	ResetVersion int64                 `json:"resetVersion"`
	Rows         []map[string]any      `json:"rows"`
	Sort         DataPreviewSortSignal `json:"sort"`
	Start        int64                 `json:"start"`
}

type DataPreviewColumnSignal struct {
	Key   string  `json:"key"`
	Label string  `json:"label"`
	Type  *string `json:"type,omitempty"`
}

type DataPreviewSignal struct {
	AvailableRows int64                             `json:"availableRows"`
	Blocks        map[string]DataPreviewBlockSignal `json:"blocks"`
	ChunkSize     int64                             `json:"chunkSize"`
	Columns       []DataPreviewColumnSignal         `json:"columns"`
	Error         *string                           `json:"error,omitempty"`
	LoadingBlock  *string                           `json:"loadingBlock,omitempty"`
	ResetVersion  int64                             `json:"resetVersion"`
	RowHeight     int64                             `json:"rowHeight"`
	Sort          DataPreviewSortSignal             `json:"sort"`
	SQL           *string                           `json:"sql,omitempty"`
	TotalRowLabel *string                           `json:"totalRowLabel,omitempty"`
	TotalRows     int64                             `json:"totalRows"`
}

type DataPreviewSortSignal struct {
	Column    *string `json:"column,omitempty"`
	Direction *string `json:"direction,omitempty"`
}

type DefinitionFactSignal struct {
	Code  *bool  `json:"code,omitempty"`
	Label string `json:"label"`
	Value string `json:"value"`
	Wide  *bool  `json:"wide,omitempty"`
}

type FilterMenuCommand struct {
	Action   *string   `json:"action,omitempty"`
	MenuID   *string   `json:"menuId,omitempty"`
	Search   *string   `json:"search,omitempty"`
	Selected *[]string `json:"selected,omitempty"`
	Value    *string   `json:"value,omitempty"`
}

type FilterMenuOptionSignal struct {
	CountLabel  *string `json:"countLabel,omitempty"`
	Description *string `json:"description,omitempty"`
	Disabled    bool    `json:"disabled"`
	Icon        *string `json:"icon,omitempty"`
	Label       string  `json:"label"`
	Selected    bool    `json:"selected"`
	Value       string  `json:"value"`
}

type FilterMenuSignal struct {
	EmptyLabel   *string                   `json:"emptyLabel,omitempty"`
	Error        *string                   `json:"error,omitempty"`
	ID           string                    `json:"id"`
	Label        string                    `json:"label"`
	Loading      bool                      `json:"loading"`
	Mode         *string                   `json:"mode,omitempty"`
	Options      *[]FilterMenuOptionSignal `json:"options,omitempty"`
	Placeholder  *string                   `json:"placeholder,omitempty"`
	Search       *string                   `json:"search,omitempty"`
	Selected     *[]string                 `json:"selected,omitempty"`
	SummaryLabel *string                   `json:"summaryLabel,omitempty"`
}

type LoginPageEnvelope struct {
	Page    LoginPageSignal    `json:"page"`
	Runtime RouteRuntimeSignal `json:"runtime"`
	Status  DashboardStatus    `json:"status"`
}

type LoginPageSignal struct {
	BackgroundModuleSrc string    `json:"backgroundModuleSrc"`
	Kind                RouteKind `json:"kind"`
	LocalAuth           bool      `json:"localAuth"`
	MustChangePassword  bool      `json:"mustChangePassword"`
	ProviderLabel       string    `json:"providerLabel"`
	SSOAuth             bool      `json:"ssoAuth"`
	Title               string    `json:"title"`
}

type RecordTableBadgeSignal struct {
	Label string  `json:"label"`
	Tone  *string `json:"tone,omitempty"`
}

type RecordTableColumnSelector struct {
	DefaultColumns *[]string `json:"defaultColumns,omitempty"`
	Enabled        bool      `json:"enabled"`
	Label          *string   `json:"label,omitempty"`
	StorageKey     *string   `json:"storageKey,omitempty"`
}

type RecordTableColumnSignal struct {
	Align      *string `json:"align,omitempty"`
	Header     string  `json:"header"`
	HrefKey    *string `json:"hrefKey,omitempty"`
	ID         string  `json:"id"`
	Kind       *string `json:"kind,omitempty"`
	Toggleable *bool   `json:"toggleable,omitempty"`
	Width      *string `json:"width,omitempty"`
}

type RecordTableSignal struct {
	ColumnSelector *RecordTableColumnSelector `json:"columnSelector,omitempty"`
	Columns        []RecordTableColumnSignal  `json:"columns"`
	Density        *string                    `json:"density,omitempty"`
	Empty          string                     `json:"empty"`
	MinWidth       *string                    `json:"minWidth,omitempty"`
	RowAction      *string                    `json:"rowAction,omitempty"`
	Rows           []map[string]any           `json:"rows"`
}

type ReportFilterConfig struct {
	Custom           *bool                 `json:"custom,omitempty"`
	Default          ReportFilterDefault   `json:"default"`
	DefaultOperator  *string               `json:"defaultOperator,omitempty"`
	Description      *string               `json:"description,omitempty"`
	Dimension        string                `json:"dimension"`
	FromURLParam     *string               `json:"fromURLParam,omitempty"`
	ID               string                `json:"id"`
	Label            string                `json:"label"`
	Operator         *string               `json:"operator,omitempty"`
	OperatorURLParam *string               `json:"operatorURLParam,omitempty"`
	Operators        *[]string             `json:"operators,omitempty"`
	Options          *[]ReportFilterOption `json:"options,omitempty"`
	Presets          *[]ReportFilterPreset `json:"presets,omitempty"`
	Targets          *ReportFilterTargets  `json:"targets,omitempty"`
	ToURLParam       *string               `json:"toURLParam,omitempty"`
	Type             string                `json:"type"`
	URLParam         *string               `json:"urlParam,omitempty"`
	Values           *ReportFilterValues   `json:"values,omitempty"`
}

type ReportFilterDefault struct {
	From     *string   `json:"from,omitempty"`
	Operator *string   `json:"operator,omitempty"`
	Preset   *string   `json:"preset,omitempty"`
	To       *string   `json:"to,omitempty"`
	Value    *string   `json:"value,omitempty"`
	Values   *[]string `json:"values,omitempty"`
}

type ReportFilterOption struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

type ReportFilterPreset struct {
	From         *string `json:"from,omitempty"`
	Label        string  `json:"label"`
	RelativeDays *int64  `json:"relativeDays,omitempty"`
	To           *string `json:"to,omitempty"`
	Value        string  `json:"value"`
}

type ReportFilterTargets struct {
	Tables  *[]string `json:"tables,omitempty"`
	Visuals *[]string `json:"visuals,omitempty"`
}

type ReportFilterValues struct {
	Limit  *int64  `json:"limit,omitempty"`
	Source *string `json:"source,omitempty"`
}

type RouteKind string

const (
	RouteKindDashboard       RouteKind = "dashboard"
	RouteKindCatalog         RouteKind = "catalog"
	RouteKindChat            RouteKind = "chat"
	RouteKindWorkspace       RouteKind = "workspace"
	RouteKindWorkspaceAsset  RouteKind = "workspace_asset"
	RouteKindConnections     RouteKind = "connections"
	RouteKindConnectionAsset RouteKind = "connection_asset"
	RouteKindData            RouteKind = "data"
	RouteKindAdmin           RouteKind = "admin"
	RouteKindLogin           RouteKind = "login"
)

type RouteRuntimeSignal struct {
	ClientID    *string   `json:"clientId,omitempty"`
	DashboardID *string   `json:"dashboardId,omitempty"`
	Kind        RouteKind `json:"kind"`
	ModelID     *string   `json:"modelId,omitempty"`
	PageID      *string   `json:"pageId,omitempty"`
	WorkspaceID *string   `json:"workspaceId,omitempty"`
}

type SemanticModelGraphEdgeSignal struct {
	Active      bool   `json:"active"`
	Cardinality string `json:"cardinality"`
	ID          string `json:"id"`
	Label       string `json:"label"`
	Source      string `json:"source"`
	SourceField string `json:"sourceField"`
	Target      string `json:"target"`
	TargetField string `json:"targetField"`
}

type SemanticModelGraphFieldSignal struct {
	Join          *bool     `json:"join,omitempty"`
	Label         *string   `json:"label,omitempty"`
	Name          string    `json:"name"`
	PrimaryKey    *bool     `json:"primaryKey,omitempty"`
	Relationships *[]string `json:"relationships,omitempty"`
	Type          *string   `json:"type,omitempty"`
}

type SemanticModelGraphNodeSignal struct {
	Description *string                         `json:"description,omitempty"`
	Fields      []SemanticModelGraphFieldSignal `json:"fields"`
	ID          string                          `json:"id"`
	PrimaryKey  *string                         `json:"primaryKey,omitempty"`
	Title       string                          `json:"title"`
}

type SemanticModelGraphSignal struct {
	BaseTable *string                        `json:"baseTable,omitempty"`
	Edges     []SemanticModelGraphEdgeSignal `json:"edges"`
	Nodes     []SemanticModelGraphNodeSignal `json:"nodes"`
}

type SidebarActionSignal struct {
	Href  string `json:"href"`
	Icon  string `json:"icon"`
	Label string `json:"label"`
}

type SidebarGroupSignal struct {
	Items []SidebarItemSignal `json:"items"`
	Label string              `json:"label"`
}

type SidebarHistoryItemSignal struct {
	Active  bool   `json:"active"`
	Href    string `json:"href"`
	ID      string `json:"id"`
	Pending *bool  `json:"pending,omitempty"`
	Title   string `json:"title"`
}

type SidebarHistorySignal struct {
	EmptyText *string                    `json:"emptyText,omitempty"`
	Items     []SidebarHistoryItemSignal `json:"items"`
	Label     string                     `json:"label"`
}

type SidebarItemSignal struct {
	Active *bool   `json:"active,omitempty"`
	Href   string  `json:"href"`
	Icon   string  `json:"icon"`
	ID     string  `json:"id"`
	Label  string  `json:"label"`
	Meta   *string `json:"meta,omitempty"`
}

type SidebarSignal struct {
	Active         string                `json:"active"`
	Compact        bool                  `json:"compact"`
	DashboardID    *string               `json:"dashboardId,omitempty"`
	DashboardTitle string                `json:"dashboardTitle"`
	Groups         []SidebarGroupSignal  `json:"groups"`
	History        *SidebarHistorySignal `json:"history,omitempty"`
	ModelID        *string               `json:"modelId,omitempty"`
	ModelTitle     *string               `json:"modelTitle,omitempty"`
	PageTitle      string                `json:"pageTitle"`
	PrimaryAction  *SidebarActionSignal  `json:"primaryAction,omitempty"`
	UserRole       *string               `json:"userRole,omitempty"`
	WorkspaceTitle string                `json:"workspaceTitle"`
}

type SubSidebarItemSignal struct {
	Active  bool   `json:"active"`
	Href    string `json:"href"`
	ID      string `json:"id"`
	Pending *bool  `json:"pending,omitempty"`
	Title   string `json:"title"`
}

type SubSidebarSignal struct {
	ActiveID    string                 `json:"activeId"`
	AriaLabel   string                 `json:"ariaLabel"`
	Collapsible bool                   `json:"collapsible"`
	Disabled    *bool                  `json:"disabled,omitempty"`
	EmptyText   *string                `json:"emptyText,omitempty"`
	Items       []SubSidebarItemSignal `json:"items"`
	Label       string                 `json:"label"`
	Numbered    bool                   `json:"numbered"`
	RailLabel   string                 `json:"railLabel"`
	StorageKey  string                 `json:"storageKey"`
}

type WorkspaceAccessCommand struct {
	BindingID   string `json:"bindingId"`
	Email       string `json:"email"`
	PrincipalID string `json:"principalId"`
	Privilege   string `json:"privilege"`
	Role        string `json:"role"`
	SubjectID   string `json:"subjectId"`
	SubjectType string `json:"subjectType"`
}

type WorkspaceAccessSignal struct {
	Bindings    []any                  `json:"bindings"`
	CanManage   bool                   `json:"canManage"`
	Command     WorkspaceAccessCommand `json:"command"`
	Mode        *string                `json:"mode,omitempty"`
	ObjectID    *string                `json:"objectId,omitempty"`
	ObjectTitle *string                `json:"objectTitle,omitempty"`
	ObjectType  *string                `json:"objectType,omitempty"`
	Roles       []any                  `json:"roles"`
	Search      string                 `json:"search"`
	Status      WorkspaceAccessStatus  `json:"status"`
	Workspace   any                    `json:"workspace"`
}

type WorkspaceAccessStatus struct {
	Error   string `json:"error"`
	Loading bool   `json:"loading"`
	Message string `json:"message"`
}

type WorkspaceActionSignal struct {
	Command  *string `json:"command,omitempty"`
	Disabled *bool   `json:"disabled,omitempty"`
	Href     *string `json:"href,omitempty"`
	Icon     *string `json:"icon,omitempty"`
	Label    string  `json:"label"`
}

type WorkspaceAssetDetailsSignal struct {
	Overview           []DefinitionFactSignal         `json:"overview"`
	Sections           []WorkspaceDetailSectionSignal `json:"sections"`
	SemanticModelGraph *SemanticModelGraphSignal      `json:"semanticModelGraph,omitempty"`
}

type WorkspaceAssetLineageSignal struct {
	Count       int64                   `json:"count"`
	Graph       AssetLineageGraphSignal `json:"graph"`
	UsedByTable RecordTableSignal       `json:"usedByTable"`
	UsesTable   RecordTableSignal       `json:"usesTable"`
}

type WorkspaceAssetListSignal struct {
	ActiveType  *string                       `json:"activeType,omitempty"`
	Assets      []WorkspaceAssetSummarySignal `json:"assets"`
	Empty       string                        `json:"empty"`
	Query       *string                       `json:"query,omitempty"`
	SearchHref  string                        `json:"searchHref"`
	Tabs        []WorkspaceTabSignal          `json:"tabs"`
	WorkspaceID *string                       `json:"workspaceId,omitempty"`
}

type WorkspaceAssetPageEnvelope struct {
	Chrome  ChromeSignal             `json:"chrome"`
	Page    WorkspaceAssetPageSignal `json:"page"`
	Runtime RouteRuntimeSignal       `json:"runtime"`
	Status  DashboardStatus          `json:"status"`
}

type WorkspaceAssetPageSignal struct {
	Actions       *[]WorkspaceActionSignal      `json:"actions,omitempty"`
	ActiveSection string                        `json:"activeSection"`
	Asset         WorkspaceAssetSummarySignal   `json:"asset"`
	AssetID       string                        `json:"assetId"`
	Breadcrumbs   []WorkspaceBreadcrumbSignal   `json:"breadcrumbs"`
	Details       *WorkspaceAssetDetailsSignal  `json:"details,omitempty"`
	Environment   *string                       `json:"environment,omitempty"`
	Kind          RouteKind                     `json:"kind"`
	Lineage       *WorkspaceAssetLineageSignal  `json:"lineage,omitempty"`
	Refresh       *WorkspaceAssetRefreshSignal  `json:"refresh,omitempty"`
	Tabs          []WorkspaceTabSignal          `json:"tabs"`
	Title         string                        `json:"title"`
	Versions      *WorkspaceAssetVersionsSignal `json:"versions,omitempty"`
	WorkspaceID   string                        `json:"workspaceId"`
}

type WorkspaceAssetRefreshSignal struct {
	LastSuccessful string             `json:"lastSuccessful"`
	Running        bool               `json:"running"`
	RunsTable      *RecordTableSignal `json:"runsTable,omitempty"`
	Status         string             `json:"status"`
}

type WorkspaceAssetSummarySignal struct {
	Description *string `json:"description,omitempty"`
	DetailHref  string  `json:"detailHref"`
	ID          string  `json:"id"`
	Key         string  `json:"key"`
	OpenHref    string  `json:"openHref"`
	ParentHref  *string `json:"parentHref,omitempty"`
	ParentTitle *string `json:"parentTitle,omitempty"`
	Title       string  `json:"title"`
	Type        string  `json:"type"`
	TypeLabel   string  `json:"typeLabel"`
}

type WorkspaceAssetVersionsSignal struct {
	CurrentContentHash string            `json:"currentContentHash"`
	Table              RecordTableSignal `json:"table"`
}

type WorkspaceBreadcrumbSignal struct {
	Current *bool   `json:"current,omitempty"`
	Href    *string `json:"href,omitempty"`
	Label   string  `json:"label"`
}

type WorkspaceCardSignal struct {
	Description  string `json:"description"`
	Href         string `json:"href"`
	ID           string `json:"id"`
	ServingLabel string `json:"servingLabel"`
	Title        string `json:"title"`
}

type WorkspaceDetailSectionSignal struct {
	Code  *string                 `json:"code,omitempty"`
	Facts *[]DefinitionFactSignal `json:"facts,omitempty"`
	Lang  *string                 `json:"lang,omitempty"`
	Table *RecordTableSignal      `json:"table,omitempty"`
	Title string                  `json:"title"`
}

type WorkspacePageEnvelope struct {
	Chrome          ChromeSignal           `json:"chrome"`
	Page            WorkspacePageSignal    `json:"page"`
	Runtime         RouteRuntimeSignal     `json:"runtime"`
	Status          DashboardStatus        `json:"status"`
	WorkspaceAccess *WorkspaceAccessSignal `json:"workspaceAccess,omitempty"`
}

type WorkspacePageSignal struct {
	AssetList   *WorkspaceAssetListSignal `json:"assetList,omitempty"`
	Cards       *[]WorkspaceCardSignal    `json:"cards,omitempty"`
	Description *string                   `json:"description,omitempty"`
	Environment *string                   `json:"environment,omitempty"`
	Kind        RouteKind                 `json:"kind"`
	Title       string                    `json:"title"`
	WorkspaceID *string                   `json:"workspaceId,omitempty"`
}

type WorkspaceTabSignal struct {
	Active bool   `json:"active"`
	Count  *int64 `json:"count,omitempty"`
	Href   string `json:"href"`
	ID     string `json:"id"`
	Label  string `json:"label"`
}
