package signals

func ContractTypes() map[string]any {
	return map[string]any{
		"AdminContentSectionSignal":    AdminContentSectionSignal{},
		"AdminMetricSignal":            AdminMetricSignal{},
		"AdminPageEnvelope":            AdminPageEnvelope{},
		"AdminPageSignal":              AdminPageSignal{},
		"CatalogDashboardSignal":       CatalogDashboardSignal{},
		"CatalogPageEnvelope":          CatalogPageEnvelope{},
		"CatalogPageSignal":            CatalogPageSignal{},
		"ChatEnvelope":                 ChatEnvelope{},
		"ChatPageSignal":               ChatPageSignal{},
		"ChatSignal":                   ChatSignal{},
		"ChromeSignal":                 ChromeSignal{},
		"ConnectionsPageEnvelope":      ConnectionsPageEnvelope{},
		"ConnectionsPageSignal":        ConnectionsPageSignal{},
		"DefinitionFactSignal":         DefinitionFactSignal{},
		"DashboardComponentSignal":     DashboardComponentSignal{},
		"DashboardEnvelope":            DashboardEnvelope{},
		"DashboardPageNavSignal":       DashboardPageNavSignal{},
		"DashboardPageSignal":          DashboardPageSignal{},
		"LoginPageEnvelope":            LoginPageEnvelope{},
		"LoginPageSignal":              LoginPageSignal{},
		"MetricGridBadgeSignal":        MetricGridBadgeSignal{},
		"MetricGridColumnSignal":       MetricGridColumnSignal{},
		"MetricGridSignal":             MetricGridSignal{},
		"RouteRuntimeSignal":           RouteRuntimeSignal{},
		"SidebarGroupSignal":           SidebarGroupSignal{},
		"SidebarItemSignal":            SidebarItemSignal{},
		"SidebarSignal":                SidebarSignal{},
		"SubSidebarItemSignal":         SubSidebarItemSignal{},
		"SubSidebarSignal":             SubSidebarSignal{},
		"WorkspaceAccessSignal":        WorkspaceAccessSignal{},
		"WorkspaceActionSignal":        WorkspaceActionSignal{},
		"WorkspaceAssetPageEnvelope":   WorkspaceAssetPageEnvelope{},
		"WorkspaceAssetPageSignal":     WorkspaceAssetPageSignal{},
		"WorkspaceAssetSummarySignal":  WorkspaceAssetSummarySignal{},
		"WorkspaceCardSignal":          WorkspaceCardSignal{},
		"WorkspaceDetailSectionSignal": WorkspaceDetailSectionSignal{},
		"WorkspaceAssetDetailsSignal":  WorkspaceAssetDetailsSignal{},
		"WorkspaceAssetLineageSignal":  WorkspaceAssetLineageSignal{},
		"WorkspacePageEnvelope":        WorkspacePageEnvelope{},
		"WorkspacePageSignal":          WorkspacePageSignal{},
		"WorkspaceTabSignal":           WorkspaceTabSignal{},
		"WorkspaceBreadcrumbSignal":    WorkspaceBreadcrumbSignal{},
	}
}
