import { describe, expect, test } from "bun:test";

import {
  SQUIRREL_APP_USER_MODEL_ID,
  handleSquirrelLifecycle,
} from "./squirrel-lifecycle.js";

describe("Squirrel.Windows lifecycle", () => {
  test("registers the per-user protocol and shortcut on install and update", () => {
    for (const event of ["--squirrel-install", "--squirrel-updated"]) {
      const calls: string[] = [];
      expect(
        handleSquirrelLifecycle({
          argv: ["LeapView.exe", event, "0.1.0"],
          packaged: true,
          platform: "win32",
          registerProtocol: () => {
            calls.push("register");
            return true;
          },
          removeProtocol: () => {
            calls.push("remove-protocol");
            return true;
          },
          runUpdate: (arguments_) => {
            calls.push(arguments_.join(" "));
          },
          scheduleQuit: () => {
            calls.push("quit");
          },
        }),
      ).toBe(true);
      expect(calls).toEqual([
        "register",
        "--createShortcut LeapView.exe",
        "quit",
      ]);
    }
  });

  test("removes per-user integration on uninstall and exits obsolete versions", () => {
    const uninstallCalls: string[] = [];
    expect(
      handleSquirrelLifecycle({
        argv: ["LeapView.exe", "--squirrel-uninstall", "0.1.0"],
        packaged: true,
        platform: "win32",
        registerProtocol: () => true,
        removeProtocol: () => {
          uninstallCalls.push("remove-protocol");
          return true;
        },
        runUpdate: (arguments_) => {
          uninstallCalls.push(arguments_.join(" "));
        },
        scheduleQuit: () => {
          uninstallCalls.push("quit");
        },
      }),
    ).toBe(true);
    expect(uninstallCalls).toEqual([
      "remove-protocol",
      "--removeShortcut LeapView.exe",
      "quit",
    ]);

    const obsoleteCalls: string[] = [];
    expect(
      handleSquirrelLifecycle({
        argv: ["LeapView.exe", "--squirrel-obsolete"],
        packaged: true,
        platform: "win32",
        registerProtocol: () => true,
        removeProtocol: () => true,
        runUpdate: () => {
          obsoleteCalls.push("update");
        },
        scheduleQuit: () => {
          obsoleteCalls.push("quit");
        },
      }),
    ).toBe(true);
    expect(obsoleteCalls).toEqual(["quit"]);
  });

  test("ignores development, other platforms, first run, and injected arguments", () => {
    const base = {
      registerProtocol: () => true,
      removeProtocol: () => true,
      runUpdate: () => {
        throw new Error("must not run");
      },
      scheduleQuit: () => {
        throw new Error("must not quit");
      },
    };
    for (const input of [
      {
        argv: ["LeapView.exe", "--squirrel-install"],
        packaged: false,
        platform: "win32" as const,
      },
      {
        argv: ["LeapView", "--squirrel-install"],
        packaged: true,
        platform: "darwin" as const,
      },
      {
        argv: ["LeapView.exe", "--squirrel-firstrun"],
        packaged: true,
        platform: "win32" as const,
      },
      {
        argv: ["LeapView.exe", "https://example.com", "--squirrel-install"],
        packaged: true,
        platform: "win32" as const,
      },
    ]) {
      expect(handleSquirrelLifecycle({ ...base, ...input })).toBe(false);
    }
  });

  test("pins the taskbar identity generated by the Squirrel package", () => {
    expect(SQUIRREL_APP_USER_MODEL_ID).toBe(
      "com.squirrel.leapview.LeapView",
    );
  });
});
