// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: serving_state.sql

package servingdb

import (
	"context"
	"database/sql"
)

const clearAssetEdgesForServingState = `-- name: ClearAssetEdgesForServingState :exec
DELETE FROM asset_edges WHERE serving_state_id = ?
`

func (q *Queries) ClearAssetEdgesForServingState(ctx context.Context, servingStateID string) error {
	_, err := q.db.ExecContext(ctx, clearAssetEdgesForServingState, servingStateID)
	return err
}

const clearAssetsForServingState = `-- name: ClearAssetsForServingState :exec
DELETE FROM assets WHERE serving_state_id = ?
`

func (q *Queries) ClearAssetsForServingState(ctx context.Context, servingStateID string) error {
	_, err := q.db.ExecContext(ctx, clearAssetsForServingState, servingStateID)
	return err
}

const createQuerySnapshotLease = `-- name: CreateQuerySnapshotLease :exec
INSERT INTO query_snapshot_leases (id, workspace_id, environment, serving_state_id, ducklake_snapshot_id, owner_id, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateQuerySnapshotLeaseParams struct {
	ID                 string `json:"id"`
	WorkspaceID        string `json:"workspace_id"`
	Environment        string `json:"environment"`
	ServingStateID     string `json:"serving_state_id"`
	DucklakeSnapshotID int64  `json:"ducklake_snapshot_id"`
	OwnerID            string `json:"owner_id"`
	ExpiresAt          string `json:"expires_at"`
}

func (q *Queries) CreateQuerySnapshotLease(ctx context.Context, arg CreateQuerySnapshotLeaseParams) error {
	_, err := q.db.ExecContext(ctx, createQuerySnapshotLease,
		arg.ID,
		arg.WorkspaceID,
		arg.Environment,
		arg.ServingStateID,
		arg.DucklakeSnapshotID,
		arg.OwnerID,
		arg.ExpiresAt,
	)
	return err
}

const createServingState = `-- name: CreateServingState :exec

INSERT INTO serving_states (id, workspace_id, project_id, environment, status, source, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateServingStateParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	Environment string `json:"environment"`
	Status      string `json:"status"`
	Source      string `json:"source"`
	CreatedBy   string `json:"created_by"`
}

// Serving-generation lifecycle, artifacts, leases, and activation state.
func (q *Queries) CreateServingState(ctx context.Context, arg CreateServingStateParams) error {
	_, err := q.db.ExecContext(ctx, createServingState,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Environment,
		arg.Status,
		arg.Source,
		arg.CreatedBy,
	)
	return err
}

const expireInactiveServingStates = `-- name: ExpireInactiveServingStates :exec
UPDATE serving_states
SET status = 'expired', error = ''
WHERE status = 'inactive'
  AND environment = ?1
`

func (q *Queries) ExpireInactiveServingStates(ctx context.Context, environment string) error {
	_, err := q.db.ExecContext(ctx, expireInactiveServingStates, environment)
	return err
}

const extendQuerySnapshotLease = `-- name: ExtendQuerySnapshotLease :execrows
UPDATE query_snapshot_leases
SET expires_at = ?
WHERE id = ?
  AND released_at IS NULL
`

type ExtendQuerySnapshotLeaseParams struct {
	ExpiresAt string `json:"expires_at"`
	ID        string `json:"id"`
}

func (q *Queries) ExtendQuerySnapshotLease(ctx context.Context, arg ExtendQuerySnapshotLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, extendQuerySnapshotLease, arg.ExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveServingState = `-- name: GetActiveServingState :one
SELECT d.id, d.workspace_id, d.status, d.digest, d.manifest_json, d.created_by, d.created_at, d.activated_at, d.error, d.environment, d.ducklake_snapshot_id, d.source, d.superseded_at, d.project_id, d.project_digest, d.project_workspaces_json, d.access_policy_json, d.dashboard_publications_json
FROM serving_states d
JOIN workspace_active_serving_states active ON active.serving_state_id = d.id
WHERE active.workspace_id = ? AND active.environment = ?
`

type GetActiveServingStateParams struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
}

func (q *Queries) GetActiveServingState(ctx context.Context, arg GetActiveServingStateParams) (ServingState, error) {
	row := q.db.QueryRowContext(ctx, getActiveServingState, arg.WorkspaceID, arg.Environment)
	var i ServingState
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Status,
		&i.Digest,
		&i.ManifestJson,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.Error,
		&i.Environment,
		&i.DucklakeSnapshotID,
		&i.Source,
		&i.SupersededAt,
		&i.ProjectID,
		&i.ProjectDigest,
		&i.ProjectWorkspacesJson,
		&i.AccessPolicyJson,
		&i.DashboardPublicationsJson,
	)
	return i, err
}

const getArtifactByServingState = `-- name: GetArtifactByServingState :one
SELECT id, serving_state_id, workspace_id, digest, format, path, manifest_json, size_bytes, created_at, environment FROM serving_state_artifacts WHERE serving_state_id = ?
`

func (q *Queries) GetArtifactByServingState(ctx context.Context, servingStateID string) (ServingStateArtifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByServingState, servingStateID)
	var i ServingStateArtifact
	err := row.Scan(
		&i.ID,
		&i.ServingStateID,
		&i.WorkspaceID,
		&i.Digest,
		&i.Format,
		&i.Path,
		&i.ManifestJson,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.Environment,
	)
	return i, err
}

const getServingState = `-- name: GetServingState :one
SELECT id, workspace_id, status, digest, manifest_json, created_by, created_at, activated_at, error, environment, ducklake_snapshot_id, source, superseded_at, project_id, project_digest, project_workspaces_json, access_policy_json, dashboard_publications_json FROM serving_states WHERE id = ?
`

func (q *Queries) GetServingState(ctx context.Context, id string) (ServingState, error) {
	row := q.db.QueryRowContext(ctx, getServingState, id)
	var i ServingState
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Status,
		&i.Digest,
		&i.ManifestJson,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.Error,
		&i.Environment,
		&i.DucklakeSnapshotID,
		&i.Source,
		&i.SupersededAt,
		&i.ProjectID,
		&i.ProjectDigest,
		&i.ProjectWorkspacesJson,
		&i.AccessPolicyJson,
		&i.DashboardPublicationsJson,
	)
	return i, err
}

const insertAsset = `-- name: InsertAsset :exec
INSERT INTO assets (snapshot_id, logical_asset_id, workspace_id, serving_state_id, asset_type, asset_key, parent_logical_asset_id, title, description, source_file, payload_schema, payload_json, content_hash)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAssetParams struct {
	SnapshotID           string `json:"snapshot_id"`
	LogicalAssetID       string `json:"logical_asset_id"`
	WorkspaceID          string `json:"workspace_id"`
	ServingStateID       string `json:"serving_state_id"`
	AssetType            string `json:"asset_type"`
	AssetKey             string `json:"asset_key"`
	ParentLogicalAssetID string `json:"parent_logical_asset_id"`
	Title                string `json:"title"`
	Description          string `json:"description"`
	SourceFile           string `json:"source_file"`
	PayloadSchema        string `json:"payload_schema"`
	PayloadJson          string `json:"payload_json"`
	ContentHash          string `json:"content_hash"`
}

func (q *Queries) InsertAsset(ctx context.Context, arg InsertAssetParams) error {
	_, err := q.db.ExecContext(ctx, insertAsset,
		arg.SnapshotID,
		arg.LogicalAssetID,
		arg.WorkspaceID,
		arg.ServingStateID,
		arg.AssetType,
		arg.AssetKey,
		arg.ParentLogicalAssetID,
		arg.Title,
		arg.Description,
		arg.SourceFile,
		arg.PayloadSchema,
		arg.PayloadJson,
		arg.ContentHash,
	)
	return err
}

const insertAssetEdge = `-- name: InsertAssetEdge :exec
INSERT INTO asset_edges (id, workspace_id, serving_state_id, from_logical_asset_id, to_logical_asset_id, edge_type)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAssetEdgeParams struct {
	ID                 string `json:"id"`
	WorkspaceID        string `json:"workspace_id"`
	ServingStateID     string `json:"serving_state_id"`
	FromLogicalAssetID string `json:"from_logical_asset_id"`
	ToLogicalAssetID   string `json:"to_logical_asset_id"`
	EdgeType           string `json:"edge_type"`
}

func (q *Queries) InsertAssetEdge(ctx context.Context, arg InsertAssetEdgeParams) error {
	_, err := q.db.ExecContext(ctx, insertAssetEdge,
		arg.ID,
		arg.WorkspaceID,
		arg.ServingStateID,
		arg.FromLogicalAssetID,
		arg.ToLogicalAssetID,
		arg.EdgeType,
	)
	return err
}

const insertServingStateArtifact = `-- name: InsertServingStateArtifact :exec
INSERT INTO serving_state_artifacts (id, serving_state_id, workspace_id, environment, digest, format, path, manifest_json, size_bytes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(serving_state_id) DO UPDATE SET
  environment = excluded.environment,
  digest = excluded.digest,
  format = excluded.format,
  path = excluded.path,
  manifest_json = excluded.manifest_json,
  size_bytes = excluded.size_bytes
`

type InsertServingStateArtifactParams struct {
	ID             string `json:"id"`
	ServingStateID string `json:"serving_state_id"`
	WorkspaceID    string `json:"workspace_id"`
	Environment    string `json:"environment"`
	Digest         string `json:"digest"`
	Format         string `json:"format"`
	Path           string `json:"path"`
	ManifestJson   string `json:"manifest_json"`
	SizeBytes      int64  `json:"size_bytes"`
}

func (q *Queries) InsertServingStateArtifact(ctx context.Context, arg InsertServingStateArtifactParams) error {
	_, err := q.db.ExecContext(ctx, insertServingStateArtifact,
		arg.ID,
		arg.ServingStateID,
		arg.WorkspaceID,
		arg.Environment,
		arg.Digest,
		arg.Format,
		arg.Path,
		arg.ManifestJson,
		arg.SizeBytes,
	)
	return err
}

const listActiveDuckLakeSnapshots = `-- name: ListActiveDuckLakeSnapshots :many
SELECT DISTINCT ducklake_snapshot_id
FROM serving_states
WHERE ducklake_snapshot_id > 0
  AND environment = ?1
  AND status = 'active'
ORDER BY ducklake_snapshot_id
`

func (q *Queries) ListActiveDuckLakeSnapshots(ctx context.Context, environment string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDuckLakeSnapshots, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var ducklake_snapshot_id int64
		if err := rows.Scan(&ducklake_snapshot_id); err != nil {
			return nil, err
		}
		items = append(items, ducklake_snapshot_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveServingStateScopes = `-- name: ListActiveServingStateScopes :many
SELECT workspace_id, environment
FROM workspace_active_serving_states
ORDER BY workspace_id, environment
`

type ListActiveServingStateScopesRow struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
}

func (q *Queries) ListActiveServingStateScopes(ctx context.Context) ([]ListActiveServingStateScopesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveServingStateScopes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveServingStateScopesRow{}
	for rows.Next() {
		var i ListActiveServingStateScopesRow
		if err := rows.Scan(&i.WorkspaceID, &i.Environment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetEdgesByServingState = `-- name: ListAssetEdgesByServingState :many
SELECT id, workspace_id, serving_state_id, from_logical_asset_id, to_logical_asset_id, edge_type, created_at FROM asset_edges WHERE serving_state_id = ? ORDER BY edge_type, from_logical_asset_id, to_logical_asset_id
`

func (q *Queries) ListAssetEdgesByServingState(ctx context.Context, servingStateID string) ([]AssetEdge, error) {
	rows, err := q.db.QueryContext(ctx, listAssetEdgesByServingState, servingStateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetEdge{}
	for rows.Next() {
		var i AssetEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ServingStateID,
			&i.FromLogicalAssetID,
			&i.ToLogicalAssetID,
			&i.EdgeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetVersions = `-- name: ListAssetVersions :many
SELECT
  d.id AS serving_state_id,
  d.workspace_id,
  d.environment,
  d.status,
  d.digest,
  d.created_by,
  d.created_at,
  d.activated_at,
  a.snapshot_id,
  a.logical_asset_id,
  a.source_file,
  a.content_hash
FROM serving_states d
JOIN assets a ON a.serving_state_id = d.id
WHERE d.workspace_id = ?
  AND d.environment = ?
  AND a.logical_asset_id = ?
  AND d.source = 'publish'
  AND d.status IN ('active', 'draining', 'inactive', 'validated')
  AND NOT EXISTS (
    SELECT 1
    FROM serving_states newer
    JOIN assets newer_asset ON newer_asset.serving_state_id = newer.id
    WHERE newer.workspace_id = d.workspace_id
      AND newer.environment = d.environment
      AND newer.source = 'publish'
      AND newer.status IN ('active', 'draining', 'inactive', 'validated')
      AND newer_asset.logical_asset_id = a.logical_asset_id
      AND newer_asset.content_hash = a.content_hash
      AND (
        COALESCE(newer.activated_at, newer.created_at) > COALESCE(d.activated_at, d.created_at)
        OR (
          COALESCE(newer.activated_at, newer.created_at) = COALESCE(d.activated_at, d.created_at)
          AND newer.created_at > d.created_at
        )
        OR (
          COALESCE(newer.activated_at, newer.created_at) = COALESCE(d.activated_at, d.created_at)
          AND newer.created_at = d.created_at
          AND newer.id > d.id
        )
      )
  )
ORDER BY
  COALESCE(d.activated_at, d.created_at) DESC,
  d.created_at DESC,
  d.id DESC
`

type ListAssetVersionsParams struct {
	WorkspaceID    string `json:"workspace_id"`
	Environment    string `json:"environment"`
	LogicalAssetID string `json:"logical_asset_id"`
}

type ListAssetVersionsRow struct {
	ServingStateID string         `json:"serving_state_id"`
	WorkspaceID    string         `json:"workspace_id"`
	Environment    string         `json:"environment"`
	Status         string         `json:"status"`
	Digest         string         `json:"digest"`
	CreatedBy      string         `json:"created_by"`
	CreatedAt      string         `json:"created_at"`
	ActivatedAt    sql.NullString `json:"activated_at"`
	SnapshotID     string         `json:"snapshot_id"`
	LogicalAssetID string         `json:"logical_asset_id"`
	SourceFile     string         `json:"source_file"`
	ContentHash    string         `json:"content_hash"`
}

func (q *Queries) ListAssetVersions(ctx context.Context, arg ListAssetVersionsParams) ([]ListAssetVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetVersions, arg.WorkspaceID, arg.Environment, arg.LogicalAssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetVersionsRow{}
	for rows.Next() {
		var i ListAssetVersionsRow
		if err := rows.Scan(
			&i.ServingStateID,
			&i.WorkspaceID,
			&i.Environment,
			&i.Status,
			&i.Digest,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.SnapshotID,
			&i.LogicalAssetID,
			&i.SourceFile,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByServingState = `-- name: ListAssetsByServingState :many
SELECT snapshot_id, logical_asset_id, workspace_id, serving_state_id, asset_type, asset_key, parent_logical_asset_id, title, description, payload_schema, payload_json, content_hash, created_at, source_file FROM assets WHERE serving_state_id = ? ORDER BY asset_type, asset_key
`

func (q *Queries) ListAssetsByServingState(ctx context.Context, servingStateID string) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsByServingState, servingStateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.SnapshotID,
			&i.LogicalAssetID,
			&i.WorkspaceID,
			&i.ServingStateID,
			&i.AssetType,
			&i.AssetKey,
			&i.ParentLogicalAssetID,
			&i.Title,
			&i.Description,
			&i.PayloadSchema,
			&i.PayloadJson,
			&i.ContentHash,
			&i.CreatedAt,
			&i.SourceFile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForeignEnvironmentDuckLakeSnapshots = `-- name: ListForeignEnvironmentDuckLakeSnapshots :many
SELECT DISTINCT ducklake_snapshot_id
FROM serving_states
WHERE ducklake_snapshot_id > 0
  AND environment <> ?1
  AND status <> 'deleted'
ORDER BY ducklake_snapshot_id
`

func (q *Queries) ListForeignEnvironmentDuckLakeSnapshots(ctx context.Context, environment string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listForeignEnvironmentDuckLakeSnapshots, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var ducklake_snapshot_id int64
		if err := rows.Scan(&ducklake_snapshot_id); err != nil {
			return nil, err
		}
		items = append(items, ducklake_snapshot_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeasedDuckLakeSnapshots = `-- name: ListLeasedDuckLakeSnapshots :many
SELECT DISTINCT ducklake_snapshot_id
FROM query_snapshot_leases
WHERE ducklake_snapshot_id > 0
  AND environment = ?1
  AND released_at IS NULL
  AND expires_at > CURRENT_TIMESTAMP
ORDER BY ducklake_snapshot_id
`

func (q *Queries) ListLeasedDuckLakeSnapshots(ctx context.Context, environment string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listLeasedDuckLakeSnapshots, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var ducklake_snapshot_id int64
		if err := rows.Scan(&ducklake_snapshot_id); err != nil {
			return nil, err
		}
		items = append(items, ducklake_snapshot_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferencedDuckLakeSnapshots = `-- name: ListReferencedDuckLakeSnapshots :many
SELECT DISTINCT ducklake_snapshot_id
FROM serving_states
WHERE ducklake_snapshot_id > 0
  AND environment = ?1
  AND status = 'active'
ORDER BY ducklake_snapshot_id
`

func (q *Queries) ListReferencedDuckLakeSnapshots(ctx context.Context, environment string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listReferencedDuckLakeSnapshots, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var ducklake_snapshot_id int64
		if err := rows.Scan(&ducklake_snapshot_id); err != nil {
			return nil, err
		}
		items = append(items, ducklake_snapshot_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeleteScheduledServingStatesDeleted = `-- name: MarkDeleteScheduledServingStatesDeleted :exec
UPDATE serving_states
SET status = 'deleted', error = ''
WHERE status = 'delete_scheduled'
  AND environment = ?1
`

func (q *Queries) MarkDeleteScheduledServingStatesDeleted(ctx context.Context, environment string) error {
	_, err := q.db.ExecContext(ctx, markDeleteScheduledServingStatesDeleted, environment)
	return err
}

const markDrainingServingStatesDeleteScheduled = `-- name: MarkDrainingServingStatesDeleteScheduled :exec
UPDATE serving_states
SET status = 'delete_scheduled', error = ''
WHERE status = 'draining'
  AND environment = ?1
`

func (q *Queries) MarkDrainingServingStatesDeleteScheduled(ctx context.Context, environment string) error {
	_, err := q.db.ExecContext(ctx, markDrainingServingStatesDeleteScheduled, environment)
	return err
}

const markOtherServingStatesDraining = `-- name: MarkOtherServingStatesDraining :exec
UPDATE serving_states
SET status = 'draining',
    superseded_at = CURRENT_TIMESTAMP,
    error = ''
WHERE workspace_id = ?
  AND environment = ?
  AND id <> ?
  AND status = 'active'
`

type MarkOtherServingStatesDrainingParams struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
	ID          string `json:"id"`
}

func (q *Queries) MarkOtherServingStatesDraining(ctx context.Context, arg MarkOtherServingStatesDrainingParams) error {
	_, err := q.db.ExecContext(ctx, markOtherServingStatesDraining, arg.WorkspaceID, arg.Environment, arg.ID)
	return err
}

const markOtherServingStatesInactive = `-- name: MarkOtherServingStatesInactive :exec
UPDATE serving_states
SET status = 'inactive'
WHERE workspace_id = ? AND environment = ? AND id <> ? AND status = 'active'
`

type MarkOtherServingStatesInactiveParams struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
	ID          string `json:"id"`
}

func (q *Queries) MarkOtherServingStatesInactive(ctx context.Context, arg MarkOtherServingStatesInactiveParams) error {
	_, err := q.db.ExecContext(ctx, markOtherServingStatesInactive, arg.WorkspaceID, arg.Environment, arg.ID)
	return err
}

const markServingStateActive = `-- name: MarkServingStateActive :exec
UPDATE serving_states
SET status = 'active', activated_at = CURRENT_TIMESTAMP, error = ''
WHERE id = ?
`

func (q *Queries) MarkServingStateActive(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markServingStateActive, id)
	return err
}

const releaseExpiredQuerySnapshotLeases = `-- name: ReleaseExpiredQuerySnapshotLeases :exec
UPDATE query_snapshot_leases
SET released_at = CURRENT_TIMESTAMP
WHERE released_at IS NULL
  AND environment = ?1
  AND expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) ReleaseExpiredQuerySnapshotLeases(ctx context.Context, environment string) error {
	_, err := q.db.ExecContext(ctx, releaseExpiredQuerySnapshotLeases, environment)
	return err
}

const releaseQuerySnapshotLease = `-- name: ReleaseQuerySnapshotLease :exec
UPDATE query_snapshot_leases
SET released_at = COALESCE(released_at, CURRENT_TIMESTAMP)
WHERE id = ?
`

func (q *Queries) ReleaseQuerySnapshotLease(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, releaseQuerySnapshotLease, id)
	return err
}

const scheduleExpiredServingStateDeletion = `-- name: ScheduleExpiredServingStateDeletion :exec
UPDATE serving_states
SET status = 'delete_scheduled', error = ''
WHERE status = 'expired'
  AND environment = ?1
`

func (q *Queries) ScheduleExpiredServingStateDeletion(ctx context.Context, environment string) error {
	_, err := q.db.ExecContext(ctx, scheduleExpiredServingStateDeletion, environment)
	return err
}

const setActiveServingState = `-- name: SetActiveServingState :exec
INSERT INTO workspace_active_serving_states (workspace_id, environment, serving_state_id, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(workspace_id, environment) DO UPDATE SET
  serving_state_id = excluded.serving_state_id,
  updated_at = CURRENT_TIMESTAMP
`

type SetActiveServingStateParams struct {
	WorkspaceID    string `json:"workspace_id"`
	Environment    string `json:"environment"`
	ServingStateID string `json:"serving_state_id"`
}

func (q *Queries) SetActiveServingState(ctx context.Context, arg SetActiveServingStateParams) error {
	_, err := q.db.ExecContext(ctx, setActiveServingState, arg.WorkspaceID, arg.Environment, arg.ServingStateID)
	return err
}

const updateServingStateDuckLakeSnapshot = `-- name: UpdateServingStateDuckLakeSnapshot :exec
UPDATE serving_states
SET ducklake_snapshot_id = ?
WHERE id = ?
`

type UpdateServingStateDuckLakeSnapshotParams struct {
	DucklakeSnapshotID int64  `json:"ducklake_snapshot_id"`
	ID                 string `json:"id"`
}

func (q *Queries) UpdateServingStateDuckLakeSnapshot(ctx context.Context, arg UpdateServingStateDuckLakeSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, updateServingStateDuckLakeSnapshot, arg.DucklakeSnapshotID, arg.ID)
	return err
}

const updateServingStateStatus = `-- name: UpdateServingStateStatus :exec
UPDATE serving_states
SET status = ?, error = ?
WHERE id = ?
`

type UpdateServingStateStatusParams struct {
	Status string `json:"status"`
	Error  string `json:"error"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateServingStateStatus(ctx context.Context, arg UpdateServingStateStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateServingStateStatus, arg.Status, arg.Error, arg.ID)
	return err
}

const updateServingStateValidated = `-- name: UpdateServingStateValidated :exec
UPDATE serving_states
SET status = ?, project_id = ?, project_digest = ?, project_workspaces_json = ?, access_policy_json = ?, dashboard_publications_json = ?, digest = ?, manifest_json = ?, error = ''
WHERE id = ?
`

type UpdateServingStateValidatedParams struct {
	Status                    string `json:"status"`
	ProjectID                 string `json:"project_id"`
	ProjectDigest             string `json:"project_digest"`
	ProjectWorkspacesJson     string `json:"project_workspaces_json"`
	AccessPolicyJson          string `json:"access_policy_json"`
	DashboardPublicationsJson string `json:"dashboard_publications_json"`
	Digest                    string `json:"digest"`
	ManifestJson              string `json:"manifest_json"`
	ID                        string `json:"id"`
}

func (q *Queries) UpdateServingStateValidated(ctx context.Context, arg UpdateServingStateValidatedParams) error {
	_, err := q.db.ExecContext(ctx, updateServingStateValidated,
		arg.Status,
		arg.ProjectID,
		arg.ProjectDigest,
		arg.ProjectWorkspacesJson,
		arg.AccessPolicyJson,
		arg.DashboardPublicationsJson,
		arg.Digest,
		arg.ManifestJson,
		arg.ID,
	)
	return err
}
