// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package manageddb

import (
	"database/sql"
)

type ManagedDataCollection struct {
	ID             string         `json:"id"`
	ProjectID      string         `json:"project_id"`
	ConnectionName string         `json:"connection_name"`
	Name           string         `json:"name"`
	Description    string         `json:"description"`
	Status         string         `json:"status"`
	CreatedBy      string         `json:"created_by"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
	ArchivedAt     sql.NullString `json:"archived_at"`
}

type ManagedDataEnvironmentPointer struct {
	CollectionID string `json:"collection_id"`
	Environment  string `json:"environment"`
	RevisionID   string `json:"revision_id"`
	DeploymentID string `json:"deployment_id"`
	Generation   int64  `json:"generation"`
	UpdatedBy    string `json:"updated_by"`
	UpdatedAt    string `json:"updated_at"`
}

type ManagedDataRevision struct {
	ID           string         `json:"id"`
	CollectionID string         `json:"collection_id"`
	Sequence     int64          `json:"sequence"`
	Digest       string         `json:"digest"`
	Status       string         `json:"status"`
	ManifestJson string         `json:"manifest_json"`
	FileCount    int64          `json:"file_count"`
	SizeBytes    int64          `json:"size_bytes"`
	CreatedBy    string         `json:"created_by"`
	CreatedAt    string         `json:"created_at"`
	ReadyAt      sql.NullString `json:"ready_at"`
	Error        string         `json:"error"`
}

type ManagedDataRevisionFile struct {
	RevisionID  string `json:"revision_id"`
	LogicalPath string `json:"logical_path"`
	SizeBytes   int64  `json:"size_bytes"`
	Sha256      string `json:"sha256"`
	StorageKey  string `json:"storage_key"`
	MediaType   string `json:"media_type"`
	Etag        string `json:"etag"`
	CreatedAt   string `json:"created_at"`
}

type ManagedDataS3MultipartPart struct {
	MultipartUploadID string `json:"multipart_upload_id"`
	PartNumber        int64  `json:"part_number"`
	SizeBytes         int64  `json:"size_bytes"`
	Sha256            string `json:"sha256"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type ManagedDataS3MultipartUpload struct {
	ID                    string         `json:"id"`
	UploadSessionID       string         `json:"upload_session_id"`
	LogicalPath           string         `json:"logical_path"`
	Sha256                string         `json:"sha256"`
	SizeBytes             int64          `json:"size_bytes"`
	ObjectKey             string         `json:"object_key"`
	ProviderUploadID      string         `json:"provider_upload_id"`
	Status                string         `json:"status"`
	Existing              int64          `json:"existing"`
	IdempotencyIdentity   string         `json:"idempotency_identity"`
	CompletionIdentity    string         `json:"completion_identity"`
	CompletionRequestHash string         `json:"completion_request_hash"`
	AbortIdentity         string         `json:"abort_identity"`
	CreatedAt             string         `json:"created_at"`
	UpdatedAt             string         `json:"updated_at"`
	CompletedAt           sql.NullString `json:"completed_at"`
	AbortedAt             sql.NullString `json:"aborted_at"`
	Error                 string         `json:"error"`
}

type ManagedDataServingStateBinding struct {
	ServingStateID string `json:"serving_state_id"`
	CollectionID   string `json:"collection_id"`
	RevisionID     string `json:"revision_id"`
	Environment    string `json:"environment"`
	BoundAt        string `json:"bound_at"`
}

type ManagedDataUploadSession struct {
	ID                string         `json:"id"`
	CollectionID      string         `json:"collection_id"`
	BaseRevisionID    sql.NullString `json:"base_revision_id"`
	RevisionID        sql.NullString `json:"revision_id"`
	Status            string         `json:"status"`
	ManifestJson      string         `json:"manifest_json"`
	ExpectedFileCount int64          `json:"expected_file_count"`
	ExpectedSizeBytes int64          `json:"expected_size_bytes"`
	UploadedFileCount int64          `json:"uploaded_file_count"`
	UploadedSizeBytes int64          `json:"uploaded_size_bytes"`
	StorageBackend    string         `json:"storage_backend"`
	StagingPrefix     string         `json:"staging_prefix"`
	CreatedBy         string         `json:"created_by"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
	ExpiresAt         string         `json:"expires_at"`
	CompletedAt       sql.NullString `json:"completed_at"`
	Error             string         `json:"error"`
}
